### ISSUE TITLE
Support for ESP8266

### ISSUE THREAD

**Issue by JasonSwindle** [aws/amazon-freertos#1]
Howdy,

Support for ESP8266 would be wonderful, as it would open up this to a large group of IOT devices.

**Comment by ourairquality** [comment]
The esp-open-rtos framework for the esp8266 uses a recent version of FreeRTOS and https://github.com/SuperHouse/esp-open-rtos/pull/500 updates this to use this code. But the IP network layer uses lwip, and newlib is used for the C library, and there are a few ssl options being explored, so it is not using all of the stack here.

**Comment by adjervis** [comment]
Thank you for the valuable feedback. Such requests are important to us and we will take them into consideration in prioritizing our support for the ESP8266 device. In the meantime, you might find this link helpful: https://github.com/SuperHouse/esp-open-rtos.

**Comment by gaborgsomogyi** [comment]
Any update on this?

**Comment by aggarg** [comment]
Thank you for checking. The Amazon FreeRTOS does not support ESP8266 as of now. However we do support ESP32.

We will keep you updated if anything changes.

Thanks.

**Comment by ahmedwahdan** [comment]
Any updates?

**Comment by jasonbrowan** [comment]
Do you have plan to port to ESP8266?
Thanks.

**Comment by cr8myf8** [comment]
+1 for support on the ESP8266

**Comment by n-sviridenko** [comment]
+1, still relevant

**Comment by rokkino** [comment]
hiii
