### ISSUE TITLE
license inconsistent

### ISSUE THREAD

**Issue by jlovejoy** [aws/amazon-freertos#10]
Hi, 
While you have the standard MIT license in your LICENSE file, yet you have a modified version in some files with an additional line: https://github.com/aws/amazon-freertos/blob/master/lib/include/aws_mqtt_agent.h as well as here: https://www.freertos.org/a00114.html

Could you please just use the standard version instead of license proliferating? 

Thanks!

**Comment by hyandell** [comment]
Agreed; we're changing it.

**Comment by hyandell** [comment]
Fixed :)

**Comment by jlovejoy** [comment]
thanks.  The FreeRTOS webpage still needs to also be updated :)
https://www.freertos.org/a00114.html
