### ISSUE TITLE
FreeRTOS+TCP should flush its ARP cache on network-down

### ISSUE THREAD

**Issue by dcgaws** [aws/amazon-freertos#100]
From the perspective of a typical IoT use case, one possible tradeoff in flushing the ARP cache unconditionally in response to network down in FreeRTOS_IP.c (see prvProcessNetworkDownEvent) is if the node is experiencing intermittent connectivity (i.e. rather than an actual disconnect/reconnect to a different network). If temporary network outages are causing network down, then the cache entries are still valid, and the cost could be a flood of broadcast traffic.

Nevertheless, I think that this is the right thing to do. As a sanity check, desktop operating systems appear to flush the ARP cache for a given port in response to disconnect.

**Comment by abhidixi11** [comment]
Closing this since pull request is tracked in  https://github.com/aws/amazon-freertos/pull/101
