### ISSUE TITLE
Is mBED TLS Thread safe

### ISSUE THREAD

**Issue by shanmugav** [aws/amazon-freertos#107]
I see that the mBED TLS doesnt have the support for multithreading. The definition MBEDTLS_THREADING_C is not defined. Can we use AWS TLS sockets from more than one task?

**Comment by huguesBouvier** [comment]
It seems you are using an older version the new one has MBEDTLS_THREADING_C :
https://github.com/aws/amazon-freertos/blob/4e6095ce3300fb81b18b3e458ba5e1eacc55849a/lib/third_party/mbedtls/include/mbedtls/config.h#L2573)

One older version of FreeRTOS threadsafety is ensured by mutex and disabling interrupt so it should be fine. I still recommend updating to the latest version.
