### ISSUE TITLE
ESP32 Compilation without Bluetooth

### ISSUE THREAD

**Issue by supreetd21** [aws/amazon-freertos#1152]
**Describe the bug**
Compilation of the aws_demos app using Espressif's SDK

**System information**
- Which hardware board or part numbers? [ESP32]
- IDE used [Editor- VSCode]
- Operating System [MacOS]
- Version of Amazon FreeRTOS (run ``git describe --tags`` to find it) - 201906.00_Major-496-g22a1744b
- Project [amazon-freertos/vendors/espressif/boards/esp32/aws_demos]

**Expected behavior**
The amazon-freertos/vendors/espressif/boards/esp32/aws_demos application should compile even with bluetooth disabled.

**Screenshots or console output**
In file included from /Users/supreetdeshpande/Desktop/Repositories/amazon-freertos/vendors/espressif/boards/esp32/ports/ble/iot_ble_hal_common_gap.c:31:0:
/Users/supreetdeshpande/Desktop/Repositories/amazon-freertos/vendors/espressif/boards/esp32/ports/ble/bluedroid/iot_ble_hal_common_gap.c:33:29: fatal error: esp_gap_ble_api.h: No such file or directory
compilation terminated.

**To reproduce**
- cd amazon-freertos/vendors/espressif/boards/esp32/aws_demos
- make menuconfig
Go to Component Config -> Bluetooth. Disable Bluetooth.
- make

Thank you!

**Comment by danhorner** [comment]
Hello @supreetd21, 

Were you able to give the CMake build a try?  Please feel free to reopen this ticket if you have further questions.
