### ISSUE TITLE
Cannot find FreeRTOS+{CLI,UDP,Trace,IO} modules

### ISSUE THREAD

**Issue by free-easy** [aws/amazon-freertos#1177]
**Describe the bug**
Hi,
it seems that the FreeRTOS Plus modules (CLI, UPD, Trace, IO) are not present in this repository.
It there any reason for that?

**Comment by free-easy** [comment]
![Screenshot from 2019-09-01 11-21-32](https://user-images.githubusercontent.com/20483759/64074377-aff3ae00-ccaa-11e9-997c-def16e3d07f3.png)

Ok, it seems that the lack of some modules is due to licensing issues, but still, I wasn't able to find the CLI module.

**Comment by 0x3333** [comment]
Exactly what I'm looking for. I could not find it. Will search a little more.

**Comment by htibosch** [comment]
Did you have a look on [freertos.org/plus](https://freertos.org/FreeRTOS-Plus/index.html).
Yes I think that you have, because there it shows the picture.
Some of the products of FreeRTOS have not ( yet ) been adopted in the AWS/FreeRTOS repository. But on the mentioned page on freertos.org, you will find the downloads that you are looking for,

**Comment by free-easy** [comment]
The reason for which I prefer to use this repository is that it integrates better with our git workflow (i.e. having dependencies as submodules).
I'd like to avoid resorting to downloading a zip from freertos.org/plus or maintaining a git mirror of the SVN repository that is on SourceForge. I'm aware of some unofficial mirror of FreeRTOS (https://github.com/coldnew/FreeRTOS-mirror), but too bad that it's unofficial.

**Comment by 0x3333** [comment]
I found the sources here:

https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS-Plus/Source/

**Comment by htibosch** [comment]
> I'm aware of some unofficial mirror of [FreeRTOS](https://github.com/coldnew/FreeRTOS-mirror), but too bad that it's unofficial.

I suppose that you have seen the new **official** [GIT repository of AWS/FreeRTOS](https://github.com/aws/amazon-freertos)? You will find the kernel, FreeRTOS+TCP and a lot more, like e.g. secure sockets/TLS. For the some other FreeRTOS products (CLI, UPD, Trace, IO, FreeRTOS+FAT), you will have to consult the [SVN on sourceforge](https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS-Plus/Source).

**Comment by dan4thewin** [comment]
Hi, @free-easy and @0x3333 .  We value your feedback.  Although I don't have any timelines to offer, I'd like to assure you we are working to improve the way we distribute FreeRTOS and related software.  Thank you.
