### ISSUE TITLE
Using OTA and MQTT together 

### ISSUE THREAD

**Issue by wayne-david** [aws/amazon-freertos#1191]
Iam trying to integrate esp-idf blink example with the aws-freertos OTA demo on esp32.I have build the aws-OTA demo and it works fine.How do I add my code to the OTA demo so that I have blink code running and also have OTA agent running on my esp32.

**Comment by chegewara** [comment]
Because AWSFreeRTOS does not support shared connection you will need to create separate connections from OTA Job and mqtt and take care of connection cleaning for each of them in case disconnection is longer than keep alive.

**Comment by wayne-david** [comment]
Thanks Chegewara ,my real issue is how do I edit the OTA code to add my custom code eg.blink in it.I tried formating the OTA code to be a task and then added the blink code compartible with esp-idf as another task.I then called the tasks with xTaskCreate.AWS have not given an example of how to integrate custom code with aws-freertos.If I could have any example of aws-freertos integrated with other esp-idf code,I will be good to go.

**Comment by chegewara** [comment]
Dont touch OTA code, try to add your own code here:
https://github.com/aws/amazon-freertos/blob/master/vendors/espressif/boards/esp32/aws_demos/application_code/main.c#L132
or here (depends on your needs):
https://github.com/aws/amazon-freertos/blob/master/vendors/espressif/boards/esp32/aws_demos/application_code/main.c#L129

**Comment by wayne-david** [comment]
@chegewara you are a savior,all along I wondered where app-main was.I was doing it wrong.Thanks alot.Do you have a link to the source of your information.Thanks so much

**Comment by chegewara** [comment]
Yes, my brain.

**Comment by wayne-david** [comment]
@chegewara alright,if am allowed to ask,was the code in the main essenstial or I can create my own clean main file.

**Comment by chegewara** [comment]
I think you can create new main file, but to me it is much easier to start with existing file and delete code i dont need or add my own code.

**Comment by wayne-david** [comment]
Thanks,I appreciate alot

**Comment by sameerdasarwad** [comment]
> Because AWSFreeRTOS does not support shared connection you will need to create separate connections from OTA Job and mqtt and take care of connection cleaning for each of them in case disconnection is longer than keep alive.

@chegewara  as  i you say if MQTT and OTA cannot run same time what if i have sensor which update shadow for every second and i also want keep running the OTA job for check new updates ...

**Comment by gordonwang0** [comment]
Hi,

It is now possible to share the MQTT connection used with OTA.  The MQTT connection is given to the OTA agent as `pvControlClient` in the `OTA_ConnectionContext_t`.  See this [line in the demo](https://github.com/aws/amazon-freertos/blob/557307c44ed828cd598692cc82c53869a86973b3/demos/ota/aws_iot_ota_update_demo.c#L251).  The application may use this connection for other purposes too.

**Comment by sameerdasarwad** [comment]
so it is possible to share connection and run both ota and shadow together

**Comment by pedroramireslima** [comment]
@sameerdasarwad were you able to isolate the mqtt connection from the aws ota example?

**Comment by pedroramireslima** [comment]
> Yes, my brain and 2 commercial projects (closed source).

@chegewara do you have any code example using the ota example from aws and mqtt connection in other topics?
