### ISSUE TITLE
JavaScript file missing and logging an error in console generatorGeneric.js net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by michaeljcalkins** [aws/amazon-freertos#1193]
**Describe the bug**
The script include found at https://github.com/aws/amazon-freertos/blob/master/tools/certificate_configuration/PEMfileToCString.html#L8 does not exist and shows a console error.

**System information**
- Operating System 
MacOS and Chrome

- Version of Amazon FreeRTOS (run ``git describe --tags`` to find it)
Latest
https://github.com/aws/amazon-freertos/blob/master/tools/certificate_configuration/PEMfileToCString.html

**Expected behavior**
No error in console.

**Screenshots or console output**
![Screen Shot 2019-09-05 at 4 32 33 PM](https://user-images.githubusercontent.com/8272012/64390717-cd9e7b80-cffa-11e9-84bc-3cce09da1308.png)

**To reproduce**

1. Navigate to `file:///SOME_PATH_HERE/amazon-freertos-master/tools/certificate_configuration/PEMfileToCString.html`
1. Open up the console
1. You will see that an error `GET file:///.../amazon-freertos-master/tools/certificate_configuration/js/generatorGeneric.js net::ERR_FILE_NOT_FOUND`

**Comment by alexa-noxon** [comment]
Thanks for pointing this out.  We've merged a fix to resolve it.
