### ISSUE TITLE
Cortex-v8M Support

### ISSUE THREAD

**Issue by cyliangtw** [aws/amazon-freertos#1207]
About Cortex-V8M support, the portable code are at [/portable/ARMv8M](https://github.com/aws/amazon-freertos/tree/master/freertos_kernel/portable/ARMv8M).
But, I can't find any platform/project link ARMv8M code in current repo. .
More, I also can't find this portable code relative to tool chain "Keil".

**Describe the solution you would like.**  
1. Kiel is much popular in our customer base, when will it support one more tool chain "Keil" ?
2. It's not easy to integrate the existing AmazonFreeRTOS libs with secure & non-secure framework. For ex, which one project need link `ARM_CM23_NTZ` and which one should link `ARM_CM23`. It's better to apply the relative code on one real platform/project for reference.

Thank you!

**Comment by RichardBarry** [comment]
Hi,

You can find pre-configured projects, including for Keil, here:

https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Demo/CORTEX_MPU_M33F_NXP_LPC55S69_MCUXpresso     ( https://www.freertos.org/RTOS-Cortex-M33-LPC55S69-MCUXpresso-GCC.html )

https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Demo/CORTEX_MPU_M33F_Simulator_Keil_GCC     ( https://www.freertos.org/RTOS-Cortex-M33-Keil-Simulator.html )

https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Demo/CORTEX_MPU_M23_Nuvoton_NuMaker_PFM_M2351_IAR_GCC   ( https://www.freertos.org/RTOS-Cortex-M23-NuMaker-PFM-M2351-Keil.html )
