### ISSUE TITLE
Publish to mqtt topic from inside Application_code

### ISSUE THREAD

**Issue by wayne-david** [aws/amazon-freertos#1209]
I have tested mqtt demo and it works fine.I would like to be able to make the mqtt work inside the application_code.

**Comment by dan4thewin** [comment]
Hi, @wayne-david.  There's some good documentation here: https://www.freertos.org/mqtt/index.html

There's also an active discussion forum that's a great resource for questions and answers:
https://sourceforge.net/p/freertos/discussion/
