### ISSUE TITLE
iot_ble_wifi_provisioning: list_networks never responds if 0 networks found

### ISSUE THREAD

**Issue by matteoscordino** [aws/amazon-freertos#1277]
**Describe the bug**
If the wifi scan succeeds, but finds 0 networks, a response is never returned to the BLE central.

**System information**
- Which hardware board or part numbers? ESP32
- IDE used: CLion, CMake
- Operating System: Linux host
- Version of Amazon FreeRTOS: master
- Project Custom Application. 

**Expected behavior**
An error response should be returned to let the mobile app handle the situation

**To reproduce**

1. make sure no network is in range of the device (e.g. desolder the antenna, use a shielding box)
2. send a listNetwork request (e.g. with the iOS BLE demo app)

**Comment by gordonwang0** [comment]
Hi @matteoscordino,

It looks like a pull request addressing this issue was merged.  I will close this issue; please reopen if you have any follow-up.
