### ISSUE TITLE
TICC3220:  Extra line termination character in PEM files created using openssl causes connection to broker to fail

### ISSUE THREAD

**Issue by bgintz-rsc** [aws/amazon-freertos#128]
Certificate and private key files generated using openssl have an additional line teriminating character after the PEM trailer:

-----END CERTIFICATE-----
----END RSA PRIVATE KEY-----

Connections to the broker will fail using files including this character but succeed if the termination is stripped.   

Note:  This character is not present in files generated by vDevModeKeyProvisioning().

**Comment by pvyawaha** [comment]
Thank you for reporting this. I was unable to reproduce the issue. The keys and certificates provisioned on CC3220SF using vDevModeKeyProvisioning() has only terminating newline character i.e 0x0A.
Can you please confirm if you have any other terminating characters in the keys that you are using? Also which host platform and Amazon FreeRTOS version you are using?
