### ISSUE TITLE
Inlcude file paths not correct for XMC Dave projects

### ISSUE THREAD

**Issue by pflegezentrum** [aws/amazon-freertos#1338]
After importing the Dave XMC projects, the projects do not compile.
The include file paths for the http_parser are not correct.

Project aws_test Problems:
Invalid project path: Include path not found (C:\Users\wedl\Documents\Repositories\amazon-freertos\libraries\3rdparty\http-parser).	aws_tests		pathentry	Path Entry Problem

Build Fail:
'Building file: C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.c'
'Invoking: ARM-GCC C Compiler'
"C:/Users/wedl/Dave/DAVE_4-4-2_64bit_2018-02-23/DAVE-IDE-4.4.2-64Bit/eclipse/ARM-GCC-49/bin/arm-none-eabi-gcc" -MMD -MT "libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o" -DXMC4800_F100x2048 -DUNITY_INCLUDE_CONFIG_H -DAMAZON_FREERTOS_ENABLE_UNIT_TESTS -DUSE_CMDLIB_WITH_RTOS -DMBEDTLS_ECDSA_SIGN_ALT -DMBEDTLS_ECDSA_VERIFY_ALT -DMBEDTLS_ECDH_COMPUTE_SHARED_ALT -DMBEDTLS_ECDH_GEN_PUBLIC_ALT -DPAL_OS_HAS_EVENT_INIT -Dpkcs11configIMPORT_PRIVATE_KEYS_SUPPORTED=0 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../freertos_kernel/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/CMSIS/Include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/drivers/inc -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/third_party/ESP_AT_Lib/src/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/CMSIS/Infineon/XMC4800_series/Include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/DAVE_Generated/XMC4800 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/application_code/infineon_code -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../freertos_kernel/portable/GCC/ARM_CM4F -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../tests/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/mbedtls/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/common/include/private -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/common/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/platform/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/platform/freertos/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/secure_sockets/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/tls/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/crypto/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/pkcs11/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/ota/test -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/pkcs11/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/utils/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/wifi/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../demos/dev_mode_key_provisioning/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/defender/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/test/access -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/serializer/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/shadow/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/shadow/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/test/access -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/test -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/posix/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/ports/posix -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/pal/xmc4800_freertos -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/optiga/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/examples/ecdsa_utils -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/pkcs11 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/freertos_plus_posix/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/defender/src/private -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/mbedtls/include/mbedtls -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/pkcs11/mbedtls -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/pkcs11 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/unity/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/unity/extras/fixture/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/tinycbor -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/http-parser -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/jsmn -O1 -ffunction-sections -fdata-sections -fno-common -Wall -std=c99 -mfloat-abi=softfp -Wa,-adhlns="libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o.lst" -pipe -c -fmessage-length=0 -MMD -MP -MF"libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.d" -MT"libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.d libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -g -gdwarf-2 -o "libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o" "C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.c" 
libraries/c_sdk/standard/https/test/unit/subdir.mk:42: recipe for target 'libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o' failed
In file included from C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.h:43:0,
                 from C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.c:30:
c:\users\wedl\documents\repositories\amazon-freertos\libraries\c_sdk\standard\https\src\private\iot_https_internal.h:39:25: fatal error: http_parser.h: No such file or directory
 #include "http_parser.h"
                         ^
compilation terminated.
make: *** [libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.o] Error 1
'Building file: C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.c'
'Invoking: ARM-GCC C Compiler'
"C:/Users/wedl/Dave/DAVE_4-4-2_64bit_2018-02-23/DAVE-IDE-4.4.2-64Bit/eclipse/ARM-GCC-49/bin/arm-none-eabi-gcc" -MMD -MT "libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.o" -DXMC4800_F100x2048 -DUNITY_INCLUDE_CONFIG_H -DAMAZON_FREERTOS_ENABLE_UNIT_TESTS -DUSE_CMDLIB_WITH_RTOS -DMBEDTLS_ECDSA_SIGN_ALT -DMBEDTLS_ECDSA_VERIFY_ALT -DMBEDTLS_ECDH_COMPUTE_SHARED_ALT -DMBEDTLS_ECDH_GEN_PUBLIC_ALT -DPAL_OS_HAS_EVENT_INIT -Dpkcs11configIMPORT_PRIVATE_KEYS_SUPPORTED=0 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../freertos_kernel/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/CMSIS/Include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/drivers/inc -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/third_party/ESP_AT_Lib/src/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/CMSIS/Infineon/XMC4800_series/Include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/XMCLib/2.1.20/DAVE_Generated/XMC4800 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/application_code/infineon_code -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../freertos_kernel/portable/GCC/ARM_CM4F -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../tests/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/mbedtls/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/aws_tests/config_files -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/common/include/private -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/common/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/platform/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/platform/freertos/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/secure_sockets/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/tls/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/crypto/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/pkcs11/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/ota/test -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/pkcs11/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/utils/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/wifi/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../demos/dev_mode_key_provisioning/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/defender/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/test/access -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/mqtt/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/serializer/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/shadow/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/shadow/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/test/access -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/standard/https/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/test -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/aws/greengrass/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/posix/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/boards/xmc4800_plus_optiga_trust_x/ports/posix -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/pal/xmc4800_freertos -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/optiga/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/optiga_trust_x/examples/ecdsa_utils -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../vendors/infineon/secure_elements/pkcs11 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/freertos_plus/standard/freertos_plus_posix/include -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/c_sdk/aws/defender/src/private -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/mbedtls/include/mbedtls -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/abstractions/pkcs11/mbedtls -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/pkcs11 -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/unity/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/unity/extras/fixture/src -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/tinycbor -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/http-parser -IC:/Users/wedl/Documents/Repositories/amazon-freertos/projects/infineon/xmc4800_plus_optiga_trust_x/dave4/aws_tests/../../../../../libraries/3rdparty/jsmn -O1 -ffunction-sections -fdata-sections -fno-common -Wall -std=c99 -mfloat-abi=softfp -Wa,-adhlns="libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.o.lst" -pipe -c -fmessage-length=0 -MMD -MP -MF"libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.d" -MT"libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.d libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.o" -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mthumb -g -gdwarf-2 -o "libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.o" "C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.c" 
In file included from C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_common.h:43:0,
                 from C:/Users/wedl/Documents/Repositories/amazon-freertos/libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.c:31:
libraries/c_sdk/standard/https/test/unit/subdir.mk:36: recipe for target 'libraries/c_sdk/standard/https/test/unit/iot_tests_https_client.o' failed
c:\users\wedl\documents\repositories\amazon-freertos\libraries\c_sdk\standard\https\src\private\iot_https_internal.h:39:25: fatal error: http_parser.h: No such file or directory
 #include "http_parser.h"

**Comment by pavanmr94** [comment]
Fixed on master: https://github.com/aws/amazon-freertos/commit/d25fa87dc6d069059ff747a0c2b5e9ba2c2ebe90
