### ISSUE TITLE
Support T-HEAD processor 

### ISSUE THREAD

**Issue by cui632** [aws/amazon-freertos#1463]
Hi , 
I am desired to port T-HEAD processor in FreeRTOS. the porting project is done. I wonder to know how to request to merge it into FreeRTOS. 

Vincent

**Comment by RichardBarry** [comment]
Grateful if you can provide a link to the T-HEAD processor - thanks.

**Comment by cui632** [comment]
https://www.t-head.cn/product/s802?spm=a2ouz.12987056.0.0.429248abc8ds69&lang=en

Richard, please have a look. 
We still have RISC-V core which is scheduled to support FreeRTOS in future 


发自我的iPhone

**Comment by cui632** [comment]
Hi Rechard

Have you check the processor link I paste?

Vincent 

发自我的iPhone

**Comment by RichardBarry** [comment]
It is not clear what the core is from the link.  Could you please contact me using the 'business contact' link on https://www.freertos.org/contact so we can discuss in more detail - thanks.

**Comment by lundinc2** [comment]
Hello, I am closing this issue as the conversation has moved to email. Please reopen if you would like to discuss this further via this forum.
