### ISSUE TITLE
Serializer comments incorrectly specify JSON and not CBOR encoding

### ISSUE THREAD

**Issue by jnz86** [aws/amazon-freertos#1472]
Very minor, but took me a second to track down.

Some files correctly state JSON or CBOR encoding as serialize options.
Example 
amazon-freertos/libraries/c_sdk/standard/serializer/include/iot_serializer.h 
```
/*
 * This library is to provide a consistent layer for serializing JSON-like format.
 * The implementations can be CBOR or JSON.
 */
```

Other files like do not, and go further by specifying JSON when in the demos it's CBOR.
amazon-freertos/libraries/c_sdk/standard/ble/include/iot_ble_mqtt_serialize.h 
```
/**
 * @brief Deserialize a CONNACK message received from MQTT BLE Proxy.
 *
 * Deserialize the CONNACK parameters from JSON structure format received from MQTT BLE proxy.
 *
```

The latter is incorrect, it's using CBOR best I can tell.

It's minor, I know. But I spent too long tracking down the 
#define IOT_BLE_MESG_ENCODER               ( _IotSerializerCborEncoder )
that hinted it was CBOR and not JSON.

Applies to more than just the example, these are the Doxygen comments, so would also translate into documentation.

IIRC, the MQTToverBLE proxy did initially use JSON.

**Comment by ravibhagavandas** [comment]
Hi,
Thank you for pointing this out. I have raised a PR to fix the documentation.
