### ISSUE TITLE
TimeOut_t doesn't work with vTaskSetTimeOutState

### ISSUE THREAD

**Issue by D252874** [aws/amazon-freertos#1507]
**Describe the bug**

**System information**
- somlabs VisionCB-RT-STD
- MCUXpresso
- Windows
- V10.0.1
- Custom Application
- 
```cpp
void modenTerminalTask(void* param){
	TickType_t xTicksToWait = 5000;
	TimeOut_t xTimeOut;
	char text[2] = {0};
	char resived[2] = {0};
	while(1)
	{
		LPUART_ReadBlocking(LPUART1, (uint8_t*)text, 1);
		LPUART_WriteBlocking(LPUART2, (uint8_t*)text, 1);
		vTaskSetTimeOutState(xTimeOut);

		while(strlen(resived) >= 1)
		{
			LPUART_ReadBlocking(LPUART2, (uint8_t*)resived, 1);
			if (xTaskCheckForTimeOut( &xTimeOut, &xTicksToWait ) != pdFALSE)
			{
				printf("break");
				break;
			}

		}
		LPUART_WriteBlocking(LPUART1, (uint8_t*)resived, 1);
		resived[0] = 0;
	}
}
```

**Expected behavior**
that my ide doesn't give an error on this line
		vTaskSetTimeOutState(xTimeOut);

**To reproduce**
NVT

**Code to reproduce the bug**
look above

If the code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

thanks in advance
if it is not an bug what should i use instead then

**Comment by lundinc2** [comment]
Hello @D252874,

I see on the line
```c
 vTaskSetTimeOutState(xTimeOut);
```
A TimeOut_t struct is passed in, but vTaskSetTimeOutState takes a pointer to a TimeOut_t struct.

So if you change said line to
```c
 vTaskSetTimeOutState(&xTimeOut);
```
That should fix the error you are seeing on that line.

**Comment by D252874** [comment]
oke this fixed it
