### ISSUE TITLE
Compile error in ES-WiFi driver for stm32l475_discovery

### ISSUE THREAD

**Issue by sakian** [aws/amazon-freertos#1508]
When using UART for interfacing with the ES-WiFi module, the driver has a compile error in es_wifi.c (located under vendors/st/stm32l475_discovery/BSP/Components/es_wifi).

The compile error appears on line 1753, where the ptr variable is used in the ES_WIFI_StartServerSingleConn. This variable is never declared in the function.

Thank you!

**Comment by lundinc2** [comment]
Hello @sakian,

Thank you for raising this issue. I am investigating.

**Comment by lundinc2** [comment]
Hello @sakian,

We have now merged your fix! Thank you for your contribution.
