### ISSUE TITLE
Package manager support - Conan etc.

### ISSUE THREAD

**Issue by shreyasbharath** [aws/amazon-freertos#1517]
Hi,

I was wondering if there is any planned support for package managers like Conan and the like in the near future?

We use Amazon FreeRTOS and it would help us a lot if it were a package.

Thanks.

**Comment by dnoal** [comment]
Thank you for this input.  We have no near term plans to support Conan or any package manager but this is something we are looking at.

**Comment by shreyasbharath** [comment]
Good to hear you are considering it :)

**Comment by yuhui-zheng** [comment]
I'm closing this issue for now, since we have it in "Feature Request". Thanks, both.
