### ISSUE TITLE
Forced use of RSA Keys for TLS Sockets on TI Platform

### ISSUE THREAD

**Issue by tparsh** [aws/amazon-freertos#154]
For the CC3220_Launchpad SecureSockets definition there is a forced use of SL_SEC_MASK_TLS_RSA_WITH_AES_128_GCM_SHA256.  I require the use of a different crypto standard (Elliptic-Curve fun).  As far as I can tell, TI supports a rather large list of different PKI/shared key/hashing pairs, so is there a reason that SL_SEC_MASK_TLS_RSA_WITH_AES_128_GCM_SHA256 is hardcoded?  If there is no real reason, it would be good if this could be a parameter (configurable per socket).

**Comment by gordonwang0** [comment]
Hi @tparsh,

We chose that cipher suite for compatibility with AWS Greengrass.  You may change that to a different cipher suite if you do not use Greengrass (and the new cipher suite is [supported by AWS IoT](https://docs.aws.amazon.com/iot/latest/developerguide/iot-security-identity.html#tls-cipher-suite-support)).
