### ISSUE TITLE
publish in MQTT server

### ISSUE THREAD

**Issue by Arunir5** [aws/amazon-freertos#160]
Hi all
I've to publish in MQTT server info of a freeRTOS cue (2 char elements). I'm looking for an examples. (with a MSP432 texas)
can anyone tell me where can find examples about it?

tnx!

**Comment by gordonwang0** [comment]
Hi @Arunir5,

We don't have an example specifically for the MSP 432.

However, you may look at the MQTT hello world demo on the TI CC3220SF.
