### ISSUE TITLE
AWS IoT Device Tester build and flash Script for MediaTek

### ISSUE THREAD

**Issue by Joyadam2** [aws/amazon-freertos#1627]
Hi,

I have MediaTek MT7697Hx Development Kit and everything is working fine.
Now, I want to test with the IDT (for the learning purpose).

**How to write the build and flash script for this?**

Could anybody help me with this?
Thanks

**Comment by dcgaws** [comment]
Hello, what IDE and tool chain are you using for compiling and flashing?

**Comment by dcgaws** [comment]
Regarding Keil, based on http://www.keil.com/support/man/docs/uv4/uv4_commandline.htm, you can do:

START /WAIT UV4.exe -b {project_path}/{project_file} -j0 -o build.log 
- and -
START /WAIT UV4.exe -f {project_path}/{project_file} -j0 -o build.log
