### ISSUE TITLE
Fix warnings in ESP32 build

### ISSUE THREAD

**Issue by dcgaws** [aws/amazon-freertos#1648]
Per this proposed PR, #1629, there is a lot compiler warnings in Amazon FreeRTOS library code when building ESP32. However, rather than suppressing those warnings at compile time, the code itself needs to be fixed at each site.

**Comment by mahavirj** [comment]
Might as well remove some of already included flags at:
https://github.com/aws/amazon-freertos/blob/master/vendors/espressif/boards/esp32/CMakeLists.txt#L340-L360

**Comment by qiutongs** [comment]
We are tracking this issue internally.
