### ISSUE TITLE
Does it possible build freeRTOS with LLVM clang compiler?

### ISSUE THREAD

**Issue by boofish** [aws/amazon-freertos#1650]
Hi, building FreeRTOS with default cross-compiler is enough for application development, but it has some difficulty to analysis the security of the generated code, and it's hard to employ advanced technology such as LLVM instrumentation.

However, the compiler of LLVM is convenient for various analysis work, it also provide supporting for ARM arch. 

So is it possible to build FreeRTOS with LLVM clang compiler?  

Thank you!

**Comment by dcgaws** [comment]
Hello, in the interest of merging this issue/thread with your questions on https://github.com/aws/amazon-freertos/issues/48, the armclang compiler is available here https://developer.arm.com/tools-and-software/embedded/arm-compiler.

**Comment by boofish** [comment]
Thank you!
