### ISSUE TITLE
CMAKE build outside amazon-freertos folder still problematic

### ISSUE THREAD

**Issue by teuteuguy** [aws/amazon-freertos#1732]
**Describe the bug**
Based on https://github.com/tgsong/amazon-freertos-examples which showcases how to build an ESP32 based project with components outside the amazon-freertos folder structure, there still seems to be issues achieving the cmake.

Easy to reproduce by reverting the aws_iot_network_config.h file to espressif's version in the amazon-freertos folder.
Effectively: 
#define configENABLED_NETWORKS      ( AWSIOT_NETWORK_TYPE_WIFI )
to what the espressif vendor code has for that file:
#define configENABLED_NETWORKS      ( AWSIOT_NETWORK_TYPE_WIFI | AWSIOT_NETWORK_TYPE_BLE )

**System information**
- Which hardware board or part numbers? ESP32
- IDE used: vscode
- Operating System [MacOS]
- Version of Amazon FreeRTOS 201912.00-23-ga89fca8da
- Project [MQTT]

**Expected behavior**
Should compile with no errors.
In theory, should be able to take any of the demos and run them outside the amazon-freertos project structure.

**Error**
CMakeFiles/afr_demo.dir/src/main.c.obj:(.literal.prvMiscInitialization+0x1c): undefined reference to `NumericComparisonInit'
CMakeFiles/afr_demo.dir/src/main.c.obj: In function `prvMiscInitialization':
/Users/tcruse/Downloads/tests/tgsong/amazon-freertos-examples/build/../src/main.c:161: undefined reference to `NumericComparisonInit'
CMakeFiles/afr_demo.dir/amazon-freertos/demos/network_manager/aws_iot_network_manager.c.obj:(.literal._bleRegisterUnregisterCb+0x4): undefined reference to `BLEGAPPairingStateChangedCb'
CMakeFiles/afr_demo.dir/amazon-freertos/demos/network_manager/aws_iot_network_manager.c.obj:(.literal._bleRegisterUnregisterCb+0x8): undefined reference to `BLENumericComparisonCb'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Thank you!

**Comment by qiutongs** [comment]
I am able to reproduce the linking error you saw after enabled AWSIOT_NETWORK_TYPE_BLE.
This is expected because the proper dependency module (demo_ble_numeric_comparison) isn't configured in the CMake. That is why the functions defined in that module were complained as errors by linker.

After adding below dependency to https://github.com/tgsong/amazon-freertos-examples/blob/master/CMakeLists.txt#L29, it should build.
```
target_link_libraries(afr_demo 
    PRIVATE 
        AFR::demo_mqtt
        AFR::demo_ble_numeric_comparison
)
```
