### ISSUE TITLE
How to use older versions

### ISSUE THREAD

**Issue by heshananupama** [aws/amazon-freertos#1740]
Hi,
Could I please know the way to use the older versions? I could download the zip files, but I could not find the way to generate build files and then compiling the demo projects as I did for the latest version as described in the getting starter guide documentation. Is there a place to get the older starter guides? I just need to compile demo applications with different versions for the research purposes. Could somebody provide me an idea to achieve my goal. Thank you.

**Comment by qiutongs** [comment]
Unfortunately, we don't have user documents for the Amazon FreeRTOS versions you want. You can open projects on the target platform. For example, here is the Windows Simulator project of v1.2.7 https://github.com/aws/amazon-freertos/tree/v1.2.7/demos/pc/windows/visual_studio

And you can still use our latest document for reference(how to use IDE, change configuration, what to expect in demo). https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_windows.html

**Comment by heshananupama** [comment]
I figured this out. The main issue was I was using Cmake to do the builds in the newest version. I was thinking and trying to do the same for the older versions. However, later I realized that Cmake was added like more recently and did used the IDE based approach as it was described in the user documentation. It worked. Thanks. I am closing the issue.
