### ISSUE TITLE
Reconnect (the Paho library style)

### ISSUE THREAD

**Issue by stefanoco** [aws/amazon-freertos#18]
The Eclipse Paho MQTT library provides a method `mosquitto_reconnect()` useful in order to restart a broken connection to a broker. Is there anything similar here? What's the suggested policy?

**Comment by alexa-noxon** [comment]
At this time a reconnect function is not provided, and applications must call connect again with the same connection parameters.  
Thank you for the input and we will consider support for automatic reconnect functionality in the future.

**Comment by stefanoco** [comment]
Would you consider pull requests on this or any other development?

**Comment by alexa-noxon** [comment]
We are still working on our pull request process and guidelines.  We welcome contributions to the project, but the decisions and criteria on whether each change will be merged will be shared in a forthcoming update.

**Comment by xiongyu0523** [comment]
Any process on auto reconnect?

**Comment by stefanoco** [comment]
can't see any contribution policy so far so didn't invest on this

**Comment by lt72** [comment]
We are re-writing MQTT to be transport independent in the context of supporting BLE in Amazon FreeRTOS. We did not implement auto-reconnect yet, but it is definitely on our radar. Please check the [ble beta branch](https://github.com/aws/amazon-freertos/tree/feature/ble-beta) in this repo and/or the [v4_beta](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta) branch in C-SDK for the latest updates. It is a work in progress, but we'd like your feedback! 
P.S. the C-SDK is slightly ahead...

**Comment by stefanoco** [comment]
@lt72 we may have a chance of testing this new branch in the next few weeks, thanks for commenting

**Comment by dcgaws** [comment]
@stefanoco and @xiongyu0523, hello, our new MQTT library interface can be found in [iot_mqtt.h](https://github.com/aws/amazon-freertos/blob/master/libraries/c_sdk/standard/mqtt/include/iot_mqtt.h). While we have not implemented reconnect, we do have an [official contribution policy](https://github.com/aws/amazon-freertos/blob/master/CONTRIBUTING.md) and welcome pull requests.
