### ISSUE TITLE
aws_iot_ota_agent.c fail to compile if OTA_DEBUG_LOG_LEVEL > 1

### ISSUE THREAD

**Issue by egoltzman** [aws/amazon-freertos#1916]
**Describe the bug**
In file aws_iot_ota_agent.c in the function prvShutdownHandler the DEFINE_OTA_METHOD_NAME( "prvShutdownHandler" ); is missing and if the OTA_DEBUG_LOG_LEVEL is bigger then 1 (that is OTA_LOG_L2 is being used) the compilation fail

**System information**
- STM L475
- CubeIDE
- Windows
- 10.3
- Custom Application / OTA

**Expected behavior**
Compile successfully

**Screenshots or console output**
error: 'OTA_METHOD_NAME' undeclared (first use in this function); did you mean 'DEFINE_OTA_METHOD_NAME'?
  OTA_LOG_L2( "[%s] Shutting Down OTA Agent. %d\r\n", OTA_METHOD_NAME );
                                                                                           ^~~~~~~~~~~~~~~
                                                                                           DEFINE_OTA_METHOD_NAME

**To reproduce**

1. Change #define OTA_DEBUG_LOG_LEVEL  to 2 in aws_iot_ota_agent.h
2. build

**Code to reproduce the bug**

**Additional context**

The fix:
static OTA_Err_t prvShutdownHandler( OTA_EventData_t * pxEventData )
{
    **DEFINE_OTA_METHOD_NAME( "prvShutdownHandler" );**

Thank you!

**Comment by pvyawaha** [comment]
Hello, 

Thank you for reporting this issue. 

The fix for this issue is merged in PR https://github.com/aws/amazon-freertos/pull/1919.
