### ISSUE TITLE
Handshake Failed

### ISSUE THREAD

**Issue by WaterDemo** [aws/amazon-freertos#1974]
Hello, I want to ask a question. 
I used the development board CC3220SF-LAUNCHXL to burn AmazonFreeRTOS. When I run code in debug mode on CCS, I can communicate with the server normally. But when I burned the bin file into the board with uniflash, the following error occurred：

![WeChat0bd4e4c7a8f017275ffd9ea6ac18fe0f](https://user-images.githubusercontent.com/12165768/81034961-77584400-8ecb-11ea-8ee0-01a752d62375.png)

Why did this happen? Looking forward to your reply. Thank you！

**Comment by tgsong** [comment]
Error -456 seems like related to the root certificate,
https://github.com/aws/amazon-freertos/blob/8106b1d280daec3d0b4aa33d08a9e9785f7baeab/vendors/ti/SimpleLink_CC32xx/v2_10_00_04/source/ti/drivers/net/wifi/errors.h#L126
How did you burn the bin file to board? Can you try following this doc? https://docs.aws.amazon.com/freertos/latest/userguide/burn-initial-firmware-ti.html

**Comment by WaterDemo** [comment]
It solved my problem perfectly, thank you very much!
