### ISSUE TITLE
Version string still says 9.0.0

### ISSUE THREAD

**Issue by thomask77** [aws/amazon-freertos#2]
https://github.com/aws/amazon-freertos/blob/5068f430f8139725a7280e936c406106d0ba8964/lib/include/task.h#L47

**Comment by adjervis** [comment]
This version string is incorrect – thank you for pointing it out. It has been noted and will be corrected.

**Comment by alexa-noxon** [comment]
This has been updated in commit 6620031aed80bd411c87baeef501ac884cfd1b1a.
