### ISSUE TITLE
Wifi connection unsuccessful sometimes on ESP32 device.

### ISSUE THREAD

**Issue by aehrath** [aws/amazon-freertos#202]
I am running into an issue, where on an ESP32S device (similar to DevkitC) the device will fail to connect to my wifi 50% of the time or so. 
My test setup is a Win 10 box running Ubuntu in a VM.
I am running the AWS shadow sample code.
Here is the failure:
I (207) phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0
I (217) wifi: mode : sta (30:ae:a4:1c:98:60)
I (217) WIFI: SYSTEM_EVENT_STA_START
I (2627) WIFI: SYSTEM_EVENT_STA_DISCONNECTED
1 253 [main] WiFi failed to connect to AP.

**Comment by mradulan** [comment]
The network connection via VM is generally unreliable. Although can you check which configuration your `Network Adapter` is using (NAT or Bridged)? Also were you able to connect to the Wifi on your Windows host machine?

**Comment by aehrath** [comment]
What you said does not make sense. The wifi connection between the ESP32 and my wifi network has nothing to do with the host machine. It connects directly to the wifi, circumventing the host. The only thing the host does, is receive log messages and send commands to the device. The ESP32 connects fine to my network about 50% of the time or so. (more or less random)

**Comment by mradulan** [comment]
There are some steps which will help debug more:
1. Can you use WIFI_Scan method defined in [this ](https://github.com/aws/amazon-freertos/blob/master/lib/include/aws_wifi.h#L126It)header to check the signal strength?
2. What is the model of your AP?
3. There is a similar [issue](https://github.com/aws/amazon-freertos/issues/57) which might be useful.

**Comment by aehrath** [comment]
AP is netgear nighthawk. signal strength is between -65 to -68.

**Comment by aggarg** [comment]
Thank you for sharing the information. Would you please try the following steps to help us better understand the issue:
- Please try using a different network with better signal strength (-55 or better) for reliable connection.
- If that does not solve the problem, would you please take the code in this branch and share the logs: https://github.com/aws/amazon-freertos/tree/merge/ESPpatch

The above mentioned branch contains the latest ESP-IDF with enhanced logging which will help us debug the issue.

Thanks.

**Comment by yuhui-zheng** [comment]
This thread seems in inactive for ~three weeks. Please reach out again and reference this ticket, if things are still not working for you. Closing issue...
