### ISSUE TITLE
Undefined symbol ulTCPWindowTxSack (referred from freertos_tcp_ip.o)

### ISSUE THREAD

**Issue by cyliangtw** [aws/amazon-freertos#2026]
**Describe the bug**

in FreeRTOS_TCP_IP.c, `prvReadSackOption()` will call `ulTCPWindowTxSack()`. 
However, if platform not enable "ipconfigUSE_TCP_WIN", it will encounter "Undefined symbol ulTCPWindowTxSack" in linking.

Snippet of `prvReadSackOption()` as below:
```
static void prvReadSackOption( const uint8_t * const pucPtr,
							   size_t uxIndex,
							   FreeRTOS_Socket_t * const pxSocket )
{
uint32_t ulFirst = ulChar2u32( &( pucPtr[ uxIndex ] ) );
uint32_t ulLast  = ulChar2u32( &( pucPtr[ uxIndex + 4U ] ) );
uint32_t ulCount = ulTCPWindowTxSack( &( pxSocket->u.xTCP.xTCPWindow ), ulFirst, ulLast );;
```

**Comment by sarenameas** [comment]
Hello @cyliangtw ,

Thanks for bringing this up. We are looking into fixing this.

**Comment by htibosch** [comment]
Thanks for posting this. We were aware of it, but it was a busy week, we worked on a big release.
Right now I am preparing a PR to repair this.

Background: the TCP SACK (selective ACK) option is only used when both `ipconfigUSE_TCP` and `ipconfigUSE_TCP_WIN` are enabled.

**Comment by htibosch** [comment]
As I submitted a PR #2029 to solve this problem, I think that this issue can be closed?
Hein
