### ISSUE TITLE
Shadow_ClientConnect fails sometimes on ESP32 device.

### ISSUE THREAD

**Issue by aehrath** [aws/amazon-freertos#203]
I am running into an issue on an ESP32S device (similar to DevkitC) the shadow demo fails to connect the shadow client with error code 2 about 20% of the time.
My test setup is a Win 10 box running Ubuntu in a VM.
Below is the log:
6 345 [main] Key provisioning done...
I (4567) wifi: pm start, type:0

7 848 [MainDemoTask] Shadow_ClientConnect unsuccessful, returned 2.
8 849 [MainDemoTask] Failed to initialize Shadow client.

**Comment by abhidixi11** [comment]
Hello aehrath ! 
Can you please enable MQTT debug logs and see if you can get any more information? Thanks

**Comment by mradulan** [comment]
closing issue since no response received. Please reopen if the issue persists.

**Comment by Utsav22G** [comment]
> Hello aehrath !
> Can you please enable MQTT debug logs and see if you can get any more information? Thanks

How do I enable the debug logs? Is this specific to my IDE? Is there a C file I need to edit??

For context, I'm using NXP LPC54018 with MCUXpresso, and am getting the same error.
