### ISSUE TITLE
vLoggingPrint is not scheduler-safe

### ISSUE THREAD

**Issue by dcgaws** [aws/amazon-freertos#214]
In 'aws_demo_logging.c', there is the following function:

    void vLoggingPrint( const char * pcMessage )
    {
        printf( "%s", pcMessage );
        fflush(stdout);
    }

The functions printf() and fflush() are system calls, and they may hold-up the task ( put it to sleep ). When that happens, a next task may ( will ) become active in an improper way.

Hence after a while, it may happen that several FreeRTOS tasks are running simultaneously (!). The synchronicity will get totally lost.

We solved this problem by starting an extra (non-FreeRTOS) thread which takes care of the logging. That thread ( prvWin32LoggingThread ) may do system calls. It may not call any of the FreeRTOS API's though.

Communication between FreeRTOS and a non-FreeRTOS task may seem a bit primitive: non of the mechanisms may be used between the tasks, neither Windows, nor FreeRTOS API's.

The above code will most probably disturb tests that need multiple FreeRTOS tasks.

You can either change:

void vLoggingPrint( const char * pcMessage )
{
    vLoggingPrintf( "%s", pcMessage );
}

or, if you really don't want the time-stamps and so, we need to make a new logging function.

**Comment by sarenameas** [comment]
I have took this specific issue from #285 and it is in the code base: 61319c37179da9f1904fedbf4020bec5c802ab08
