### ISSUE TITLE
AWS CA1-CA4 Certs now in CC3220 Cert Store

### ISSUE THREAD

**Issue by tombresson** [aws/amazon-freertos#226]
As of [SimpleLink 2.40.00.05](http://www.ti.com/tool/download/SIMPLELINK-CC3220-SDK), TI now includes the AWS ATS Certs CA1-CA4 in their cert store.

The file `aws_secure_sockets.c` can now be revised to no longer disable the built-in cert store as it can be left enabled to satisfy the certificate chain.

In the mean-time, we've effectively commented out the relevant lines of code (listed below) to re-enable use of the built-in cert store.

https://github.com/aws/amazon-freertos/blob/3c16dfabb69410116a4fbff41f4a9975ded9b997/lib/secure_sockets/portable/ti/cc3220_launchpad/aws_secure_sockets.c#L397-L432

**Comment by dcgaws** [comment]
We're struggling a bit with the transition procedure that this change will require. If we remove the code block above as proposed, but the customer hasn't re-Uniflashed the board (or if the customer does re-Uniflash, but with an older version of the SDK), then the cloud connection will fail.

A second consideration, regarding boards that get migrated as above: is there a risk in leaving the old root cert as a user file?

**Comment by dcgaws** [comment]
@tombresson per my comment above, the risk of taking this change doesn't seem to outweigh the benefit. If you have further insight into smoothing the transition, please reopen this issue and let me know. In the meantime, I apologize for the delay in getting back to you.
