### ISSUE TITLE
CBOR ARRAY types 

### ISSUE THREAD

**Issue by rquilez** [aws/amazon-freertos#228]
I do not understand what is the point of  providing two different implementations of CBOR: aws_cbor and tiny_cbor with amazon freertos?

Concerning aws_cbor, encoding/decoding cbor ARRAY types are missing. Are you planning to develop then?

Thank you!

**Comment by alexa-noxon** [comment]
Hi rquilez,

It is recommended that you use tiny_cbor rather than aws_cbor.   aws_cbor is intended for internal use only, and there are not plans to develop those features at this time.
