### ISSUE TITLE
Dependency in the lwIP iot_secure_sockets.c file to the Wi-Fi library

### ISSUE THREAD

**Issue by vvelciu** [aws/amazon-freertos#2307]
There is a dependency in the lwIP iot_secure_sockets.c file to the Wi-Fi library. According to the qualification guide, it looks like the Wi-Fi library is not a requirement, as long as the device can connect to the AWS Cloud across a secure ethernet connection. 
 
![iot_secure_sockets](https://user-images.githubusercontent.com/11376393/88283116-7f1dcc80-ccf3-11ea-8206-c5447defd156.png)

Is this call to WIFI_GetHostIP intended?

**Comment by lundinc2** [comment]
Hello @vvelciu,

Thank you for reporting this issue, I have begun investigating.

**Comment by gkwicker** [comment]
Hi @vvelciu, thank you for bringing this to our attention.  I have merged a fix (see PR #2359) for it.  Please let us know if there is anything else we can help with on this issue.  Thanks again!
