### ISSUE TITLE
Unable to connect to GGC in docker using the GG discovery demo

### ISSUE THREAD

**Issue by OZsGit** [aws/amazon-freertos#2327]
**Describe the bug**
Running the GG discovery demo, ESP32 fails to connect to the Greengrass core if the GGC is running in a docker container. If GGC is running on the system not in a docker container it is able to connect.

**System information**
- Which hardware board or part numbers?: ESP32-WROVER-KIT
- IDE used: N/A
- Operating System: Windows 10 to flash the ESP32/Ubuntu 18.04.4 LTS running Docker 19.03.12 running Greengrass
- Version of FreeRTOS: 202007.00-96-g5c345b395
- Project: Greengrass discovery demo 

**Expected behavior**
The demo is expected to successfully discover the GGC, connect, and run the remaining demo tasks.

**Screenshots or console output**
[docker_image_inspect.txt](https://github.com/aws/amazon-freertos/files/5031762/docker_image_inspect.txt)
[ESP32_serial_out_fail.txt](https://github.com/aws/amazon-freertos/files/5031848/ESP32_serial_out_fail.txt)
[ESP32_serial_out_success.txt](https://github.com/aws/amazon-freertos/files/5031849/ESP32_serial_out_success.txt)
[ESP_to_GG_wireshark_captures.zip](https://github.com/aws/amazon-freertos/files/5031850/ESP_to_GG_wireshark_captures.zip)

Results after forwarding ports 443 and 80 as suggested by https://github.com/aws/amazon-freertos/issues/2327#issuecomment-669735714
Note: static IPs of the ESP32 and perhaps the Docker machine are different from above due to other devices connecting to the WiFi network.
[ESP32_serial_out_443_80_fail.txt](https://github.com/aws/amazon-freertos/files/5038545/ESP32_serial_out_443_80_fail.txt)
[ESP_to_dockerGG_443_80_capture_fail.zip](https://github.com/aws/amazon-freertos/files/5038539/ESP_to_dockerGG_443_80_fail.zip)

The captures and corresponding serial outputs are from the same sessions. Wireshark was ran on the machine on which GG and Docker were also ran.

(partial serial logs)

I (4575) WIFI: SYSTEM_EVENT_STA_CONNECTED
I (4585) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (6485) event: sta ip: 192.168.0.10, mask: 255.255.255.0, gw: 192.168.0.1
I (6485) WIFI: SYSTEM_EVENT_STA_GOT_IP
GAP procedure initiated: stop advertising.
4 616 [iot_thread] [INFO ][DEMO][6160] Successfully initialized the demo. Network type for the demo: 1
5 616 [iot_thread] [INFO ][MQTT][6160] MQTT library successfully initialized.
6 616 [iot_thread] [INFO ][DEMO][6160] Attempting automated selection of Greengrass device

GAP procedure initiated: stop advertising.
E (6955) PKCS11: failed nvs get file size 4354 0
7 1184 [iot_thread] JSON file retrieval completed
8 1184 [iot_thread] About to close socket.
9 1185 [iot_thread] Socket closed.
10 1185 [iot_thread] Stack high watermark for discovery helper task: 5160.
11 2999 [iot_thread] LwIP connect fail -1 113
12 2999 [iot_thread] ERROR! SOCKETS_Connect call failed: ServerAddress=33558956, Port=45858, ReturnCode=-1
13 2999 [iot_thread] About to close socket.
14 2999 [iot_thread] Socket closed.
15 2999 [iot_thread] Stack high watermark for discovery helper task: 4952.
16 2999 [iot_thread] GGD - Can't connect to greengrass Core
I (30335) wifi:state: run -> init (0)
I (30335) wifi:pm stop, total sleep time: 21602740 us / 25761102 us

I (30345) wifi:new:<11,0>, old:<11,0>, ap:<255,255>, sta:<11,0>, prof:1
I (30355) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 8
E (30355) wifi:wifi deinit internal: wifi not stop
17 2999 [iot_thread] [ERROR][DEMO][29990] Auto-connect: Failed to retrieve Greengrass address and certificate.
18 2999 [iot_thread] [INFO ][MQTT][29990] MQTT library cleanup done.
I (30375) wifi:flush txq
I (30375) wifi:stop sw txq
I (30385) wifi:lmac stop hw txq
19 2999 [iot_thread] [INFO ][DEMO][29990] Cleaned up MQTT library.
20 2999 [iot_thread] [INFO ][DEMO][29990] memory_metrics::freertos_heap::before::bytes::194244
I (30395) wifi:Deinit lldesc rx mblock:10
21 2999 [iot_thread] [INFO ][DEMO][29990] memory_metrics::freertos_heap::after::bytes::98168
22 3001 [iot_thread] [INFO ][DEMO][30010] memory_metrics::demo_task_stack::before::bytes::8920
23 3001 [iot_thread] [INFO ][DEMO][30010] memory_metrics::demo_task_stack::after::bytes::4952
24 3001 [iot_thread] [ERROR][DEMO][30010] Error running demo.
25 3011 [iot_thread] [INFO ][INIT][30110] SDK cleanup done.
26 3011 [iot_thread] [INFO ][DEMO][30110] -------DEMO FINISHED-------

**To reproduce**

1. Setup a GGC container image in a Docker container
2. Configure the GG group from the AWS GG as required for containerized GG images.
3. Modify aws_clientcredential.h and aws_clientcredential_keys.h with necessary details and flash the ESP32 with the AFR GG discovery demo
4. Add the ESP32 IoT device as a device to the GG group
5. Configure a subscription in the GG group with the ESP32 Thing as the publisher and the GGC device as the subscriber
6. Start Docker on the target machine. Start Greengrass in a Docker container
7. Deploy the GG group to the containerized Docker image
8. Run the AFR GG discovery demo

**Edits**
Edit 1: Added txt files containing the full serial output of both the successful and unsuccessful GG discovery, and the output of 'docker image inspect [greengrass image]'. 
Uploaded a .zip containing Wireshark captures for successful discovery when running GG on the target machine, and unsuccessful discovery when running GG in Docker on the same target machine.

Edit 2: Tried port forwarding ports 443 and 80 as suggested by https://github.com/aws/amazon-freertos/issues/2327#issuecomment-669735714. It did not fix the problem, serial output and packet capture of this scenario have been uploaded.

**Comment by dan4thewin** [comment]
Hi @OZsGit .  Could you provided a packet capture of each scenario?

**Comment by OZsGit** [comment]
> Hi @OZsGit . Could you provided a packet capture of each scenario?

I'm sorry, how do I capture packets? What packets should I try to capture?

**Comment by yourslab** [comment]
> > Hi @OZsGit . Could you provided a packet capture of each scenario?
> 
> I'm sorry, how do I capture packets? What packets should I try to capture?

You may use Wireshark, tcpdump, or a similar utility.

Also, it would be helpful to show the Dockerfile or Docker Image that you use. Since SOCKETS_Connect is failing, it could be that one of the ports are not forwarded correctly.

**Comment by OZsGit** [comment]
Edited the original post with Wireshark capture data and corresponding ESP32 device serial outputs for both scenarios. I'm not sure how to show the Dockerfile or Docker Image, as I simply followed the [instructions from AWS](https://docs.aws.amazon.com/greengrass/latest/developerguide/run-gg-in-docker-container.html) to pull the GGC Docker container image. I've also added the output of inspecting this image with docker image inspect [repository name].

**Comment by yourslab** [comment]
Thank you very much for the comprehensive report. 

It seems that port 443 of the GGC is not accessible. If you used the following command to run the GGC using Docker:
```bash
docker run --rm --init -it --name aws-iot-greengrass --entrypoint /greengrass-entrypoint.sh -v c:/Users/%USERNAME%/Downloads/certs:/greengrass/certs -v c:/Users/%USERNAME%/Downloads/config:/greengrass/config -p 8883:8883 216483018798.dkr.ecr.us-west-2.amazonaws.com/aws-iot-greengrass:latest
```

You must change it to the following in order to forward ports listed in the AWS IoT Greengrass discovery demo application under Inbound Rules:
```bash
docker run --rm --init -it --name aws-iot-greengrass --entrypoint /greengrass-entrypoint.sh -v c:/Users/%USERNAME%/Downloads/certs:/greengrass/certs -v c:/Users/%USERNAME%/Downloads/config:/greengrass/config -p 8883:8883 -p 443:443 -p 80:80 216483018798.dkr.ecr.us-west-2.amazonaws.com/aws-iot-greengrass:latest
```

Essentially, we need to add `-p 443:443 -p 80:80` so that the ports needed by the discovery demo application are reachable.

Please feel free to reach out if you encounter more issues. Thanks again for your patience.

**Comment by OZsGit** [comment]
Thanks @yourslab, I tried this and it doesn't appear to have worked. It fails in what appears to be the same way as before, at least according to the serial output. I've updated the original post with both serial output and packet capture for this scenario.

**Comment by yourslab** [comment]
I can see from the packet capture that your ESP32 is not able to discover the GGC. It appears that the Docker container is advertising its own IP address rather than the IP address of the host system (Ubuntu 18.04) to AWS IoT. 

Please go to `AWS IoT` -> `Greengrass` -> `Cores` -> [`Name of Core`] -> `Connectivity`. 

Under Connectivity, you should add port 8883 and the IP address of the host system (Ubuntu 18.04) where the Docker container is running. The IP address should be in the form of 192.168.0.?.

**Comment by OZsGit** [comment]
I checked and indeed the core endpoint doesn't show the IP address of the host system. The following two endpoints are shown:
![Capture3](https://user-images.githubusercontent.com/13131269/89700951-1763b480-d976-11ea-9481-a17dbf8ea542.PNG)
Presumably there are two because I deployed the same group to GG on both the host system and in Docker. What should I do to address this?

**Comment by yourslab** [comment]
Please try to add the IP address of the host system in the form of 192.168.0.* and port 8883.

**Comment by OZsGit** [comment]
Adding the core endpoint has enabled the GG discovery demo to discovery the GG core and complete the demo tasks. The steps taken to resolve this were:
1. Start Docker and launch Greengrass in a container using
```shell
docker run --rm --init -it --name aws-iot-greengrass --entrypoint /greengrass-entrypoint.sh -v c:/Users/%USERNAME%/Downloads/certs:/greengrass/certs -v c:/Users/%USERNAME%/Downloads/config:/greengrass/config -p 8883:8883 -p 443:443 -p 80:80 216483018798.dkr.ecr.us-west-2.amazonaws.com/aws-iot-greengrass:latest
```
2. Deploy the Greengrass group to the containerized core from AWS
3. From `AWS IoT` -> `Greengrass` -> `Cores` -> [`Name of Core`] -> `Connectivity` manually add the local IP address of the host system with port 8883. 
4. Launch the FreeRTOS GG discovery demo on the ESP32.

Strangely if I tried to add the additional connection details _before_ deploying the GG group, after the deployment the connection details would be reset and the additional 192.168.0.? IP details would no longer be present. Starting the FreeRTOS demo at this point would again result in failure. This necessitated modifying the connection details after the deployment. Why would this be the case and how can I prevent the connection details from resetting? This may not be the appropriate thread or location for this discussion.

**Comment by yourslab** [comment]
Ahh that is a good point @OZsGit. I will forward that to the Greengrass Core team. I will close this issue since it has been resolved, but if you encounter any blocker again, please feel free to reach out.

Thank you again for being very descriptive about the steps you've taken to resolve this problem!
