### ISSUE TITLE
FreeRTOS can't publish data to IoT Core through Greengrass

### ISSUE THREAD

**Issue by monhack** [aws/amazon-freertos#2366]
**Describe the bug**
I'm trying to have my ESP32 connect to a iot core. The problem is while esp32 connect iot core, connection failed because it can't find endpoint or connect a remote core. 

**System information**

- ESP32 WROOM32D
- Visual Studio Code
- Operating System : Linux
- Version of Amazon FreeRTOS : 202007.00 release
- Project : MQTTGreengrass|Sub pub Demo 

**Expected behavior**
FreeRTOS accepted publish data to iot core

**Screenshots or console output**
$ python .vendors/espressif/esp-idf/tools/idf.py monitor -p /dev/ttyUSB0 -B directory
.........
 --- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:7180
load:0x40078000,len:12652
ho 0 tail 12 room 4
load:0x40080400,len:6708
entry 0x40080778
I (72) boot: Chip Revision: 1
I (72) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) boot: ESP-IDF HEAD-HASH-NOTFOUND 2nd stage bootloader
I (40) boot: compile time 12:43:26
I (40) boot: Enabling RNG early entropy source...
I (46) boot: SPI Speed      : 40MHz
I (50) boot: SPI Mode       : DIO
I (54) boot: SPI Flash Size : 4MB
I (58) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00010000 00006000
I (76) boot:  1 otadata          OTA data         01 00 00016000 00002000
I (84) boot:  2 phy_init         RF data          01 01 00018000 00001000
I (91) boot:  3 ota_0            OTA app          00 10 00020000 00177000
I (99) boot:  4 ota_1            OTA app          00 11 001a0000 00177000
I (106) boot:  5 storage          WiFi data        01 02 00317000 00010000
I (114) boot: End of partition table
I (118) boot: ota rollback check done
I (122) boot_comm: chip revision: 1, min. application chip revision: 0
I (129) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x287e8 (165864) map
I (197) esp_image: segment 1: paddr=0x00048810 vaddr=0x3ffbdb60 size=0x037fc ( 14332) load
I (203) esp_image: segment 2: paddr=0x0004c014 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/monhack/Documents/Magang/FreeRTOS/freertos_kernel/portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vectors.S:1713

I (204) esp_image: segment 3: paddr=0x0004c41c vaddr=0x40080400 size=0x03bf4 ( 15348) load
I (219) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xb3d34 (736564) map
0x400d0018: _flash_cache_start at ??:?

I (480) esp_image: segment 5: paddr=0x00103d54 vaddr=0x40083ff4 size=0x174e0 ( 95456) load
0x40083ff4: phy_unforce_wifi_chan at /home/aiqin/git_tree/chip7.1_phy/chip_7.1/board_code/app_test/pp/phy/phy_chip_v7_ana.c:756

I (535) boot: Loaded app from partition at offset 0x20000
I (535) boot: Disabling RNG early entropy source...
I (536) cpu_start: Pro cpu up.
I (539) cpu_start: Application information:
I (544) cpu_start: Project name:     esp-idf
I (549) cpu_start: App version:      1
I (554) cpu_start: Compile time:     Aug 14 2020 12:42:39
I (560) cpu_start: ELF file SHA256:  2ae223720d7829f4...
I (566) cpu_start: ESP-IDF:          HEAD-HASH-NOTFOUND
I (572) cpu_start: Single core mode
I (576) heap_init: Initializing. RAM available for dynamic allocation:
I (583) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (589) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (595) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (601) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (607) heap_init: At 3FFCC678 len 00013988 (78 KiB): DRAM
I (614) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (620) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (626) heap_init: At 4009B4D4 len 00004B2C (18 KiB): IRAM
I (632) cpu_start: Pro cpu start user code
I (315) cpu_start: Starting scheduler on PRO CPU.
I (337) uart: queue free spaces: 10
0 1 [main] Initializing lwIP TCP stack
I (337) PKCS11: Initializing NVS partition: "storage"
E (357) PKCS11: failed nvs get file size 4354 0
1 4 [main] Write certificate...
2 6 [iot_thread] [INFO ][DEMO][60] ---------STARTING DEMO---------

I (387) BTDM_INIT: BT controller compile version [0fff744]
3 6 [iot_thread] [INFO ][INIT][60] SDK successfully initialized.
I (387) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (497) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=187 adv_itvl_max=375
I (817) wifi:wifi driver task: 3ffd06e4, prio:23, stack:3584, core=0
I (817) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (817) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (837) wifi:wifi firmware version: 1afdae0
I (837) wifi:config NVS flash: enabled
I (837) wifi:config nano formating: disabled
I (837) wifi:Init dynamic tx buffer num: 32
I (837) wifi:Init data frame dynamic rx buffer num: 32
I (847) wifi:Init management frame dynamic rx buffer num: 32
I (857) wifi:Init management short buffer num: 32
I (857) wifi:Init static rx buffer size: 1600
I (857) wifi:Init static rx buffer num: 10
I (867) wifi:Init dynamic rx buffer num: 32
I (877) wifi:mode : sta (30:ae:a4:97:6b:b0)
I (877) WIFI: SYSTEM_EVENT_STA_START
I (1367) wifi:new:<2,1>, old:<1,0>, ap:<255,255>, sta:<2,1>, prof:1
I (2347) wifi:state: init -> auth (b0)
I (2357) wifi:state: auth -> assoc (0)
I (2367) wifi:state: assoc -> run (10)
I (2467) wifi:connected with KharismaAgri, aid = 13, channel 2, 40U, bssid = d8:07:b6:3e:08:b2
I (2467) wifi:security type: 3, phy: bgn, rssi: -59
I (2477) wifi:pm start, type: 1

I (2477) WIFI: SYSTEM_EVENT_STA_CONNECTED
I (2517) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (3557) event: sta ip: 192.168.0.166, mask: 255.255.255.0, gw: 192.168.0.1
I (3557) WIFI: SYSTEM_EVENT_STA_GOT_IP
GAP procedure initiated: stop advertising.
4 324 [iot_thread] [INFO ][DEMO][3240] Successfully initialized the demo. Network type for the demo: 1
5 324 [iot_thread] [INFO ][MQTT][3240] MQTT library successfully initialized.
6 324 [iot_thread] [INFO ][DEMO][3240] Attempting automated selection of Greengrass device

GAP procedure initiated: stop advertising.
E (4087) PKCS11: failed nvs get file size 4354 0
7 990 [iot_thread] JSON file retrieval completed
8 990 [iot_thread] About to close socket.
9 991 [iot_thread] Socket closed.
10 991 [iot_thread] Stack high watermark for discovery helper task: 5256.
E (10427) PKCS11: failed nvs get file size 4354 0
11 1286 [iot_thread] About to close socket.
12 1287 [iot_thread] Socket closed.
13 1287 [iot_thread] Stack high watermark for discovery helper task: 2696.
**14 1287 [iot_thread] [INFO ][DEMO][12870] Greengrass device discovered.
15 1287 [iot_thread] [INFO ][DEMO][12870] Attempting to establish MQTT connection to Greengrass.
E (13237) PKCS11: failed nvs get file size 4354 0
16 1638 [iot_thread] [INFO ][MQTT][16380] Establishing new MQTT connection.
17 1638 [iot_thread] [INFO ][MQTT][16380] Anonymous metrics (SDK language, SDK version) will be provided to AWS IoT. Recompile with AWS_IOT_MQTT_ENABLE_METRICS set to 0 to disable.
18 1638 [iot_thread] [INFO ][MQTT][16380] (MQTT connection 0x3ffb5f84, CONNECT operation 0x3ffb5600) Waiting for operation completion.
19 1640 [iot_thread] [INFO ][MQTT][16400] (MQTT connection 0x3ffb5f84, CONNECT operation 0x3ffb5600) Wait complete with result SUCCESS.
20 1641 [iot_thread] [INFO ][MQTT][16410] New MQTT connection 0x3ffb4a50 established.
21 1641 [iot_thread] [INFO ][MQTT][16410] (MQTT connection 0x3ffb5f84) MQTT PUBLISH operation queued.
22 1792 [iot_thread] [INFO ][MQTT][17920] (MQTT connection 0x3ffb5f84) MQTT PUBLISH operation queued.
23 1942 [iot_thread] [INFO ][MQTT][19420] (MQTT connection 0x3ffb5f84) MQTT PUBLISH operation queued.
24 2092 [iot_thread] [INFO ][DEMO][20920] Disconnecting from broker.
25 2092 [iot_thread] [INFO ][MQTT][20920] (MQTT connection 0x3ffb5f84) Disconnecting connection.
26 2092 [iot_thread] [INFO ][MQTT][20920] (MQTT connection 0x3ffb5f84, DISCONNECT operation 0x3ffb5600) Waiting for operation completion.
27 2093 [iot_thread] [INFO ][MQTT][20930] (MQTT connection 0x3ffb5f84, DISCONNECT operation 0x3ffb5600) Wait complete with result SUCCESS.
28 2093 [iot_thread] [INFO ][MQTT][20930] (MQTT connection 0x3ffb5f84) Connection disconnected.
29 2094 [iot_thread] [INFO ][MQTT][20940] (MQTT connection 0x3ffb5f84) Network connection closed.**
I (21297) wifi:state: run -> init (0)
I (21297) wifi:pm stop, total sleep time: 14222366 us / 18819312 us

I (21297) wifi:new:<2,0>, old:<2,1>, ap:<255,255>, sta:<2,1>, prof:1
I (21307) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 8
E (21307) wifi:wifi deinit internal: wifi not stop
30 2097 [iot_thread] [INFO ][MQTT][20970] (MQTT connection 0x3ffb5f84) Network connection destroyed.
31 2097 [iot_thread] [INFO ][DEMO][20970] Disconnected from the broker.
32 2097 [iot_thread] Heap low watermark: 97800. Stack high watermark: 2696.
I (21337) wifi:flush txq
I (21337) wifi:stop sw txq
I (21347) wifi:lmac stop hw txq
33 2097 [iot_thread] [INFO ][MQTT][20970] MQTT library cleanup done.
34 2097 [iot_thread] [INFO ][DEMO][20970] Cleaned up MQTT library.
I (21357) wifi:Deinit lldesc rx mblock:10
35 2097 [iot_thread] [INFO ][DEMO][20970] memory_metrics::freertos_heap::before::bytes::193252
36 2097 [iot_thread] [INFO ][DEMO][20970] memory_metrics::freertos_heap::after::bytes::97800
37 2097 [iot_thread] [INFO ][DEMO][20970] memory_metrics::demo_task_stack::before::bytes::8776
38 2097 [iot_thread] [INFO ][DEMO][20970] memory_metrics::demo_task_stack::after::bytes::2696
39 2097 [iot_thread] [INFO ][DEMO][20970] Demo completed successfully.
40 2108 [iot_thread] [INFO ][INIT][21080] SDK cleanup done.
41 2108 [iot_thread] [INFO ][DEMO][21080] -------DEMO FINISHED-------

**To reproduce**
i follow step by step in https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html
help me guys

Thank you!

**Comment by yanjos-dev** [comment]
Hello @monhack, it looks like the demo is running correctly based on the log you posted. Were you able to see the expected messages in the AWS IoT MQTT client? You can find instructions on how to do this in the [AWS IoT Greengrass discovery demo application documentation](https://docs.aws.amazon.com/freertos/latest/userguide/gg-demo.html). 

For your reference, here is a log of the code running successfully with the 202007.00 release on the ESP32 board. 

```
rst:0x1 (POWERON_RESET),boot:0x3e (SPI_FAST_FLASH_BOOT)

flash read err, 1000

ets_main.c 371 

ets Jun  8 2016 00:22:57



rst:0x10 (RTCWDT_RTC_RESET),boot:0x3e (SPI_FAST_FLASH_BOOT)

configsip: 0, SPIWP:0xee

clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00

mode:DIO, clock div:2

load:0x3fff0018,len:4

load:0x3fff001c,len:7176

load:0x40078000,len:12652

load:0x40080400,len:6708

entry 0x40080778

[0;32mI (74) boot: Chip Revision: 1[0m

[0;32mI (74) boot_comm: chip revision: 1, min. bootloader chip revision: 0[0m

[0;32mI (40) boot: ESP-IDF HEAD-HASH-NOTFOUND 2nd stage bootloader[0m

[0;32mI (40) boot: compile time 02:33:14[0m

[0;32mI (70) boot: Enabling RNG early entropy source...[0m

[0;32mI (70) boot: SPI Speed      : 40MHz[0m

[0;32mI (70) boot: SPI Mode       : DIO[0m

[0;32mI (72) boot: SPI Flash Size : 4MB[0m

[0;32mI (76) boot: Partition Table:[0m

[0;32mI (80) boot: ## Label            Usage          Type ST Offset   Length[0m

[0;32mI (87) boot:  0 nvs              WiFi data        01 02 00010000 00006000[0m

[0;32mI (95) boot:  1 otadata          OTA data         01 00 00016000 00002000[0m

[0;32mI (102) boot:  2 phy_init         RF data          01 01 00018000 00001000[0m

[0;32mI (110) boot:  3 ota_0            OTA app          00 10 00020000 00177000[0m

[0;32mI (117) boot:  4 ota_1            OTA app          00 11 001a0000 00177000[0m

[0;32mI (125) boot:  5 storage          WiFi data        01 02 00317000 00010000[0m

[0;32mI (133) boot: End of partition table[0m

[0;32mI (137) boot: No factory image, trying OTA 0[0m

[0;32mI (142) boot_comm: chip revision: 1, min. application chip revision: 0[0m

[0;32mI (149) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x27b80 (162688) map[0m

[0;32mI (215) esp_image: segment 1: paddr=0x00047ba8 vaddr=0x3ffbdb60 size=0x037dc ( 14300) load[0m

[0;32mI (221) esp_image: segment 2: paddr=0x0004b38c vaddr=0x40080000 size=0x00400 (  1024) load[0m

[0;32mI (222) esp_image: segment 3: paddr=0x0004b794 vaddr=0x40080400 size=0x0487c ( 18556) load[0m

[0;32mI (238) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xb3d50 (736592) map[0m

[0;32mI (498) esp_image: segment 5: paddr=0x00103d70 vaddr=0x40084c7c size=0x16858 ( 92248) load[0m

[0;32mI (552) boot: Loaded app from partition at offset 0x20000[0m

[0;32mI (615) boot: Set actual ota_seq=1 in otadata[0][0m

[0;32mI (615) boot: Disabling RNG early entropy source...[0m

[0;32mI (616) cpu_start: Pro cpu up.[0m

[0;32mI (619) cpu_start: Application information:[0m

[0;32mI (624) cpu_start: Project name:     esp-idf[0m

[0;32mI (629) cpu_start: App version:      1[0m

[0;32mI (633) cpu_start: Compile time:     Jul 19 2020 02:32:58[0m

[0;32mI (639) cpu_start: ELF file SHA256:  xxxxxxxxxxxxxxxxxx...[0m

[0;32mI (645) cpu_start: ESP-IDF:          HEAD-HASH-NOTFOUND[0m

[0;32mI (651) cpu_start: Single core mode[0m

[0;32mI (655) heap_init: Initializing. RAM available for dynamic allocation:[0m

[0;32mI (662) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM[0m

[0;32mI (668) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM[0m

[0;32mI (674) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM[0m

[0;32mI (681) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM[0m

[0;32mI (687) heap_init: At 3FFCC658 len 000139A8 (78 KiB): DRAM[0m

[0;32mI (693) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM[0m

[0;32mI (699) heap_init: At 40078000 len 00008000 (32 KiB): IRAM[0m

[0;32mI (705) heap_init: At 4009B4D4 len 00004B2C (18 KiB): IRAM[0m

[0;32mI (712) cpu_start: Pro cpu start user code[0m

[0;32mI (58) cpu_start: Starting scheduler on PRO CPU.[0m

[0;32mI (66) uart: queue free spaces: 10[0m

0 0 [main] Initializing lwIP TCP stack


[0;32mI (76) PKCS11: Initializing NVS partition: "storage"[0m

1 3 [main] Write certificate...


2 507 [iot_thread] [INFO ][DEMO][5070] ---------STARTING DEMO---------




3 507 [iot_thread] [INFO ][DEMO][5070] UUID: _uuid_xxxxxxxxxxxxxxxxxxxxxxxxx




[0;32mI (5136) BTDM_INIT: BT controller compile version [0fff744][0m

4 507 [iot_thread] [INFO ][INIT][5070] SDK successfully initialized.


[0;32mI (5146) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m

[0;33mW (5156) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration[0m

[0;32mI (5316) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 2[0m

GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=187 adv_itvl_max=375

I (5646) wifi:wifi driver task: 3ffdb200, prio:23, stack:3584, core=0

[0;32mI (5646) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m

[0;32mI (5646) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m

I (5676) wifi:wifi firmware version: 1afdae0

I (5676) wifi:config NVS flash: enabled

I (5676) wifi:config nano formating: disabled

I (5676) wifi:Init dynamic tx buffer num: 32

I (5686) wifi:Init data frame dynamic rx buffer num: 32

I (5686) wifi:Init management frame dynamic rx buffer num: 32

I (5696) wifi:Init management short buffer num: 32

I (5696) wifi:Init static rx buffer size: 1600

I (5706) wifi:Init static rx buffer num: 10

I (5706) wifi:Init dynamic rx buffer num: 32

I (5716) wifi:mode : sta (xx:xx:xx:xx:xx:xx)

[0;32mI (5716) WIFI: SYSTEM_EVENT_STA_START[0m

I (8376) wifi:new:<xx,x>, old:<x,x>, ap:<xxx,xxx>, sta:<xx,x>, prof:1

I (9356) wifi:state: init -> auth (b0)

I (9366) wifi:state: auth -> assoc (0)

I (9376) wifi:state: assoc -> run (10)

I (9396) wifi:connected with xxxxxxxx, aid = 27, channel 11, BW20, bssid = xx:xx:xx:xx:xx:xx

I (9396) wifi:security type: 3, phy: bgn, rssi: -48

I (9396) wifi:pm start, type: 1



[0;32mI (9406) WIFI: SYSTEM_EVENT_STA_CONNECTED[0m

I (9466) wifi:AP's beacon interval = 102400 us, DTIM period = 1

[0;32mI (10166) event: sta ip: xxx.xxx.xx.xxx, mask: xxx.xxx.xxx.x, gw: xxx.xxx.xx.x[0m

[0;32mI (10166) WIFI: SYSTEM_EVENT_STA_GOT_IP[0m

5 1010 [iot_thread] [INFO ][DEMO][10100] Successfully initialized the demo. Network type for the demo: 1


6 1010 [iot_thread] [INFO ][MQTT][10100] MQTT library successfully initialized.


7 1011 [iot_thread] [INFO ][DEMO][10110] Attempting automated selection of Greengrass device





[0;31mE (10346) PKCS11: failed nvs get file size 4354 0[0m

I (15466) wifi:bcn_timout,ap_probe_send_start

8 1548 [iot_thread] JSON file retrieval completed


9 1548 [iot_thread] About to close socket.


10 1548 [iot_thread] Socket closed.


11 1548 [iot_thread] Stack high watermark for discovery helper task: 5208.


[0;31mE (15576) PKCS11: failed nvs get file size 4354 0[0m

12 1846 [iot_thread] About to close socket.


13 1847 [iot_thread] Socket closed.


14 1847 [iot_thread] Stack high watermark for discovery helper task: 2616.


15 1847 [iot_thread] [INFO ][DEMO][18470] Greengrass device discovered.


16 1847 [iot_thread] [INFO ][DEMO][18470] Attempting to establish MQTT connection to Greengrass.


[0;31mE (18636) PKCS11: failed nvs get file size 4354 0[0m

17 2154 [iot_thread] [INFO ][MQTT][21540] Establishing new MQTT connection.


18 2154 [iot_thread] [INFO ][MQTT][21540] Anonymous metrics (SDK language, SDK version) will be provided to AWS IoT. Recompile with AWS_IOT_MQTT_ENABLE_METRICS set to 0 to disable.


19 2154 [iot_thread] [INFO ][MQTT][21540] (MQTT connection 0x3ffe73fc, CONNECT operation 0x3ffe72e8) Waiting for operation completion.


20 2161 [iot_thread] [INFO ][MQTT][21610] (MQTT connection 0x3ffe73fc, CONNECT operation 0x3ffe72e8) Wait complete with result SUCCESS.


21 2161 [iot_thread] [INFO ][MQTT][21610] New MQTT connection 0x3ffb4a50 established.


22 2162 [iot_thread] [INFO ][MQTT][21620] (MQTT connection 0x3ffe73fc) MQTT PUBLISH operation queued.


23 2312 [iot_thread] [INFO ][MQTT][23120] (MQTT connection 0x3ffe73fc) MQTT PUBLISH operation queued.


I (24476) wifi:bcn_timout,ap_probe_send_start

24 2462 [iot_thread] [INFO ][MQTT][24620] (MQTT connection 0x3ffe73fc) MQTT PUBLISH operation queued.


25 2612 [iot_thread] [INFO ][DEMO][26120] Disconnecting from broker.


26 2612 [iot_thread] [INFO ][MQTT][26120] (MQTT connection 0x3ffe73fc) Disconnecting connection.


27 2612 [iot_thread] [INFO ][MQTT][26120] (MQTT connection 0x3ffe73fc, DISCONNECT operation 0x3ffe9798) Waiting for operation completion.


28 2613 [iot_thread] [INFO ][MQTT][26130] (MQTT connection 0x3ffe73fc, DISCONNECT operation 0x3ffe9798) Wait complete with result SUCCESS.


29 2613 [iot_thread] [INFO ][MQTT][26130] (MQTT connection 0x3ffe73fc) Connection disconnected.


30 2615 [iot_thread] [INFO ][MQTT][26150] (MQTT connection 0x3ffe73fc) Network connection closed.


I (26236) wifi:state: run -> init (0)

I (26236) wifi:pm stop, total sleep time: 8222650 us / 16839550 us



I (26236) wifi:new:<xx,x>, old:<xx,x>, ap:<xxx,xxx>, sta:<xx,x>, prof:1

[0;32mI (26246) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 8[0m

E (26246) wifi:wifi deinit internal: wifi not stop

31 2617 [iot_thread] [INFO ][MQTT][26170] (MQTT connection 0x3ffe73fc) Network connection destroyed.


I (26266) wifi:flush txq

I (26266) wifi:stop sw txq

I (26266) wifi:lmac stop hw txq

32 2617 [iot_thread] [INFO ][DEMO][26170] Disconnected from the broker.


I (26276) wifi:Deinit lldesc rx mblock:10

33 2617 [iot_thread] Heap low watermark: 74192. Stack high watermark: 2616.


34 2617 [iot_thread] [INFO ][MQTT][26170] MQTT library cleanup done.


35 2617 [iot_thread] [INFO ][DEMO][26170] Cleaned up MQTT library.


36 2617 [iot_thread] [INFO ][DEMO][26170] memory_metrics::freertos_heap::before::bytes::193944


37 2617 [iot_thread] [INFO ][DEMO][26170] memory_metrics::freertos_heap::after::bytes::74192


38 2617 [iot_thread] [INFO ][DEMO][26170] memory_metrics::demo_task_stack::before::bytes::8920


39 2617 [iot_thread] [INFO ][DEMO][26170] memory_metrics::demo_task_stack::after::bytes::2616


40 2617 [iot_thread] [INFO ][DEMO][26170] Demo completed successfully.


GAP procedure initiated: stop advertising.

GAP procedure initiated: stop advertising.

41 2630 [iot_thread] [INFO ][INIT][26300] SDK cleanup done.


42 2630 [iot_thread] [INFO ][DEMO][26300] -------DEMO FINISHED-------
```

**Comment by monhack** [comment]
i follow instruction in https://docs.aws.amazon.com/freertos/latest/userguide/gg-demo.html number 3
```
Open freertos/vendors/vendor/boards/board/aws_demos/config_files/aws_demo_config.h, comment out #define CONFIG_MQTT_DEMO_ENABLED, and define CONFIG_GREENGRASS_DISCOVERY_DEMO_ENABLED. 
```
thanks @yanjos-dev finally solve
