### ISSUE TITLE
Configure freertos devices to interact with aws greengrass core via local network

### ISSUE THREAD

**Issue by Arion12112** [aws/amazon-freertos#2379]
How to configure freertos devices to interact with aws greengrass core via local network? please help because i cannot find any documentation or tutorial for this

**Comment by aggarg** [comment]
This page documents how to setup and run our Greengrass demo on a FreeRTOS device: https://docs.aws.amazon.com/freertos/latest/userguide/gg-demo.html

Thanks.

**Comment by aggarg** [comment]
I am closing this issue. Please feel free to re-open or create a new issue if you need anything else.

Thanks.
