### ISSUE TITLE
WPA3 Security mode support in Documentation and Device tester IDT userdata_schema.json file

### ISSUE THREAD

**Issue by praveenCY** [aws/amazon-freertos#2399]
**Is your feature request related to a problem? Please describe.**  
Yes. WPA3 security mode in WiFi is added as part of PR : https://github.com/aws/amazon-freertos/pull/2380.
This support needs update in userdata_schema.json file in devicetester package for IDT test runs .
Also documentation needs to updated : https://docs.aws.amazon.com/freertos/latest/userguide/freertos-wifi.html

**Error with WPA3 security mode using IDT**
 The document is not compatible with schema.
see errors :
- clientWifiConfig: Does not match a valid configuration format
- clientWifiConfig.wifiSecurityType: clientWifiConfig.wifiSecurityType must be one of the following: "eWiFiSecurityWPA", "eWiFiSecurityWEP", "eWiFiSecurityWPA2"
- testWifiConfig: Does not match a valid configuration format
- testWifiConfig.wifiSecurityType: testWifiConfig.wifiSecurityType must be one of the following: "eWiFiSecurityWPA", "eWiFiSecurityWEP", "eWiFiSecurityWPA2"

**Describe the solution you would like.**  
Below change in userdata_schema.json 
eWiFiSecurityWPA3 in clientWifiConfig ==> wifiSecurityType
eWiFiSecurityWPA3 in testWifiConfig ==> wifiSecurityType

**Additional context**  
Add any other information (including rationale, requirements, or references) about the feature request here.

Thank you!

**Comment by tgsong** [comment]
Thanks for reporting the issue, IDT team is planning to release this feature together with next FreeRTOS release, which is planned in October.
