### ISSUE TITLE
 [iot_thread] [ERROR][MQTT][14340] Failed to establish new MQTT connection, error TIMEOUT.

### ISSUE THREAD

**Issue by SGOSAI602** [aws/amazon-freertos#2404]
**Describe the bug**
I am trying to run the MQTT demo on ESP32. I followed this tutorial : https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html
Its configuration is done and build files are successfully generated. But when i run this command to flash and run FreeRTOS : " ./vendors/espressif/esp-idf/tools/idf.py flash monitor -p /dev/ttyUSB0" on serial monitor it shows "Starting Demo" and gets error at

****12 4238 [iot_thread] [INFO ][MQTT][42380] Network connection closed on error.
13 4239 [iot_thread] [INFO ][MQTT][42390] (MQTT connection 0x3ffdf948) Network connection destroyed.
I (42437) wifi:state: run -> init (0)
I (42447) wifi:pm stop, total sleep time: 9958099 us / 13014256 us**

**I (42447) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1****
. I cannot figure out what kind of error it could be.
There's is another
**E (33017) PKCS11: failed nvs get file size 4354 0**

**System information**
-  Hardware - ESP32-WROOM-32 D
- Operating System Linux-Ubuntu
- Version of FreeRTOS (run ``git describe --tags`` to find it)
- Project AWS FreeRTOS MQTT demo

**Console Output**
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:7204
load:0x40078000,len:12652
load:0x40080400,len:6708
entry 0x40080778
I (72) boot: Chip Revision: 1
I (72) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (38) boot: ESP-IDF v3.3.2-235-ga3ce2f400 2nd stage bootloader
I (38) boot: compile time 21:28:40
I (39) boot: Enabling RNG early entropy source...
I (44) boot: SPI Speed      : 40MHz
I (48) boot: SPI Mode       : DIO
I (52) boot: SPI Flash Size : 4MB
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00010000 00006000
I (75) boot:  1 otadata          OTA data         01 00 00016000 00002000
I (82) boot:  2 phy_init         RF data          01 01 00018000 00001000
I (90) boot:  3 ota_0            OTA app          00 10 00020000 00177000
I (97) boot:  4 ota_1            OTA app          00 11 001a0000 00177000
I (105) boot:  5 storage          WiFi data        01 02 00317000 00010000
I (112) boot: End of partition table
I (117) boot: No factory image, trying OTA 0
I (121) boot_comm: chip revision: 1, min. application chip revision: 0
I (129) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x2bb88 (179080) map
I (200) esp_image: segment 1: paddr=0x0004bbb0 vaddr=0x3ffbdb60 size=0x03848 ( 14408) load
I (206) esp_image: segment 2: paddr=0x0004f400 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/aumrajshital/aws_esp32/amazon-freertos/freertos_kernel/portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vectors.S:1713

I (208) esp_image: segment 3: paddr=0x0004f808 vaddr=0x40080400 size=0x00808 (  2056) load
I (217) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xb76fc (751356) map
0x400d0018: _flash_cache_start at ??:?

I (489) esp_image: segment 5: paddr=0x0010771c vaddr=0x40080c08 size=0x1a8cc (108748) load
I (550) boot: Loaded app from partition at offset 0x20000
I (585) boot: Set actual ota_seq=1 in otadata[0]
I (585) boot: Disabling RNG early entropy source...
I (585) cpu_start: Pro cpu up.
I (588) cpu_start: Application information:
I (593) cpu_start: Project name:     esp-idf
I (598) cpu_start: App version:      202007.00-124-g60f21a68d
I (604) cpu_start: Compile time:     Aug 22 2020 21:27:36
I (610) cpu_start: ELF file SHA256:  4f4efd404e8a7cea...
I (616) cpu_start: ESP-IDF:          v3.3.2-235-ga3ce2f400
I (623) cpu_start: Single core mode
I (627) heap_init: Initializing. RAM available for dynamic allocation:
I (634) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (640) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (646) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (652) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (658) heap_init: At 3FFCBFD0 len 00014030 (80 KiB): DRAM
I (664) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (671) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (677) heap_init: At 4009B4D4 len 00004B2C (18 KiB): IRAM
I (683) cpu_start: Pro cpu start user code
I (30) cpu_start: Starting scheduler on PRO CPU.
I (37) uart: queue free spaces: 10
0 0 [main] Initializing lwIP TCP stack
I (47) PKCS11: Initializing NVS partition: "storage"
1 3 [main] Write certificate...
2 4 [iot_thread] [INFO ][DEMO][40] ---------STARTING DEMO---------

I (77) BTDM_INIT: BT controller compile version [0fff744]
3 4 [iot_thread] [INFO ][INIT][40] SDK successfully initialized.
I (87) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
W (97) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
I (237) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 2
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=187 adv_itvl_max=375
I (567) wifi:wifi driver task: 3ffda04c, prio:23, stack:3584, core=0
I (567) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (567) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (597) wifi:wifi firmware version: 1afdae0
I (597) wifi:config NVS flash: enabled
I (597) wifi:config nano formating: disabled
I (597) wifi:Init dynamic tx buffer num: 32
I (597) wifi:Init data frame dynamic rx buffer num: 32
I (607) wifi:Init management frame dynamic rx buffer num: 32
I (607) wifi:Init management short buffer num: 32
I (617) wifi:Init static rx buffer size: 1600
I (617) wifi:Init static rx buffer num: 10
I (617) wifi:Init dynamic rx buffer num: 32
I (627) wifi:mode : sta (30:ae:a4:9c:fc:1c)
I (637) WIFI: SYSTEM_EVENT_STA_START
I (3767) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 201
I (7897) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 201
I (13027) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 201
I (20157) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 201
I (28397) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (29377) wifi:state: init -> auth (b0)
I (29387) wifi:state: auth -> assoc (0)
I (29397) wifi:state: assoc -> run (10)
I (29427) wifi:connected with OPPOA7, aid = 1, channel 1, BW20, bssid = 48:95:07:7f:fe:2f
I (29427) wifi:security type: 3, phy: bgn, rssi: -48
I (29427) wifi:pm start, type: 1

I (29437) WIFI: SYSTEM_EVENT_STA_CONNECTED
I (29627) wifi:AP's beacon interval = 204800 us, DTIM period = 2
I (32637) event: sta ip: 192.168.43.62, mask: 255.255.255.0, gw: 192.168.43.1
I (32637) WIFI: SYSTEM_EVENT_STA_GOT_IP
4 3260 [iot_thread] [INFO ][DEMO][32600] Successfully initialized the demo. Network type for the demo: 1
5 3260 [iot_thread] [INFO ][MQTT][32600] MQTT library successfully initialized.
6 3260 [iot_thread] [INFO ][DEMO][32600] MQTT demo client identifier is esp32 (length 5).
E (33017) PKCS11: failed nvs get file size 4354 0
7 3738 [iot_thread] [INFO ][MQTT][37380] Establishing new MQTT connection.
8 3738 [iot_thread] [INFO ][MQTT][37380] Anonymous metrics (SDK language, SDK version) will be provided to AWS IoT. Recompile with AWS_IOT_MQTT_ENABLE_METRICS set to 0 to disable.
9 3738 [iot_thread] [INFO ][MQTT][37380] (MQTT connection 0x3ffdf948, CONNECT operation 0x3ffdfe2c) Waiting for operation completion.
10 4238 [iot_thread] [INFO ][MQTT][42380] (MQTT connection 0x3ffdf948, CONNECT operation 0x3ffdfe2c) Wait complete with result TIMEOUT.
11 4238 [iot_thread] [ERROR][MQTT][42380] Failed to establish new MQTT connection, error TIMEOUT.
12 4238 [iot_thread] [INFO ][MQTT][42380] Network connection closed on error.
13 4239 [iot_thread] [INFO ][MQTT][42390] (MQTT connection 0x3ffdf948) Network connection destroyed.
I (42437) wifi:state: run -> init (0)
I (42447) wifi:pm stop, total sleep time: 9958099 us / 13014256 us

I (42447) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (42457) WIFI: SYSTEM_EVENT_STA_DISCONNECTED: 8
E (42467) wifi:wifi deinit internal: wifi not stop
14 4239 [iot_thread] [ERROR][DEMO][42390] MQTT CONNECT returned error TIMEOUT.
15 4239 [iot_thread] [INFO ][MQTT][42390] MQTT library cleanup done.
16 4239 [iot_thread] [INFO ][DEMO][42390] memory_metrics::freertos_heap::before::bytes::200488
I (42487) wifi:flush txq
I (42487) wifi:stop sw txq
I (42497) wifi:lmac stop hw txq
17 4239 [iot_thread] [INFO ][DEMO][42390] memory_metrics::freertos_heap::after::bytes::76880
I (42507) wifi:Deinit lldesc rx mblock:10
18 4240 [iot_thread] [INFO ][DEMO][42400] memory_metrics::demo_task_stack::before::bytes::5848
19 4240 [iot_thread] [INFO ][DEMO][42400] memory_metrics::demo_task_stack::after::bytes::1896
20 4240 [iot_thread] [ERROR][DEMO][42400] Error running demo.
GAP procedure initiated: stop advertising.
GAP procedure initiated: stop advertising.
21 4251 [iot_thread] [INFO ][INIT][42510] SDK cleanup done.
22 4251 [iot_thread] [INFO ][DEMO][42510] -------DEMO FINISHED-------

Thank you!

**Comment by tgsong** [comment]
Hi, sorry for a late response. It is likely that your AWS IoT thing and certificate are not configured correctly. Could you provide information on how you set up the IoT thing? Did you create a certificate from console? Is it activated and attached to the thing? Are they being correctly configured in the source code?

**Comment by sarenameas** [comment]
Hello @SGOSAI602 ,

We have not header back from you yet. I am going to close issue for now. Please reopen if you are still having issues.

**Comment by LeonardMichalas** [comment]
@tgsong @sarenameas I have got the same issue as well. 

I have set up the configuration as follows:

clientcredentialMQTT_BROKER_ENDPOINT = My custom MQTT Endpoint (AWS IoT > Settings)

clientcredentialIOT_THING_NAME = Thing ARN (AWS IoT > Things > [Device Name] > Thing ARN)

clientcredentialMQTT_BROKER_PORT = 8883

clientcredentialGREENGRASS_DISCOVERY_PORT  = 8443

keyCLIENT_CERTIFICATE_PEM = device certificate, which I downloaded when I created the thing in AWS IoT

keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM = Amazon Root CA 1 (https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html?icmpid=docs_iot_console#server-authentication-certs)

keyCLIENT_PRIVATE_KEY_PEM  = private key, which I downloaded when I created the thing in AWS IoT 

Any support would be highly appreciated.
