### ISSUE TITLE
AWS Greengrass using elliptic curves

### ISSUE THREAD

**Issue by vvelciu** [aws/amazon-freertos#2406]
Hello,

Is there any guide on how to use the Greengrass discovery demo application with EC-based certificates?

Thanks!

**Comment by muneebahmed10** [comment]
HI @vvelciu,

AWS IoT supports several [certificate signing algorithms](https://docs.aws.amazon.com/iot/latest/developerguide/x509-client-certs.html#x509-cert-algorithms) for X.509 certs, including ECDSA. Have you tried [creating your own client certificates](https://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html), and then using them for the [Greengrass Discovery demo](https://docs.aws.amazon.com/freertos/latest/userguide/gg-demo.html)?

**Comment by muneebahmed10** [comment]
Hi @vvelciu,

Did the above response resolve your issue? We will close this issue if we don't hear back from you.

**Comment by vvelciu** [comment]
Hello @muneebahmed10 ,

I managed to run the Greengrass Discovery demo with ECDSA (I generated the keys for the device and the Greengrass core as described [here,](https://aws.amazon.com/it/blogs/iot/elliptic-curve-cryptography-and-forward-secrecy-support-in-aws-iot-3/) but I needed to make some changes in the _iot_tls.c_ file. The default root certificates did not include the ATS3 one, so I manually added it:
![image](https://user-images.githubusercontent.com/11376393/108719869-c473d800-7528-11eb-89d4-f57a6a2a9de5.png)
Is there any proper way of doing this? Greengrass is hardcoded to using default certificates:
![image](https://user-images.githubusercontent.com/11376393/108719991-eec59580-7528-11eb-87b5-6c3c97ad3361.png)

Thanks,
Veronica
