### ISSUE TITLE
CertificateConfigurator.html Location Error

### ISSUE THREAD

**Issue by JacobBeningo** [aws/amazon-freertos#2478]
**Describe the bug**
In the CertificateConfigurator.html tool located under tools, at the bottom just above the copyright, it states "Save the generated header file to the demos/common/include folder of the demo project."

**Expected behavior**
This should actually read:

"Save the generated header file to the demos/include folder of the demo project."

The path folder is incorrect

Thank you!

**Comment by alfred2g** [comment]
Thanks for reporting @JacobBeningo
