### ISSUE TITLE
how to create or add custom source and header file in AWS freeRTOS.

### ISSUE THREAD

**Issue by SGOSAI602** [aws/amazon-freertos#2489]
**Describe the bug**
how to create or add custom source and header file in AWS freeRTOS.

**System information**
Hardware - ESP32-WROOM-32 D
Operating System Linux-Ubuntu
Version of FreeRTOS (run git describe --tags to find it)
Project AWS FreeRTOS shadow demo

Thank you!

**Comment by alfred2g** [comment]
What exactly are you trying to achieve here?
you wanna add source and headers to a demo projects? test project?
amazon-freertos uses cmake as the build system, you will have to add the source files you want to one of the CMakelists.txt

**Comment by yanjos-dev** [comment]
@SGOSAI602 I'm going to close this for now. Please feel free to reopen this issue if you have any further issues or questions.
