### ISSUE TITLE
POSIX time.h not including expected data structures

### ISSUE THREAD

**Issue by osloapps-max** [aws/amazon-freertos#2552]
**Describe the bug**
The AFR POSIX include for "time.h" does not contain the "tm" data structure as expected. The header file does make a reference to https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html which states that it shall declare this structure.

As this is not done, the user code must take extra steps to make sure the compiler version of the time header is pulled in instead of the POSIX equivalent. 

I might be going at this the wrong way in my application but it seems that the header files should at least honor the referenced specification.

**System information**
- Which hardware board or part numbers?
 Texas Instruments CC3220SF
- IDE used
 None
- Operating System [Windows|Linux|MacOS]
Windows
- Version of FreeRTOS (run ``git describe --tags`` to find it)
 202007.00-193-gd217bf4fb
- Project [Custom Application|MQTT|Shadow|Greengrass|OTA|Device Defender|TCP Echo|Sub pub Demo|Simple TCP Server]
aws_tests
- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 

**Expected behavior**
That the user can include the <time.h> in the project with the standard behavior. Currently I have only been able to work around it by including <../include/time.h> to prevent it from selecting the POSIX version.

**Comment by dachalco** [comment]
Hi @osloapps-max 

Thanks for bringing this to our attention. I've queued this to the appropriate internal team and they should provide a response once this issue is addressed.

**Comment by dachalco** [comment]
Hi @osloapps-max 

Recently merged PR #2797 which adds `struct tm` to our `time.h`. Please re-open the issue as needed.
