### ISSUE TITLE
Conflict type for "transaction_cb_t" in two files in espressif submodule

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#2650]
Including i2c.h and spi_master.h header files from the espressif submodule library in a file creates a conflicting error type for "transaction_cb_t" since this was defined in both i2c.h and spi_master.h.

**Comment by shubhamkulkarni97** [comment]
Hi @MrMelon1232, thanks for reporting this issue. We have added the fix in esp-idf submodule. 

https://github.com/aws/amazon-freertos/pull/2660 updates submodule with the fix.

Thanks,
Shubham
