### ISSUE TITLE
Unable to publish data from AWS IoT To ESP32 Using MQTT

### ISSUE THREAD

**Issue by abhi-ratnman** [aws/amazon-freertos#2677]
**Describe the bug**
I am trying to communicate with AWS IoT using ESP32. My application requires two-way communication. Right now I'm able to publish messages from ESP32 to AWS cloud using the _publishAllMessages() in the MQTT Demo of ESP32. But I'm unable to find a way to receive data from the AWS Cloud to ESP32 i.e subscribe to a topic to receive data.

**System information**
- hardware board: ESP32 Wroom32 Development Board
- IDE used: ESP-IDF
- Operating System [Windows]
- Version of FreeRTOS (202007.00-195-g19bcad705)
- Project [MQTT]

**Expected behavior**
The data sent on a specified topic from AWS IoT should be received by the ESP32

Thank you!

**Comment by ravibhagavandas** [comment]
Hi,
The demo subscribes to four topic filters and publishes messages to each of the topics and verifies the publish messages are received back correctly on the topics. This way demo can be tested independently without an external client publishing  to the topic.

But you can modify the demo to subscribe to a topic filter you want using one of the sync/async subscription APIs ([doc](https://docs.aws.amazon.com/freertos/latest/lib-ref/c-sdk/mqtt/mqtt_functions.html)). Messages published to the topic should be received in the callback which is registered along with the topic filter subscription.
