### ISSUE TITLE
Implementation of new core mqtt libraries with OTA 

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#2747]
Hi,

I was just wondering if OTA demo will also be updated with the new methods of connecting to mqtt using core_mqtt and more.

**Comment by lundinc2** [comment]
Hello @MrMelon1232,

We are currently working on OTA in this repository https://github.com/aws/ota-for-aws-iot-embedded-sdk. The new design uses an interface for MQTT that can be defined by the application. 

Thanks,

Carl

**Comment by MrMelon1232** [comment]
Hello @lundinc2,
Thanks for the quick response! Will be looking out the new update.

Thanks,

Julien Phan
