### ISSUE TITLE
Invalid sockets not handled in prvSetupConnection

### ISSUE THREAD

**Issue by caleb-garrett** [aws/amazon-freertos#277]
**Describe the bug**
If SOCKETS_Socket() returns SOCKETS_INVALID_SOCKET prvSetupConnection() will return pdPASS. The MQTT agent will then attempt to connect to a non-existent socket.

**System information**
- STM32
- IAR
- Windows
- v1.4.1
- Custom Application

**Expected behavior**
If SOCKETS_Sockect() returns SOCKETS_INVALID_SOCKET, prvSetupConnection() should return pdFAIL.

**Comment by mradulan** [comment]
Hi @caleb-garrett , you are correct. The MQTT agent should not try to connect if the socket is invalid. We will fix this. Thank yo for pointing this out.

**Comment by mradulan** [comment]
closing this as it is fixed now.
