### ISSUE TITLE
Unable to get Shadow reported response on Rest API AWS IoT

### ISSUE THREAD

**Issue by abhi-ratnman** [aws/amazon-freertos#2779]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-overview.html
https://aws.amazon.com/api-gateway/faqs/

We are developing a Home automation Product using AWS IoT. Our devices use amazon freeRTOS and the appliances are controlled using device shadows over MQTT protocol. Appliances can also be controlled using the physical switches which also uses MQTT protocol. Now we are confused on which protocol (MQTT or HTTPS) to use for appliance control and monitoring its current state in mobile App instantly. 

If we use REST API for updating the shadow, we are not able to get a reported message which confirms us that the action was successfully executed at the device/thing side since we need to figure out a constant pooling mechanism which bombards the server with many requests just to get current state.

PS: Can we use MQTT over WebSockets to implement the way we described above? If yes, please guide us on how to get started with it.

**Comment by dan4thewin** [comment]
Hi, @abhi-ratnman .  The lack of notifications is a documented limitation of the REST API and MQTT over WSS is the recommended solution ( https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-comms-app.html ).  The AWS IoT Core developer guide lists the endpoint for MQTT over WSS as `wss://your-iot-endpoint/mqtt` ( https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html ).

The only SDK I can readily find that does MQTT over WSS is this: https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js
I hope that helps.  Please let us know if you have more questions.
