### ISSUE TITLE
 how to my custom Json file merge with AWS cloud

### ISSUE THREAD

**Issue by SGOSAI602** [aws/amazon-freertos#2786]
Describe the bug
how to my custom Json file merge with AWS cloud and send data on AWS server?

System information
Hardware - ESP32-WROOM-32 D
Operating System Linux-Ubuntu
Version of FreeRTOS (run git describe --tags to find it)
Project AWS FreeRTOS shadow demo

Thank you!

**Comment by aggarg** [comment]
Are you asking if you can send a custom JSON to the AWS Device Shadow service? If so, yes, you can report whatever values you want to report in your shadow document as long as the document is valid. You can read more about Shadow Document structure here: https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html

Thanks.

**Comment by lundinc2** [comment]
Hi @SGOSAI602,

I am closing this issue as it has gone stale. Please re-open this if you have further questions!
