### ISSUE TITLE
STM32WB55

### ISSUE THREAD

**Issue by nicolasgarnet** [aws/amazon-freertos#2793]
Hi,

Are Amazon FreeRTOS over BLE features available on STM32WB55 ?

I saw a mention of a support coming in 2019, but I don't see it in vendor/ST list.

Thank you,

**Comment by sbammi** [comment]
Hi nicolasgarnet,

Thank you for your question and interest in FreeRTOS. We greatly appreciate it.

Full and current set of our partner devices qualified with FreeRTOS can be found in the [device catalog](https://devices.amazonaws.com/search?kw=freertos&page=1&sv=freertos). You can find FreeRTOS qualified devices from ST Micro there as well. STM32WB55 is currently not one of them. Please stay tuned as our partners add more devices there.

best regards,
Sachin

**Comment by nicolasgarnet** [comment]
Thank you for the answer !
