### ISSUE TITLE
IotClock_TimerXXX api may cause troubles in timer task link list

### ISSUE THREAD

**Issue by pakls** [aws/amazon-freertos#2837]
If IotClock_TimerCreate is invoked, followed by IotClock_TimerArm, then IotClock_TimerDestroy.
We will have this timer in timer task linked-list and stopped.

If we call IotClock_TimerCreate again with the same static buffer, we may have the timer linked-list mangled.

**Comment by lundinc2** [comment]
Hi @pakls,

Thank you for this report, I am investigating this issue.

**Comment by lundinc2** [comment]
Hi @pakls,

Can you provide some further details, is this an issue that you ran into? The timer is being removed from the timer linked list as the IotClock_TimerDestroy is processed

**Comment by lundinc2** [comment]
I am closing this as a stale issue. Please re-open with further details on the issue.

Thanks,
Carl
