### ISSUE TITLE
New implementation of OTA with coreMQTT estimate time

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#2852]
Hi,

Is it possible to get an estimate on the release time for the new OTA libraries and implementation with coreMQTT ?

**Comment by pvyawaha** [comment]
OTA Library implementation with generic interfaces to use any MQTT and HTTP Library is available in https://github.com/aws/OTA-for-AWS-IoT-embedded-SDK. An example demonstrating its integration with coreMQTT Library and coreMQTT Agent on FreeRTOS is available https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/ repo.

**Comment by pvyawaha** [comment]
Please let me know if you have more questions on the topic.
