### ISSUE TITLE
Is there a expire date of Ota Certificate inside aws_ota_codesignercertificate ? 

### ISSUE THREAD

**Issue by elieDaan** [aws/amazon-freertos#2924]
Hello, 

I have a question about OTA Certificates for ESP32. The certificate stored inside the device in aws_ota_codesignercertificate.h can expire ? I know that the certificates for signing the code on the AWS Management console can expire when you are doing a OTA update but is it the same for the device ?

**Comment by pvyawaha** [comment]
Hello,

The certificate on the service can no longer be used when expired for signing code. On the device side the OTA PAL does not check on the certificate expiration.

**Comment by elieDaan** [comment]
Thanks for your response.
