### ISSUE TITLE
wrong ESP_LOGI in espressif's wifi port code (iot_wifi.c)

### ISSUE THREAD

**Issue by maa1370** [aws/amazon-freertos#2925]
Hi
in vendors/espressif/boards/ports/wifi/iot_wifi.c, in the event_handler function, this line is wrong:

            case SYSTEM_EVENT_AP_STOP:
                ESP_LOGI(TAG, "SYSTEM_EVENT_AP_START");

and I think it has been wrong in previous versions too.
@shubhamkulkarni97

**Comment by shubhamkulkarni97** [comment]
@maa1370 Thanks for pointing this out. Indeed, it has been wrong in previous versions as well.
Please check PR linked above which fixes this issue.

**Comment by maa1370** [comment]
it is wrong again now!

**Comment by shubhamkulkarni97** [comment]
@maa1370 Sorry for late reply. https://github.com/aws/amazon-freertos/pull/3307 fixes this issue.

**Comment by yanjos-dev** [comment]
Hello @maa1370, it looks like this has been resolved so I'm going to close the issue. Please open this issue again or create a new one if you have any further questions.
