### ISSUE TITLE
How to store OTA certificate without using adding it manually in "aws_ota_codesigner_certificate.h" file

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#2968]
I am currently using NVS to store the OTA certificate. I would like to retrieve it via NVS by using a function. Is there any way to override the variable ```static const char signingcredentialSIGNING_CERTIFICATE_PEM[]``` and assign it to the return value of the function or parse an argument when initializing OTA to have custom certificates ?

Any other approach and suggestions are appreciated as well.

**Comment by yourslab** [comment]
Have you considered provisioning the OTA certificate through PKCS #11? There is a `pkcs11configOTA_SUPPORTED` macro in `core_pkcs11_config.h` that you can use for this.

**Comment by leegeth** [comment]
@MrMelon1232,

Could you try the provisioning that @yourslab mentioned? Are you looking for any further help from us?

**Comment by MrMelon1232** [comment]
Hi @leegeth @yourslab, I have found a workaround for this issue and will therefore close it.
