### ISSUE TITLE
Running the Greengrass Discovery demo with ECDSA

### ISSUE THREAD

**Issue by vvelciu** [aws/amazon-freertos#3019]
Hello,

I managed to run the Greengrass Discovery demo with ECDSA (I generated the keys for the device and the Greengrass core as described [here,](https://aws.amazon.com/it/blogs/iot/elliptic-curve-cryptography-and-forward-secrecy-support-in-aws-iot-3/) but I needed to make some changes in the _iot_tls.c_ file. The default root certificates did not include the ATS3 one, so I manually added it:
![image](https://user-images.githubusercontent.com/11376393/108719869-c473d800-7528-11eb-89d4-f57a6a2a9de5.png)
Is there any proper way of doing this? Greengrass is hardcoded to using default certificates:
![image](https://user-images.githubusercontent.com/11376393/108719991-eec59580-7528-11eb-87b5-6c3c97ad3361.png)

Thanks,
Veronica

_Originally posted by @vvelciu in https://github.com/aws/amazon-freertos/issues/2406#issuecomment-783405838_

**Comment by lundinc2** [comment]
Hi @vvelciu,

This approach is correct. I will consider adding ATS3 to the default chain, and will post back here either with further comments or a PR you can track.

Thanks,

Carl

**Comment by lundinc2** [comment]
Hi @vvelciu I have merged said change. Please re-open this issue if you have further questions.
