### ISSUE TITLE
OTA Demo build issue on master

### ISSUE THREAD

**Issue by ahmedwahdan** [aws/amazon-freertos#3034]
**Describe the bug**
This may be a naïve issue, but I have build issue with master branch.
Unknown type IotNetworkConnectionAfr_t
![image](https://user-images.githubusercontent.com/5406736/110633828-e9677c80-81b1-11eb-9ad8-413c62daace1.png)

I looked for this type al over the repo and this all I found 
![image](https://user-images.githubusercontent.com/5406736/110423862-863ef280-80aa-11eb-8f2e-17d0b5303ef0.png)

and on release branch
![image](https://user-images.githubusercontent.com/5406736/110422403-f8fa9e80-80a7-11eb-885e-dffbe4101f3b.png)

**System information**
- ESP32 Wroom kit
- IDE used : NA
- Operating System : Windows
- Version of FreeRTOS : master latest
- Project OTA Demo

**Expected behavior**
Successful build

Thank you!

**Comment by Yoimer** [comment]
@ahmedwahdan Hi again. As mentioned on the other issue, try using `ESP-IDF 4.2` and `FreeRTOS V202012.00`. I am willing to help on this if needed.

**Comment by ahmedwahdan** [comment]
Thanks again Yoimer. I tried the FreeRTOSV202012.00 with IDF v3.3 and it works fine.
Do I just need to switch IDF submodule to 4.2?

**Comment by Yoimer** [comment]
@ahmedwahdan No need to move to 4.2 as long as your demos work fine.

**Comment by yanjos-dev** [comment]
@ahmedwahdan It looks like this issue has been resolved. I'm going to close this issue, but feel free to open it again if you need any assistance.

**Comment by ahmedwahdan** [comment]
Hello, No it's not.
The type was removes and build fails.

**Comment by Yoimer** [comment]
@ahmedwahdan What's the issue you're facing specifically?

**Comment by ahmedwahdan** [comment]
If you enabled the OTA demo, the build will fail du to missing type which was removed recently.

**Comment by Yoimer** [comment]
I don't follow you. 
1) Did you choose the demo from `aws_demo_config.h`?
2) Are you compiling using the `build` folder created on a previous compilation process?
3) If 2 is yes, remove build compilation folder and start over.

**Comment by Yoimer** [comment]
> Thanks again Yoimer. I tried the FreeRTOSV202012.00 with IDF v3.3 and it works fine.
> Do I just need to switch IDF submodule to 4.2?

You had said  _`I tried the FreeRTOSV202012.00 with IDF v3.3 and it works fine`_ but now you say it fails?
Can you paste your logs or snapshot of what you're seeing?

**Comment by ahmedwahdan** [comment]
This issue about master not release branch.
![Screenshot_2021-03-12-01-30-04-360_com android chrome](https://user-images.githubusercontent.com/5406736/110869264-c1236f00-82d2-11eb-9aa6-8928372f4ce8.jpg)
![Screenshot_2021-03-12-01-29-56-785_com android chrome](https://user-images.githubusercontent.com/5406736/110869272-c41e5f80-82d2-11eb-87b3-217d0413cc25.jpg)

**Comment by yanjos-dev** [comment]
Hi @ahmedwahdan, I was able to confirm this issue. Thank you for bringing this to our attention. In the meantime, I recommend basing your project off of one of the tagged releases.

**Comment by yanjos-dev** [comment]
@ahmedwahdan I have created a PR to fix this build issue. https://github.com/aws/amazon-freertos/pull/3050

I'll close this issue after this has been merged.

**Comment by yanjos-dev** [comment]
This fix has been merged, so I'm closing this issue.
