### ISSUE TITLE
How to add esp32-wifi-manager in aws_greengrass_discovery_demo.c program?

### ISSUE THREAD

**Issue by monhack** [aws/amazon-freertos#3036]
Hi @everyone,

I want to ask, how do I add a wifi manager function to the aws_greengrass_discovery_demo.c program? i got no documentation about it. The problem is that I have to manually connect freertos with the configuration in the aws_clientcredential.h program, this method will not be effective. So, I want to make wifi-manager like this for my project
![image](https://user-images.githubusercontent.com/37388043/111114095-59e91180-8595-11eb-914f-4010efd79260.png)

**Comment by Yoimer** [comment]
@monhack Hi. I am trying to the same with OTA and coreMQTT demos. Have you found anything? By the way. Have you been able to bring sensors (like DHT, MQ2, BMP180 just to name a few) to your greengrass demo? Feel free to reply. Thanks a lot

**Comment by yanjos-dev** [comment]
Hello @monhack, what version of the repository are you using?

**Comment by monhack** [comment]
@Yoimer I just focused in greengrass and freertos development for my IoT Project. I able to bring sensors in pro mini, not esp32 (freertos). So I send data sensors to freertos using UART, freertos publish data to greengrass using shadow

**Comment by monhack** [comment]
@yanjos-dev i'm using freertos version 202007.00

**Comment by Yoimer** [comment]
@monhack Hello. Thanks for replying and sharing your experience. By the way did you get any answer about integrating the greengrass demo with the wifi_provisionin?. Thanks again!.

**Comment by yanjos-dev** [comment]
@monhack, can you clarify what you are referring to when you say Wi-Fi manager? If this is a module that is specific to Espressif, then I would recommend raising this question on the Espressif section of the FreeRTOS forums ([link](https://forums.freertos.org/c/partners-sponsors/espressif/14)).
