### ISSUE TITLE
Amazon FreeRTOS and ESP32 with Eclipse

### ISSUE THREAD

**Issue by amlac** [aws/amazon-freertos#3037]
I am trying to use Eclipse on Windows to build and flash AWS FreeRTOS on Espressif ESP32 because I need to include other funcionalities, but I am having the following error:

```
Building in: D:\eclipse-workspace\amazon-freertos\build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=D:\esp-idf\esp-idf-v4.2\tools\cmake\toolchain-esp32.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DIDF_TARGET=esp32 D:\eclipse-workspace\amazon-freertos
-- Submodule update
Skipping submodule '../../../libraries/abstractions/backoff_algorithm/'
Skipping submodule '../../../../libraries/abstractions/pkcs11/corePKCS11/'
Skipping submodule '../../../libraries/abstractions/pkcs11/corePKCS11/'
Skipping submodule '../../../libraries/abstractions/pkcs11/corePKCS11/'
Skipping submodule '../../../libraries/abstractions/pkcs11/corePKCS11/'
Skipping submodule '../../../libraries/coreHTTP/'
Skipping submodule '../../../libraries/coreHTTP/'
Skipping submodule '../../../libraries/coreHTTP/'
Skipping submodule '../../../libraries/coreJSON/'
Skipping submodule '../../../libraries/coreJSON/'
Skipping submodule '../../../libraries/coreJSON/'
Skipping submodule '../../../libraries/coreMQTT/'
Skipping submodule '../../../libraries/coreMQTT/'
Skipping submodule '../../../libraries/coreMQTT/'
Skipping submodule '../../../libraries/device_defender_for_aws/'
Skipping submodule '../../../libraries/device_defender_for_aws/'
Skipping submodule '../../../libraries/device_defender_for_aws/'
Skipping submodule '../../../libraries/device_shadow_for_aws/'
Skipping submodule '../../../libraries/device_shadow_for_aws/'
Skipping submodule '../../../libraries/device_shadow_for_aws/'
Skipping submodule '../../libraries/freertos_plus/standard/freertos_plus_tcp/'
Skipping submodule '../../libraries/freertos_plus/standard/freertos_plus_tcp/'
Skipping submodule '../../libraries/freertos_plus/standard/freertos_plus_tcp/'
Skipping submodule '../../../libraries/jobs_for_aws/'
Skipping submodule '../../../libraries/jobs_for_aws/'
Skipping submodule '../../../libraries/jobs_for_aws/'
CMake Error at CMakeLists.txt:53 (message):
  Board is not supported: vendor.board
```

Using ESP-IDF command prompt I can build and flash. If I create a new Espressif IDF project  on Eclipse it is possible to build and flash too.

Is it possible to use Eclipse? Otherwise, which tool is recommended to use?

**Comment by dan4thewin** [comment]
Hi, @amlac .  While I haven't used it myself, I've found that Espressif provides an Eclipse plugin: https://github.com/espressif/idf-eclipse-plugin/blob/master/README.md

Have you tried it?

**Comment by amlac** [comment]
Hi, @dan4thewin. Yes, I am using Eclipse plugin. It works for hello world example in the tutorial but it don't work for AWS FreeRTOS project.
Thank you.

**Comment by yanjos-dev** [comment]
Hi @amlac, I'm unfamiliar with the tools that you are using, but it looks like you are still building with CMake. Building this project requires some specific flags to be set, including the "BOARD" flag. This flag is used to select a supported target platform that you are attempting to build for. In this case it looks like this flag is not being set so you are getting the "Board is not supported: vendor.board" error. I'd recommend setting this flag along with the other required flags that can be found in our [getting started guide for Espressif](https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html).

If you are still having the issue after this, I would recommend bringing this discussion to the [Espressif specific section of the FreeRTOS forums](https://forums.freertos.org/c/partners-sponsors/espressif/14). There may be others that have experience using this specific setup.

**Comment by Yoimer** [comment]
@amlac let's suppose you want to test the `ota` demo.
Force (edit) your CMake configuration on Eclipse. From `amazon-freertos` folder issue:
`cmake -DVENDOR=espressif -DBOARD=esp32_devkitc -DCOMPILER=xtensa-esp32 -GNinja -S . -B demos/ota/build`
`cmake  --build demos/ota/build`

**Comment by shift-madel** [comment]
> @amlac let's suppose you want to test the `ota` demo. Seeing your logs, I can see that you're trying to compile `AFR` using `ESP-IDF tools`. That might fail. Try forcing `ESP-IDF` to use the `amazon-freertos` tools as I mention here [espressif/vscode-esp-idf-extension#355 (comment)](https://github.com/espressif/vscode-esp-idf-extension/issues/355#issue-836988674)
> 
> Edit your CMake configuration on Eclipse. From `amazon-freertos` folder issue: `cmake -DVENDOR=espressif -DBOARD=esp32_devkitc -DCOMPILER=xtensa-esp32 -GNinja -S . -B demos/ota/build` `cmake --build demos/ota/build`

How i can edit the CMake configuration on Eclipse, and i will import the project as ESP-IDF project or something else?
