### ISSUE TITLE
vDevModeKeyProvisioning() with ATECC608A chip

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#3083]
Hi,

I am currently using an esp32 dev_kit C with external atecc608A chip connected. From what I understood, this function either stores the certificate in NVS flash or provisions them to the eccx08 chip. Is this correct and if so what exactly is the process or flow of operations ? The goal is to be able to store certificate and the private key (aws generated credentials for tls) in the chip. Is it possible with using vDevModeKeyProvisioning() function to do all of this and are there any requirements ?

**Comment by lundinc2** [comment]
I have replied on the forums https://forums.freertos.org/t/vdevmodekeyprovisioning-with-atecc608a-chip/12156/2

**Comment by archigup** [comment]
Hi, as the discussion is continuing on the forums, I am closing this issue. Feel free to open a new issue if you have more questions.
