### ISSUE TITLE
Wrong implementation of the test case `AFQP_WIFI_GetHostIP_DomainNameLengthExceeded`

### ISSUE THREAD

**Issue by tu-thai** [aws/amazon-freertos#3088]
Version of FreeRTOS: 202012.00

In the `libraries/abstractions/wifi/test/iot_test_wifi.c`, the test case `AFQP_WIFI_GetHostIP_DomainNameLengthExceeded` doesn't set  `cDomainNameLengthExceeded` into the `WIFI_GetHostIP()` call. Then this test case's behavior becomes the same as the test case `AFQP_WIFI_GetHostIP_InvalidDomainName`.

**Comment by ravibhagavandas** [comment]
Thanks for reporting the issue. We are working on fixing this.

**Comment by ravibhagavandas** [comment]
Hi,
The related fix has been merged. Please open a new issue if you have further questions.
