### ISSUE TITLE
FreeRTOS does not support Wi-Fi  WEP level of security

### ISSUE THREAD

**Issue by bgklika** [aws/amazon-freertos#3108]
**Describe the bug**

Description
Initially ESP32 firmware can’t connect to Wi-Fi routers  configured to WEP at all.

After changes in Amazon FreeRTOS by patch we can able to connect, but connection is not established again after device reboot.

Problem caused by Amazon FreeRTOS (at least 202011.00 and 202012.00) has no support of Wi-Fi connection to routers with WEP level of security.

We are use Wi-Fi credentials provisioning over BLE.  Android application is able to see routers with WEP level of security but after selection in application firmware can't connect to these routers.

**System information**
- Which hardware board or part numbers?
-ESP32_DevKitC_V4

- IDE used
ESP-IDF 3.3
- Operating System [Windows|Linux|MacOS]
Windows 10
- Version of FreeRTOS (run ``git describe --tags`` to find it)
On both 202011.00 and 202012.00

- Project [Custom Application|MQTT|Shadow|Greengrass|OTA|Device Defender|TCP Echo|Sub pub Demo|Simple TCP Server]
Custom project.
- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 
No special code is required just add Wi-Fi credentials provisioning over BLE demo to the project.

**Expected behavior**
We expect firmware can establish connection with router configured with WEP 

**Screenshots or console output**
Not applicable

**To reproduce**

1. Build the amazon freertos with Wi-Fi credentials provisioning over BLE
2. Configure Wi-Fi router to use WEP
2. Using amazon demo application for Android try to add router with WEP to list of connected networks on the device

**Patch file to resolve the problem is here**
https://gist.github.com/bgklika/c860ef86aceeced37f217ad8b1a37038

**Comment by paulbartell** [comment]
@bgklika : WEP is not supported due to widely known attacks against the RC4 stream cipher. You can read more about this on [Wikipedia](https://en.wikipedia.org/wiki/Wired_Equivalent_Privacy).
