### ISSUE TITLE
problem in ota_demo_core_mqtt.c : prvMqttUnSubscribe cmdCompleteCallback

### ISSUE THREAD

**Issue by maa1370** [aws/amazon-freertos#3118]
**Describe the bug**
in ota_v3_integration branch, demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c, function prvMqttUnSubscribe, commandParams.cmdCompleteCallback is currently set to prvMQTTSubscribeCompleteCallback, but i think it should be set to prvMQTTUnsubscribeCompleteCallback which is currently there, but unused.

@divekarshubham i think you are working on this, so i mentioned you

Thanks!

**Comment by paulbartell** [comment]
@maa1370 Seems so. I will open a PR and reference this Issue.

In the future, feel free to open a pull request when you notice any similar issues and we will be happy to review and merge them.
