### ISSUE TITLE
error: expected initializer before '__result_use_check' ,'__alloc_align' when I was use `make all -j4`

### ISSUE THREAD

**Issue by adrian-zulnedi** [aws/amazon-freertos#3209]
Hi, I have something problem again with cmake builder. That Cmake builder can run but when I was run `make all -j4` have an error. I just do it step by step for preparing firmware (esp32) with AWS FreeRTOS. Some body can please help me?

@yourslab  Thank you during this period. I would be very happy if you could teach me again.

```
FreeRTOS_OTA/FreeRTOS/build$ make all -j4

In file included from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/cstdlib:75,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/ext/string_conversions.h:41,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:6400,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/string:52,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/stdexcept:39,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/array:39,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/tuple:39,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/bits/unique_ptr.h:37,
                 from /Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/8.4.0/memory:80,
                 from /Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/components/nvs_flash/src/nvs.hpp:18,
                 from /Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/components/nvs_flash/src/nvs_api.cpp:14:
/Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:155:44: error: expected initializer before '__result_use_check'
 void *reallocarray(void *, size_t, size_t) __result_use_check __alloc_size(2)
                                            ^~~~~~~~~~~~~~~~~~
/Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:340:52: error: expected initializer before '__alloc_align'
 void * aligned_alloc(size_t, size_t) __malloc_like __alloc_align(1)


make: *** [all] Error 2
```

**Comment by adrian-zulnedi** [comment]
I just try remove that [build] on FreeRTOS and another case I make  [build] in FreeRTOS_OTA  folder.

Then I starting to use 
`cmake -DVENDOR=espressif -DBOARD=esp32_wrover_kit -DCOMPILER=xtensa-esp32 -S . -B ../build`

And `make all -j4` again but still have same error.

**Comment by adrian-zulnedi** [comment]
Addition Information Error

Start with clear I have error package like this.(This picture sentence is Japanese. translate in english is mean can`nt open that package name)

Download xtensa-esp32-elf which if I run have error like this two picture.
https://docs.espressif.com/projects/esp-idf/en/v4.2.1/esp32/api-guides/tools/idf-tools.html

<img width="372" alt="スクリーンショット 2021-06-09 22 21 37" src="https://user-images.githubusercontent.com/74901436/121368682-33f5c200-c976-11eb-8bb5-c9dea4dd3979.png">
<img width="372" alt="スクリーンショット 2021-06-09 22 19 54" src="https://user-images.githubusercontent.com/74901436/121368695-3821df80-c976-11eb-93f0-f4e03658ad0f.png">


this one ↓ I download extensa file another one.
https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/linux-setup.html

<img width="328" alt="スクリーンショット 2021-06-09 16 57 35" src="https://user-images.githubusercontent.com/74901436/121368707-3a843980-c976-11eb-8b61-3ea5933dc9a1.png">

**Comment by yourslab** [comment]
The error is occurring because you are using the wrong compiler. Make sure you are using `xtensa-esp32-elf-gcc` because other compilers won't be able to build.

To fix this, I think you are using toolchain for Linux but you should be using MacOS toolchain instead: https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/macos-setup.html

**Comment by adrian-zulnedi** [comment]
@yourslab thank you for reply my question again. I try that link when first I remove the xtensa-esp32-elf in my folder.
But If I was call get_idf I have error in `xtensa-esp32-elf-gcc` folder. 

<img width="1440" alt="スクリーンショット 2021-06-10 6 56 24" src="https://user-images.githubusercontent.com/74901436/121434930-07af6500-c9b9-11eb-962e-eb0b77968d82.png">

**Comment by yourslab** [comment]
Looks like a permission issue with your Mac. You need to update your Preferences so that it can be opened.

**Comment by adrian-zulnedi** [comment]
@yourslab I just trying Preferences for permission data `extensa-esp32-elf` I think is work it but, Something like error or have a few warning.　Did you have idea for fix it? I just trying a few time for initiallize my data name `FreeRTOS_OTA` named build and FreeRTOS/build. I remove that data and I renew download `extensa-esp32-elf` on terminal again.

<img width="1440" alt="スクリーンショット 2021-06-10 10 31 29" src="https://user-images.githubusercontent.com/74901436/121451837-3f2e0980-c9d9-11eb-83e8-204ebb5e68ae.png">

Download omitted


<img width="1440" alt="スクリーンショット 2021-06-10 10 29 54" src="https://user-images.githubusercontent.com/74901436/121450547-ec535280-c9d6-11eb-8d57-4fcf08d0b23f.png">




error or warning contents

```

Traceback (most recent call last):
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 2622, in parseImpl
    if (instring[loc] == self.firstMatchChar and
IndexError: string index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/tools/ldgen/generation.py", line 619, in add_sections_info
    results = parser.parseString(first_line)
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1814, in parseString
    raise exc
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1804, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 3705, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 4067, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 1550, in _parseNoCache
    raise ParseException( instring, len(instring), self.errmsg, self )
pyparsing.ParseException: Expected "In archive" (at char 1), (line:2, col:1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/tools/ldgen/ldgen.py", line 113, in <module>
    main()
  File "/Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/tools/ldgen/ldgen.py", line 88, in main
    sections_infos.add_sections_info(sections_info_file_obj)
  File "/Users/adrian_plugo/FreeRTOS-OTA/FreeRTOS/vendors/espressif/esp-idf/tools/ldgen/generation.py", line 621, in add_sections_info
    raise ParseException("File " + sections_info_file.name + " is not a valid sections info file. " + p.message)
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/pyparsing.py", line 272, in __getattr__
    raise AttributeError(aname)
AttributeError: message
make[2]: *** [esp-idf/esp32/esp32.project.ld] Error 1
make[1]: *** [esp-idf/esp32/CMakeFiles/ldgen_esp32.project.ld_script.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Linking C static library libbootloader_support.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: libafr_3rdparty_mbedtls.a the table of contents is empty (no object file members in the library define global symbols)
[ 91%] Built target idf_component_bootloader_support
[ 79%] Built target afr_3rdparty_mbedtls
Scanning dependencies of target idf_component_bootloader_support_sections_info
[ 92%] Generating idf_component_bootloader_support.sections_info
[ 92%] Built target idf_component_bootloader_support_sections_info
Scanning dependencies of target ldgen_section_infos
[ 92%] Built target ldgen_section_infos
Scanning dependencies of target ldgen
[ 92%] Built target ldgen
Scanning dependencies of target bootloader
[ 94%] Building C object CMakeFiles/bootloader.dir/dummy_main_src.c.obj
[ 96%] Linking C executable bootloader.elf
[ 98%] Built target bootloader
Scanning dependencies of target app
[100%] Generating bootloader.bin
esptool.py v2.8
[100%] Built target app
[ 79%] No install step for 'bootloader'
[ 79%] Completed 'bootloader'
[ 79%] Built target bootloader
make: *** [all] Error 2

```

**Comment by yourslab** [comment]
Hi @adrian-zulnedi. I'm not entirely sure as to why you are facing this problem with the esp-idf. Have you tried downgrading Python to 3.7? Also, try to delete `build` directory then re-run again.

**Comment by adrian-zulnedi** [comment]
@yourslab hi , I try removed inside data that build directory on FreeRTOS_OTA then I re-run again . but It doesn`t work 100%.
I still Returned to the first stage problem again. when I put `make all -ja` on terminal that over 16% have error again.

**Comment by adrian-zulnedi** [comment]
this is version of extensa

```

adriannoMacBook-Air:build adrian_plugo$ xtensa-esp32-elf-gcc --version
xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by adrian-zulnedi** [comment]
I guess which one must download file for Standard Setup of Toolchain for Mac OS? 
I forgeted which can be 100% that I put on terminal `make all -j4`
when you give me this link  it stoped beetwen 16%~20% .
https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/macos-setup.html

**Comment by yourslab** [comment]
That is the right link. Note that you should be installing and using idf provided in `FreeRTOS/vendors/espressif/esp-idf`.

**Comment by adrian-zulnedi** [comment]
Hi, @yourslab  I try another OS (Linux Ubuntu) is work it but still have again like yesterday.
I take a lot of screen shourt , sorry if hard to see this article.

![Screenshot from 2021-06-11 08-14-21](https://user-images.githubusercontent.com/74901436/121608704-778f1f80-ca8d-11eb-8b86-dc415fc387b3.png)
![Screenshot from 2021-06-11 08-14-40](https://user-images.githubusercontent.com/74901436/121608709-78c04c80-ca8d-11eb-87c9-036f90df7da8.png)
![Screenshot from 2021-06-11 08-14-46](https://user-images.githubusercontent.com/74901436/121608711-7958e300-ca8d-11eb-9187-bab0e922b07c.png)
![Screenshot from 2021-06-11 08-14-51](https://user-images.githubusercontent.com/74901436/121608714-79f17980-ca8d-11eb-8e67-22297b751b9d.png)
![Screenshot from 2021-06-11 08-14-55](https://user-images.githubusercontent.com/74901436/121608718-7b22a680-ca8d-11eb-8849-a5fd715950a5.png)
![Screenshot from 2021-06-11 08-14-58](https://user-images.githubusercontent.com/74901436/121608722-7bbb3d00-ca8d-11eb-8554-fc29a49fbb81.png)
![Screenshot from 2021-06-11 08-15-01](https://user-images.githubusercontent.com/74901436/121608724-7c53d380-ca8d-11eb-9eb0-aae3be4a3a62.png)
![Screenshot from 2021-06-11 08-15-03](https://user-images.githubusercontent.com/74901436/121608729-7cec6a00-ca8d-11eb-806c-8dc6a44ef5e3.png)
![Screenshot from 2021-06-11 08-15-05](https://user-images.githubusercontent.com/74901436/121608734-7e1d9700-ca8d-11eb-8c09-1f28d860a4f8.png)
![Screenshot from 2021-06-11 08-15-08](https://user-images.githubusercontent.com/74901436/121608736-7eb62d80-ca8d-11eb-880d-57b0d58f8360.png)
![Screenshot from 2021-06-11 08-15-10](https://user-images.githubusercontent.com/74901436/121608738-7f4ec400-ca8d-11eb-8c64-db61f95e8e6d.png)
![Screenshot from 2021-06-11 08-15-13](https://user-images.githubusercontent.com/74901436/121608744-7fe75a80-ca8d-11eb-876d-17d0f0995b89.png)
![Screenshot from 2021-06-11 08-15-16](https://user-images.githubusercontent.com/74901436/121608748-81188780-ca8d-11eb-9005-f826ea4a8d46.png)
![Screenshot from 2021-06-11 08-15-19](https://user-images.githubusercontent.com/74901436/121608750-81b11e00-ca8d-11eb-8f3c-ee2d66558512.png)
![Screenshot from 2021-06-11 08-15-21](https://user-images.githubusercontent.com/74901436/121608752-8249b480-ca8d-11eb-9399-7cb1a6a2d8f4.png)
![Screenshot from 2021-06-11 08-15-23](https://user-images.githubusercontent.com/74901436/121608756-82e24b00-ca8d-11eb-8b57-dad077079fe0.png)
![Screenshot from 2021-06-11 08-15-24](https://user-images.githubusercontent.com/74901436/121608757-84137800-ca8d-11eb-8c0b-af207f79877d.png)
![Screenshot from 2021-06-11 08-15-28](https://user-images.githubusercontent.com/74901436/121608760-84ac0e80-ca8d-11eb-8230-18c71dd51b58.png)
![Screenshot from 2021-06-11 08-15-30](https://user-images.githubusercontent.com/74901436/121608766-8544a500-ca8d-11eb-9ee6-7796eb0dd51b.png)
![Screenshot from 2021-06-11 08-15-34](https://user-images.githubusercontent.com/74901436/121608767-85dd3b80-ca8d-11eb-98ac-bbcaa19a295f.png)
![Screenshot from 2021-06-11 08-15-36](https://user-images.githubusercontent.com/74901436/121608770-8675d200-ca8d-11eb-8be6-51532f4eb7d3.png)
![Screenshot from 2021-06-11 08-15-37](https://user-images.githubusercontent.com/74901436/121608773-87a6ff00-ca8d-11eb-81fd-b1bc7ac7e102.png)
![Screenshot from 2021-06-11 08-15-39](https://user-images.githubusercontent.com/74901436/121608775-883f9580-ca8d-11eb-9d4b-0074b742faa4.png)
![Screenshot from 2021-06-11 08-15-40](https://user-images.githubusercontent.com/74901436/121608779-88d82c00-ca8d-11eb-988e-1c12ffe229e6.png)
![Screenshot from 2021-06-11 08-15-41](https://user-images.githubusercontent.com/74901436/121608782-8a095900-ca8d-11eb-919f-23f11b8d6149.png)
![Screenshot from 2021-06-11 08-15-44](https://user-images.githubusercontent.com/74901436/121608787-8aa1ef80-ca8d-11eb-8421-94dc9f8cbb35.png)
![Screenshot from 2021-06-11 08-15-45](https://user-images.githubusercontent.com/74901436/121608789-8b3a8600-ca8d-11eb-9121-7356a2548724.png)
![Screenshot from 2021-06-11 08-15-47](https://user-images.githubusercontent.com/74901436/121608792-8bd31c80-ca8d-11eb-917e-b1d219cf22e8.png)
![Screenshot from 2021-06-11 08-15-48](https://user-images.githubusercontent.com/74901436/121608795-8d044980-ca8d-11eb-943c-1e81ecde3263.png)
![Screenshot from 2021-06-11 08-15-50](https://user-images.githubusercontent.com/74901436/121608799-8d9ce000-ca8d-11eb-8939-19c807f86d28.png)

**Comment by adrian-zulnedi** [comment]
Documents

https://docs.espressif.com/projects/esp-idf/en/release-v3.0/get-started/linux-setup.html

```

for 64-bit Linux:

https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz

```

```
mkdir -p ~/esp
cd ~/esp
tar -xzf ~/Downloads/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
```

**Comment by yourslab** [comment]
Actually, on Ubuntu, it built correctly but has a few warnings. You should be able to flash already.

**Comment by adrian-zulnedi-plugo** [comment]
@yourslab thank you I will check again but I have question what is mean about flash? can you show me that command line?

**Comment by adrian-zulnedi** [comment]
@yourslab thank you that right I just try that flash so it maybe can be . but I didn't know that serial port for esp32 in ubuntu when I use in MacBook I installed that serialport UART driver but if I wan`t to use on linux how can I change that serial port?

**Comment by adrian-zulnedi** [comment]
Hi @yourslab I think this RTOS is work it.(But something have an error on my program so maybe later I check again.) 
I am apreciate with your Gentleman correspondence. Next time my project is to renew that device is mean Over The Air (OTA).
I really luck to gladd @yourslab . Thank you very much!

![Screenshot from 2021-06-12 16-18-01](https://user-images.githubusercontent.com/74901436/121768697-7861a780-cb9a-11eb-8b5c-80007a908b6a.png)
![Screenshot from 2021-06-12 16-18-06](https://user-images.githubusercontent.com/74901436/121768699-7992d480-cb9a-11eb-863b-cb1c08b6bbc1.png)
![Screenshot from 2021-06-12 16-18-10](https://user-images.githubusercontent.com/74901436/121768700-7a2b6b00-cb9a-11eb-966c-675009cd31c4.png)
![Screenshot from 2021-06-12 16-18-17](https://user-images.githubusercontent.com/74901436/121768701-7ac40180-cb9a-11eb-80da-55bdbbdc9b7f.png)
![Screenshot from 2021-06-12 16-18-21](https://user-images.githubusercontent.com/74901436/121768703-7ac40180-cb9a-11eb-84a4-29266c75b0b5.png)
![Screenshot from 2021-06-12 16-18-23](https://user-images.githubusercontent.com/74901436/121768704-7b5c9800-cb9a-11eb-860e-7da7c81eeb5b.png)
![Screenshot from 2021-06-12 16-18-24](https://user-images.githubusercontent.com/74901436/121768705-7bf52e80-cb9a-11eb-8419-cf420a4f220b.png)
