### ISSUE TITLE
break while building esp32-at esp-idf

### ISSUE THREAD

**Issue by adrian-zulnedi** [aws/amazon-freertos#3241]
Hi, guys  I have make issue alikely  about why not make in `make all -j4` But is not have corectly what I want to know it.
Because I want to runnning on mac OS (M1) not just only Linux Ubuntu20.04. 

Then I was run `make all -j4` something have problem with xtensa-esp32-elf.
I try in another issue But not working . Step by step to using this lecture↓ in ESPRESSIF I use 3.3V.

@pvyawaha Hi, When I was talk with Mr.youslab , He help me not full about make all -j4. If you know something cloud you teach me about why is cannnot work ? I am very glad can to talk with you.

[Build break while building esp32-at using release/v1.2.0.0 branch #215](https://github.com/espressif/esp-at/issues/215)

```
/Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:155:44: error: expected initializer before '__result_use_check'
 void *reallocarray(void *, size_t, size_t) __result_use_check __alloc_size(2)
                                            ^~~~~~~~~~~~~~~~~~
/Users/adrian_plugo/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/stdlib.h:340:52: error: expected initializer before '__alloc_align'
 void * aligned_alloc(size_t, size_t) __malloc_like __alloc_align(1)
                                                    ^~~~~~~~~~~~~
```

**Comment by adrian-zulnedi-plugo** [comment]
@yourslab Hi I am very glad for your passion to teach me. thank you. I have trying that your comment link.
But still doesn`t work. Maybe I must initialize my operating sytem? I had try command in terminal. cloud you check my terminal? 



<img width="1440" alt="スクリーンショット 2021-06-18 2 40 32" src="https://user-images.githubusercontent.com/84275521/122447648-ecf37680-cfde-11eb-8d48-f4d08e54d75f.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 36" src="https://user-images.githubusercontent.com/84275521/122447677-f250c100-cfde-11eb-8d6c-d032c3565e84.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 40" src="https://user-images.githubusercontent.com/84275521/122447686-f381ee00-cfde-11eb-92e8-7b4c5dc8d31a.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 44" src="https://user-images.githubusercontent.com/84275521/122447689-f41a8480-cfde-11eb-85cd-cfbd3d4a1fd0.png">

**Comment by adrian-zulnedi** [comment]
@yourslab Hi I am very glad for your passion to teach me. thank you. I have trying that your comment link.
But still doesn`t work. Maybe I must initialize my operating sytem? I had try command in terminal. cloud you check my terminal? 



<img width="1440" alt="スクリーンショット 2021-06-18 2 40 32" src="https://user-images.githubusercontent.com/84275521/122447648-ecf37680-cfde-11eb-8d48-f4d08e54d75f.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 36" src="https://user-images.githubusercontent.com/84275521/122447677-f250c100-cfde-11eb-8d6c-d032c3565e84.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 40" src="https://user-images.githubusercontent.com/84275521/122447686-f381ee00-cfde-11eb-92e8-7b4c5dc8d31a.png">
<img width="1440" alt="スクリーンショット 2021-06-18 2 40 44" src="https://user-images.githubusercontent.com/84275521/122447689-f41a8480-cfde-11eb-85cd-cfbd3d4a1fd0.png">

**Comment by yourslab** [comment]
I am introducing @shubhamkulkarni97, engineer from Espressif. Have any other customers encountered this issue when compiling using M1 Mac? The customer was able to compile using Ubuntu but gets an error when following the same steps on M1 Mac.

**Comment by adrian-zulnedi** [comment]
@yourslab Hi, Thanks for your help.
@shubhamkulkarni97 hi, nice to meet you. I need your help for how can I install extensa-esp32-elf on Mac(M1&intel). Intel have same error.

**Comment by adrian-zulnedi** [comment]
@yourslab Hi, Mr.shubnamkulkarni97 not have reply.

**Comment by adrian-zulnedi** [comment]
this esp-idf have many something trouble because when I was `. ./exporth.sh` that have error like this. 

<img width="1440" alt="スクリーンショット 2021-06-21 12 08 32" src="https://user-images.githubusercontent.com/74901436/122701985-67472380-d289-11eb-8c0b-07788e798339.png">

**Comment by adrian-zulnedi** [comment]
ERROR DOCUMENTS

```

Traceback (most recent call last):
  File "/Users/adrian_plugo/esp/esp-idf/tools/idf.py", line 822, in <module>
    main()
  File "/Users/adrian_plugo/esp/esp-idf/tools/idf.py", line 740, in main
    cli(sys.argv[1:], prog_name=PROG, complete_var='_IDF.PY_COMPLETE')
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1057, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1132, in _main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/shell_completion.py", line 45, in shell_complete
    echo(comp.source())
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/shell_completion.py", line 324, in source
    self._check_version()
  File "/Users/adrian_plugo/.espressif/python_env/idf4.4_py3.9_env/lib/python3.9/site-packages/click/shell_completion.py", line 312, in _check_version
    raise RuntimeError(
RuntimeError: Shell completion is not supported for Bash versions older than 4.4.

```

**Comment by shubhamkulkarni97** [comment]
Hi @adrian-zulnedi, sorry for late response.

1. Regarding main issue, it seems you are not using correct toolchain version for building the application. You can see a warning message in the logs you shared [here](https://github.com/aws/amazon-freertos/issues/3241#issuecomment-863436772). It says: `version 8.4.0 is not supported`, you should use `version 5.2.0`.
To fix this issue, it is recommended to run `./install.sh` and `. ./export.sh` commands in esp-idf folder in the repo.

2. Regarding issue mentioned [here](https://github.com/aws/amazon-freertos/issues/3241#issuecomment-864690833), default bash version supported in macOS is completely outdated. To use all features supported by ESP-IDF, you need to update bash to latest version. You can check current bash version by running `bash --version`. For upgrading bash, you can refer this [link](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba).

You should upgrade bash version and then run commands mentioned in first point.

Hope this helps!

Thanks,
Shubham

**Comment by adrian-zulnedi** [comment]
@shubhamkulkarni97 hi, thank for your reply. 
1. when I was download esp-idf is version 5.2.0 but when I have installed is make to 8.4.0 .how can I fix that?
2. I just try that link but doesn`t work.

<img width="1440" alt="スクリーンショット 2021-06-21 13 45 37" src="https://user-images.githubusercontent.com/74901436/122708718-c7dd5d00-d297-11eb-9446-efd8694a6257.png">

**Comment by shubhamkulkarni97** [comment]
@adrian-zulnedi, Could you share which repositories are you using to build this project? Also the branch used.

Are you using both Amazon FreeRTOS and ESP-IDF?

**Comment by adrian-zulnedi** [comment]
@shubhamkulkarni97 sorry cloud you tell me that how to check it ? command line. Because I think I use both . Amazon FreeRTOS and ESP-IDF .

**Comment by shubhamkulkarni97** [comment]
@adrian-zulnedi, If you are using Amazon FreeRTOS, required version of ESP-IDF is included in it. You can check it in `./vendors/espressif/esp-idf` directory. In this case you should not use external ESP-IDF.

Please note that you need to run `./install.sh` and `. ./export.sh` commands in `./vendors/espressif/esp-idf` directory in Amazon FreeRTOS (not in any other directory/repo).

To check version of Amazon FreeRTOS you are using, you can run `git describe --tags` in AFR repo.

Also, the environment setup by above commands will be valid for single terminal. If you use new terminal window, you need to run these commands again.

**Comment by adrian-zulnedi** [comment]
@shubhamkulkarni97 Sorry I know why can running that make all -j4. Because In Mac M1 is not creally good for runnnig.
I must to use Mac (intel) and version is ESP-IDF (v3.3). Just only this. thanks for your help. I will close this issue.
