### ISSUE TITLE
[General] <Can not find demos/include/aws_ota_codesigner_certificate.h.>

### ISSUE THREAD

**Issue by abhibhatia98** [aws/amazon-freertos#3252]
Well  I have successfully compile freeRTOS mqtt demo project, and now I am working on OTA demo. 

And followed [this](https://docs.aws.amazon.com/freertos/latest/userguide/burn-initial-firmware-esp.html) guide. In second point it mention to copy the certificate in to `demos/include/aws_ota_codesigner_certificate.h` , but when I goes to freeRTOS project that I downloaded from [github](https://github.com/aws/amazon-freertos), this file is not there.

Can anyone help me to find if I am missing something ?

Thanks
Abhi

**Comment by Carfer10** [comment]
You first have to run the script tools/aws_config_quick_start/SetupAWS.py, as explained in this [getting started with FreeRTOS guide](https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html). This script will generate that file.

**Comment by abhibhatia98** [comment]
Hi, Thanks for your response @Carfer10 please check below snapshot.

![image](https://user-images.githubusercontent.com/54257727/122658428-cb36f280-d18a-11eb-9531-e130ee321165.png)

It not generate` demos/include/aws_ota_codesigner_certificate.h` .

Regards
Abhi

**Comment by Yoimer** [comment]
@abhibhatia98 Check this out, all about OTA is well explained there https://docs.aws.amazon.com/freertos/latest/userguide/freertos-ota-dev.html

**Comment by abhibhatia98** [comment]
Hi @Yoimer , Thanks for your response.

I am followed the same guide and when reaches to [this](https://docs.aws.amazon.com/freertos/latest/userguide/burn-initial-firmware-esp.html) page at second point 

![image](https://user-images.githubusercontent.com/54257727/122748553-f49a7000-d2a9-11eb-9b4d-ad5b62bb2999.png)

the git project doesn't have this file. That's the issue.

Thanks 
Abhi

**Comment by pvyawaha** [comment]
Hello @abhibhatia98 ,

Are you using the main ? We are working on integrating the latest OTA library in main branch of this repository along with the documentation updates , so the aws_ota_codesigner_certificate.h is removed. You can use previous release  https://github.com/aws/amazon-freertos/releases/tag/202012.00
