### ISSUE TITLE
idf.py : command not found

### ISSUE THREAD

**Issue by aditi230** [aws/amazon-freertos#3261]
**Briefly summarize the issue being raised**
While performing "To build and flash the project" on Ubuntu facing the error as idf.py : command not found
**Describe the desired outcome**
idf.py -DVENDOR=espressif -DBOARD=esp32__devkitc -DCOMPILER=xtensa-esp32 build
This is the command I ruined on FreeRTOS directory on linux
**System information**
- Hardware board: [ esp-32 devkitc ]
- IDE used: [ ... ] performing on terminal
- Operating System: [Linux]
- Code version: (run ``git describe --tags`` to find it) while I ruined this error was - "Not a fir repository"

![WhatsApp Image 2021-06-22 at 13 52 31](https://user-images.githubusercontent.com/56488242/122890392-40f4b700-d361-11eb-898e-ac1d77cc0aa1.jpeg)

**Comment by gshvang** [comment]
Hi @aditi230, Does the FreeRTOS directory contains the FreeRTOS code that you downloaded? It would be helpful is you can share the contents of FreeRTOS directory where you are running this command. Also to run git command you have to change directory to the root of the FreeRTOS code that you downloaded. There should be a folder named amazon-freertos from where you need to run the git commands.

**Comment by aditi230** [comment]
hey! it worked after I clones the git repository .
