### ISSUE TITLE
[General] releases don't include submodule code

### ISSUE THREAD

**Issue by koooge** [aws/amazon-freertos#3330]
**Briefly summarize the issue being raised**

Hi there,
releases do not include submodules' code like freertos_kernel and libraries/. Is this intended?
https://github.com/aws/amazon-freertos/releases/tag/202012.00

**Describe the desired outcome**
I hope releases include FreeRTOS code. It would make amazon-freertos easier to use

**Comment by muneebahmed10** [comment]
Hi @koooge,

I just downloaded the `freertos-aws-reference-integrations.tar.gz` archive and it contained the submodule contents, including the FreeRTOS kernel and libraries. Please make sure that you are downloading the uploaded `freertos-aws-reference-integrations.tar.gz` asset and not the source code archives auto generated by GitHub.

**Comment by koooge** [comment]
Aha, I had downloaded zip. Thanks!
