### ISSUE TITLE
[BUG] changing demo's does not work

### ISSUE THREAD

**Issue by knap1930** [aws/amazon-freertos#3338]
**Describe the bug**
When I change `#define CONFIG_CORE_MQTT_MUTUAL_AUTH_DEMO_ENABLED` to `#define CONFIG_OTA_HTTP_UPDATE_DEMO_ENABLED` in `vendors/vendor/boards/board/aws_demos/config_files/aws_demo_config.h` like mentioned in your docs... absolutely nothing happens! 

**System information**
- Hardware board: ESP32-DevKitC
- IDE used: none
- Operating System: MacOS
- Code version: 202107.00-3-g19c657cf0
- Project/Demo: anything other than mqtt_demo_mutual_auth

**Expected behavior**
The selected demo (in this case OTA HTTP demo runs)

My guess is that it looks like there is a second file where this defined vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h

**Comment by knap1930** [comment]
I can confirm changing the demo in both places
`vendors/vendor/boards/board/aws_demos/config_files/aws_demo_config.h`
AND
`vendors/espressif/boards/esp32/aws_demos/config_files/aws_demo_config.h`
works... I feel like I was eating crazy pills for a while here..

**Comment by knap1930** [comment]
so I guess I see where I went wrong, and maybe this isn't a bug...

![image](https://user-images.githubusercontent.com/6470136/126850311-2394f1ed-2b6d-4af8-9f8f-f370573432eb.png)

I guess the red parts are suppose to be variables, and I needed to replace them with my specific vendor and board... but the fact `vendors/vendor/boards/board/aws_demos/config_files/aws_demo_config.h` exists is maddening.. maybe this is used for a template when creating a new board?

**Comment by mleister97** [comment]
Facing the same issue. Thanks for your input!
