### ISSUE TITLE
[General] Size analysis of the binaries of  esp32 project. 

### ISSUE THREAD

**Issue by Devyami-Apcon** [aws/amazon-freertos#3339]
**Briefly summarize the issue being raised**
I have a ESP32 project in which i have consumed AFR as a subdirectory. 
I can do everything just like normal esp-idf project but i cant review and analyse my binary ram and data distribution as it is using cmake command and not the idf.py command. I guess elf files are not being generated.

what to do?

**Comment by yourslab** [comment]
Tagging @shubhamkulkarni97 who may be able to answer your question better.

Also, have you tried building with `idf.py` instead? If AFR subdirectory is `freertos`, you can call:
```sh
freertos/vendors/espressif/esp-idf/tools/idf.py -DVENDOR=espressif -DBOARD=esp32_devkitc -DCOMPILER=xtensa-esp32 build```

freertos/vendors/espressif/esp-idf/tools/idf.py size
```

**Comment by shubhamkulkarni97** [comment]
Hi @Devyami-Apcon @yourslab, idf.py size command is not supported in amazon-freertos.

Instead you can run this command:
```
./freertos/vendors/espressif/esp-idf/tools/idf_size.py <path-to-map-file>
```

**Comment by Devyami-Apcon** [comment]
@shubhamkulkarni97 

Thanks, this worked. 
Just a doubt though, my bin file and map file have different names. For example my bin file is afr_demo.bin and my map file is aws_demos.map 

Would I still be tracking my customised project or would this be tracking predefined aws demos?

**Comment by shubhamkulkarni97** [comment]
@Devyami-Apcon It should track for customised project.
Thanks for pointing out that the map file is not generated with correct name. I will create a PR to fix the name of generated map file.

**Comment by Devyami-Apcon** [comment]
Thanks @shubhamkulkarni97 @yourslab for your responses. Closing the issue.
