### ISSUE TITLE
Undefined symbol clientcredentialJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM (referred from aws_tls.o).

### ISSUE THREAD

**Issue by varshakiragi** [aws/amazon-freertos#334]
I am new to AWS. Please help me to fix this build error.

Undefined symbol **clientcredentialJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM** (referred from aws_tls.o).

Where will be the definition of above array and what it will contain?

**Comment by aggarg** [comment]
It is declared in ```aws_dev_mode_key_provisioning.c```: https://github.com/aws/amazon-freertos/blob/master/demos/common/devmode_key_provisioning/aws_dev_mode_key_provisioning.c#L66

Compiling this file should fix your issue. Which platfrom are you seeing this issue on?

Thanks.

**Comment by gordonwang0** [comment]
Hi @varshakiragi,

Please let us know if you need any more help with this.  Closing issue.
