### ISSUE TITLE
[Feature Request] Linux simulator user guide.

### ISSUE THREAD

**Issue by overheat** [aws/amazon-freertos#3354]
A FreeRTOS simulator for Linux is very useful. Do we have user guide for linux simulator?

**Comment by awsa2ron** [comment]
+1

**Comment by alfred2g** [comment]
We are glad you found it useful.
The simulator guide is here: 
https://freertos.org/FreeRTOS-simulator-for-Linux.html

If you have more questions please reopen or create a new issue.
