### ISSUE TITLE
esp32c3 chip support

### ISSUE THREAD

**Issue by shun-dgut** [aws/amazon-freertos#3357]
Hello, I want to ask when esp32c3 will be supported. I tried to adapt to esp32c3, but I encountered a problem.

**Comment by RichardBarry** [comment]
We are actively working to consolidate FreeRTOS RISC-V ports into a single upstream port, including support for the ESP32C3.   I hope this will be available sometime in October - although we are working on lots of things so that may slip.  Meanwhile I think Espressif have some support.
