### ISSUE TITLE
[BUG] BLE WiFi Provisioning BSSID

### ISSUE THREAD

**Issue by AndreaPetrelli** [aws/amazon-freertos#3362]
**Describe the bug**

Adding a new network with BLE provisioning fail with error:
Decode add network cbor message, status = 519

**System information**
- Hardware board: ESP32

The function that read the BSSID from message on file iot_ble_wifi_provisioning_serializer.c

```cpp
status = prvGetByteStringValueFromMap( &map, IOT_BLE_WIFI_PROV_BSSID_KEY, pAddNetworkReq->info.network.ucBSSID, &length );
```

has a incorrect length, the correct code should be

```cpp
length = sizeof( pAddNetworkReq->info.network.ucBSSID );
status = prvGetByteStringValueFromMap( &map, IOT_BLE_WIFI_PROV_BSSID_KEY, pAddNetworkReq->info.network.ucBSSID, &length );
```

**Comment by pvyawaha** [comment]
Thank you for reporting this , we will raise a pull request to fix this and share update here.

**Comment by ravibhagavandas** [comment]
Thanks for pointing this out, I have raised a PR to fix the same: https://github.com/aws/amazon-freertos/pull/3363
