### ISSUE TITLE
[General] Build and upload demo project

### ISSUE THREAD

**Issue by eng-Ibrahim-2012** [aws/amazon-freertos#3365]
**Briefly summarize the issue being raised**
When I tried to make these steps on windows I can't also find the folder structure so any one can support how to make these steps using esp-idf

Go to the directory: amazon-freertos/demos/espressif/esp32_devkitc_esp_wrover_kit/make
This directory contains an Amazon FreeRTOS demo project:
$ cd ~/esp/amazon-freertos/demos/espressif/esp32_devkitc_esp_wrover_kit/make
$ make flash monitor

**Describe the desired outcome**
Can't upload the software to ESP32 and the previous steps was done.

**System information**
- Hardware board: [ ESP32 ]
- IDE used: [idf.py]
- Operating System: [ Windows ]
- Code version: (run ``git clone https://github.com/aws/amazon-freertos`` to find it)
 

**References**
https://aws.amazon.com/blogs/apn/connect-microcontroller-based-devices-to-the-cloud-with-amazon-freertos-and-espressif-esp32/

**Comment by pvyawaha** [comment]
Hello @eng-Ibrahim-2012 ,

Can you please check if you had no issue cloning the repository ? You can also download the latest release https://github.com/aws/amazon-freertos/releases/tag/202107.00

**Comment by eng-Ibrahim-2012** [comment]
Thank you.
