### ISSUE TITLE
[General] Request for clarification and more details, thanks.

### ISSUE THREAD

**Issue by zlhk100** [aws/amazon-freertos#3369]
Hi,

We  plan to integrate freeRTOS plus AWS CSDK into our cortex-m MCU project(stm32L562-DK).   Part of our existing project already integrated and worked with AWS IOT CSDK pretty well.

We noted this REPO https://github.com/FreeRTOS/FreeRTOS-LTS, which seems also covering same AWS CSDK libraries(coreHTTP, coreMQTT and corePKCS11 etc).   What are the difference and which one should we integrate?   BTW,  we want to use Cmake building system.

Thanks,
Lei zhou

**Comment by paulbartell** [comment]
@zlhk100 The CSDK repository is targeted mainly at using AWS libraries on a posix/linux platform and has a build system and demos that run on a linux system. It provides an example of a full solution for connecting with AWS IoT services with all of the pieces integrated together. Software in the CSDK repository may not always be a LTS revision (meaning there could be breaking API changes in the future).

The FreeRTOS-LTS repository only links to LTS releases of the FreeRTOS / AWS libraries and does not contain a build system or any platform-specific ports required to use these libraries on a particular platform. The FreeRTOS-LTS repository is mainly targeted at platforms other than posix or for customers that prefer to maintain their own implementations of platform-specific port portions for each library. You can review the [platform/posix](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/platform/posix) directory in the CSDK repository for an idea of what this entails.
