### ISSUE TITLE
[BUG] <BLE advertising name can't be increased to more than 5 characters >

### ISSUE THREAD

**Issue by sumit612** [aws/amazon-freertos#3417]
**System information**
- Hardware board: [ Custom Board ESP32 WROOM]
- Operating System: [ Windows 10 ]
- Code version: 202012.00
- Project/Demo: [ CONFIG_OTA_UPDATE_DEMO_ENABLED with custom functionalities added ]

**Describe the bug**
We were trying to increase BLE advertising name length. We tried the below process to increase the name lenth, but it can't be increased to more the 5 characters.
      1. change IOT_BLE_DEVICE_SHORT_LOCAL_NAME_SIZE  more than 5(e.g 6) in "iot_ble_config_defaults.h"
      2. update IOT_BLE_DEVICE_COMPLETE_LOCAL_NAME according to the name length(e.g "123456")
	  
If we try to increase more than 5 characters the OTA demo stops and it's log screenshot attached below.

![5character_issue](https://user-images.githubusercontent.com/11428929/139211027-54de3bce-de53-4168-8c71-0bfcfeee17c1.PNG)

Is there a way to increase BLE advertising name to more than 5 characters?

**Comment by dachalco** [comment]
Hi @sumit612 

Removed the bug label as it's a valid failure per the [BT/BLE v4.2 spec](https://www.bluetooth.com/specifications/specs/core-specification-4-2/) which our BT/BLE software is based on. For the MQTT BLE demo, and I believe for the BLE GATT DEMO too, our advertisement data looks like this when _shortened local name_ is set to 6:
```
$2 = {
  flags = 6 '\006', 
  uuids16 = 0x0, 
  num_uuids16 = 0 '\000', 
  uuids16_is_complete = 0, 
  uuids32 = 0x0, 
  num_uuids32 = 0 '\000', 
  uuids32_is_complete = 0, 
  uuids128 = 0x3ffb3d70, 
  num_uuids128 = 1 '\001', 
  uuids128_is_complete = 1, 
  name = 0x3ffbdc40 <ble_svc_gap_name> "123456", 
  name_len = 6 '\006', 
  name_is_complete = 0, 
  tx_pwr_lvl = -128 '\200', 
  tx_pwr_lvl_is_present = 1, 
  slave_itvl_range = 0x0, 
  svc_data_uuid16 = 0x0, 
  svc_data_uuid16_len = 0 '\000', 
  public_tgt_addr = 0x0, 
  num_public_tgt_addrs = 0 '\000', 
  appearance = 0, 
  appearance_is_present = 0, 
  adv_itvl = 0, 
  adv_itvl_is_present = 0, 
  svc_data_uuid32 = 0x0, 
  svc_data_uuid32_len = 0 '\000', 
  svc_data_uuid128 = 0x0, 
  svc_data_uuid128_len = 0 '\000', 
  uri = 0x0, 
  uri_len = 0 '\000', 
  mfg_data = 0x0, 
  mfg_data_len = 0 '\000'
}
```

With this advertisement setup, when shortened local name is > 5, the advertisement PDU data exceeds the 31 byte limit.
Breakdown looks like this:
| flags | uuid128 | name | tx power |
| --- | --- | --- | --- |
| 2 + 1 B | 3 + 16 B | 2 + strlen(name) B | 2 + 1 B | 

The BLE spec GAP/GATT details explain where the first terms come from, they're basically data IDs + lengths.
So, the NimBLE stack (default for ESP32) fails appropriately, percolating to the failure you see which _should_ have an indicative log (I'm adding one now). Advertisement PDU size was increased in >= v5.0, which we plan to support in the future.

The _complete local name_ is ***not*** provided in advertisements, rather it's provided when you request it via EIR. Not sure what BT/BLE scanner you are using, but if request the _complete local name_ via EIR, you should get the entire name as expected. I've confirmed this with a BLE scanner app on my phone, which sends EIR for full name and gets `123456` as expected.

**Comment by sumit612** [comment]
@dachalco , apologies for late reply. Got busy with some office tasks. Thank you very much for your elaborated reply. Will try the complete local name then with EIR scanner then.

**Comment by Yoimer** [comment]
@sumit612 . Check this commit.I was able to fix the length of the name for BLE on AWS FreeRTOS GreenGrass. It's the same principle for any of the demos.

Hope this helps you.

https://github.com/Yoimer/freertos_greengrass_202007/commit/268bfc523cd4ccf82f2ef5e0e684b2c4fa84dcfd

**Comment by sumit612** [comment]
@Yoimer thank you very much. Will definitely try it.

**Comment by sumit612** [comment]
@Yoimer, it worked for me. :)

**Comment by Yoimer** [comment]
> @Yoimer, it worked for me. :)

@sumit612. I am glad it worked for you. Hope you can move forward in your project. I am here just in case you need any further help 👍

**Comment by dachalco** [comment]
Glad a suitable solution was found. Please keep in mind that ADV data is still limited to 31 bytes, so the longer the name, the more data you need sacrifice to fit it. Please re-open as needed. Cheers!
