### ISSUE TITLE
ESP32 using second core

### ISSUE THREAD

**Issue by samuelbles07** [aws/amazon-freertos#3423]
Hi, thanks for the great work!

My application use case require to use second core. Based on [this issue](https://github.com/aws/amazon-freertos/issues/3312), it is still on development/integration. My question, is there any estimation when it will be release?

Thanks!

**Comment by tianmc1** [comment]
Hi @samuelbles07,

As a general rule, we don't comment on ETA of future releases or features. Thank you for understanding.
