### ISSUE TITLE
[General] How to figure out wether the device is connected to the broker ?

### ISSUE THREAD

**Issue by Devyami-Apcon** [aws/amazon-freertos#3433]
**Briefly summarize the issue being raised**
I am trying to implement a feature where my app knows that my device is connected to the mqtt broker or not. According to my research MQTT LWT messages is what i need to implement using device shadows.  Under the heading "Detecting a device is connected" in this [https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-comms-app.html#thing-connection](url) 

it is described how to implement it. However, how to trigger the aws broker to send a "disconnected" status when a sudden error occurs, say power failure etc. In brief how does point number 5 in the link provided works? 

Any help would be appreciated. Thanks

**System information**
- Hardware board: [esp32 ]
- IDE used: [ esp-idf ]
- Operating System: [ MacOS ]
- Code version: (run ``git describe --tags`` to find it)

**Comment by aggarg** [comment]
You specify the LWT topic and message during connect - https://github.com/FreeRTOS/coreMQTT/blob/main/source/include/core_mqtt.h#L417

Your app should subscribe to the same LWT topic. When your device disconnects, the AWS IoT will publish the same message that you specified during connect on the LWT topic.

Thanks.

**Comment by Devyami-Apcon** [comment]
Thank you @aggarg for the answer, it cleared out most of the doubts and it is working as expected. 

However, I have a further extended doubt. For LWT message, reserved topics can not be used and thus i have to use a rule to republish the message to my shadow. The rule I am using is universal for all my devices by using certain sql functions. However the current rule is not working as expected because of policy mismatch, what exact policy shall I attach to my current rule ? 

Here is how my rule look like.
<img width="976" alt="Screenshot 2021-11-27 at 2 42 14 PM" src="https://user-images.githubusercontent.com/75112099/143675652-90f3301d-d197-4f82-8b32-b7e2ce679def.png">

Here is how my role's policy look like.
<img width="1031" alt="Screenshot 2021-11-27 at 2 43 35 PM" src="https://user-images.githubusercontent.com/75112099/143675673-8a40ec70-d04e-4df2-8615-4873cd8b0f4e.png">

**Comment by aggarg** [comment]
You cannot use substitution template expressions in your policy document. You need to update your policy to use the topic `$aws/things/*/shadow/name/settings/update`. 

Regarding the use of `*` instead of `+`, the following is from this document: https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html 
```
The MQTT wildcards + and # are treated as literal strings in an AWS IoT Core policy for MQTT clients. To specify wildcard characters in topic names and topic filters in AWS IoT Core policies for MQTT clients, you must use *.
```

Thanks.

**Comment by jasonpcarroll** [comment]
@Devyami-Apcon Has this issue been resolved?

**Comment by Devyami-Apcon** [comment]
@jasonpcarroll @aggarg 

Yes thank you for the support.
