### ISSUE TITLE
Support for ESP32-S3?

### ISSUE THREAD

**Issue by marcusufg** [aws/amazon-freertos#3459]
Version release/v4.4 of Espressif esp-idf (https://github.com/espressif/esp-idf/tree/release/v4.4) already supports ESP32-S3.
![image](https://user-images.githubusercontent.com/26750539/154855166-4afe70de-e0be-432e-91d2-0f5faf22155c.png)
Our new truck tracker system is intended to use it. I can upload very basic espressif's demos to it, but I can't do it for my project. Does AFR support for this new microcontroller in near future? Is there any timeline? Currently only v4.2 is supported on AFR.
![image](https://user-images.githubusercontent.com/26750539/154855252-ef8e011e-8347-4900-9a9a-0b8f0a4ab071.png)

**Comment by n9wxu** [comment]
At present, there is not a schedule for updating the IDF of AFR beyond 4.2.  Your request will help set the priorities of this project.  Thank you.

**Comment by marcusufg** [comment]
Thanks, Joseph. We, from Simemap, believe this will help also a lot of 
other programmers who are migrating to this new ESP32-S3 processor. I'll 
keep looking forward to the updates.

**Comment by thomasklaush** [comment]
Since esp-afr-sdk is now on v4.4, is there a timeframe to integrate it?

**Comment by mahavirj** [comment]
@thomasklaush We are working on integrating ESP-IDF v4.4 support. Please expect the draft PR in next few days. CC @laukik-hase

**Comment by thomasklaush** [comment]
Hi @mahavirj 
any news on that?

**Comment by mahavirj** [comment]
@thomasklaush Apologies for the delay here. We are in the final phase of the testing on ESP32-S3. We shall raise the PR by early next week.
