### ISSUE TITLE
[General] Mbed TLS `v2.16.10` on `main` branch

### ISSUE THREAD

**Issue by laukik-hase** [aws/amazon-freertos#3484]
- The `main` branch uses Mbed TLS `v2.16.10` which is now at end-of-life. 
- The release `202203.00` has the current LTS `v2.28.0` - when will be the `main` branch updated with this change?

**Comment by ravibhagavandas** [comment]
Hello,
We have a pull request #3472  open for this which we are working on merging to main. The pull request also updates the MBedtls Version.

**Comment by laukik-hase** [comment]
Resolved with https://github.com/aws/amazon-freertos/pull/3499
