### ISSUE TITLE
[General] Timing for feature/cellular branch being merged to main|LTS

### ISSUE THREAD

**Issue by jspaith** [aws/amazon-freertos#3493]
**Briefly summarize the issue being raised**
Is there a rough timeline you can share for the branch `feature/cellular` being merged into the main and/or an LTS branch of this repo?

There's interesting functionality in this, but we're concerned taking a dependency on components/interfaces still under development.

Thank you!
John

**Describe the desired outcome**
Just to understand timing.

**System information**
N/A

**References**
N/A

**Code/Steps to reproduce the current status**
N/A

**Additional context**
N/A

**Comment by ravibhagavandas** [comment]
Hello,
As far as I can tell, the branch you are looking at `feature/cellular` is not actively developed. Instead we have the FreeRTOS Cellular Interface as a modular library which can be included in your project directly:
https://github.com/FreeRTOS/FreeRTOS-Cellular-Interface
We have ports for the library and demos for three Cellular Modems. To learn more you can visit the documentation here: https://freertos.org/cellular/index.html
