### ISSUE TITLE
Please add a function FreeRTOS_dnsclear()

### ISSUE THREAD

**Issue by htibosch** [aws/amazon-freertos#352]
**Is your feature request related to a problem? Please describe.**  
When testing the DNS ( and LLMNR or NBNS ) functions, it can be disturbing that the results are stored in a DNS cache. Once stored, a new request for the same URL will be looked-up in the cache.

Also, after a device gets reconnected to a LAN, it may be good to clear results from earlier DNS-requests.

**Describe the solution you would like.**  

Add this bit of code to FreeRTOS_DNS.c :

`#if( ipconfigUSE_DNS_CACHE == 1 )`
`    void FreeRTOS_dnsclear( )`
`    {`
`        memset( xDNSCache, '\0', sizeof ( xDNSCache ) );`
`    }`
`#endif /* ipconfigUSE_DNS_CACHE == 1 */`
`/*-----------------------------------------------------------*/`

Thanks, Hein

**Comment by IP555** [comment]
IFamily and IHead of the new economy management
