### ISSUE TITLE
[BUG] MbedTLS version not reflected within git modules.

### ISSUE THREAD

**Issue by rahul-arasikere** [aws/amazon-freertos#3523]
The gitmodules file tracks 2.16.8 tag of mbedtls where as there are pull requests that reference 2.16.8. Should the git modules file be updated to reflect that change as well?

**Comment by paulbartell** [comment]
@rahul-arasikere : Currently, the mbedtls submodule points to v2.28.0. Shortly, I will update this to v2.28.1 and correct the revision listed in the .gitmodules file.

**Comment by AniruddhaKanhere** [comment]
Hello @rahul-arasikere, the above mentioned PR has been merged and your issue should be fixed now. I'll be closing this issue now. Feel free to re-open this issue, or a new one, if you continue facing any problems.

Thanks.
Aniruddha
