### ISSUE TITLE
[General] Where is esp_hw_support component ?

### ISSUE THREAD

**Issue by taherrera** [aws/amazon-freertos#3526]
Hello,

I am trying to use this function: `esp_err_t esp_read_mac(uint8_t *mac, esp_mac_type_t type)`

For this I have to `#include "esp_mac.h"`

However, **esp_hw_support** folder  does not exist under the components directory, so adding this to CMakeLists.txt of the esp32 has no effect. 

Is there a reason for this ? How can I use esp_read_mac or read the BLEMAC in AFR ?

I am using an ESP32-WROVER.

Thanks

**Comment by jasonpcarroll** [comment]
Hi @taherrera,
Sorry for the later reply. So AFR currently uses a slightly modified version of ESP-IDF v4.2. This is submoduled in at vendors/espressif/esp-idf. So with that in mind, I believe the esp_hw_support component is added in a later version of ESP-IDF and you are using the docs for that version. With that said, here is the reference you should be using https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/api-reference/system/system.html?highlight=mac%20address . Based on this, I believe that you want to add the esp_system component and then include esp_system.h. That should give you the esp_read_mac function.

Let me know if this helps
Best,
Jason Carroll
