### ISSUE TITLE
[BUG] Lacking a check for the return value of mbedtls_ssl_conf_own_cert()

### ISSUE THREAD

**Issue by UVScan** [aws/amazon-freertos#3532]
**Describe the bug**
Lacking a check for the return value of mbedtls_ssl_conf_own_cert().

**Expected behavior**
Should check the return value of mbedtls_ssl_conf_own_cert().
According to the requirement, mbedtls_ssl_conf_own_cert() returns 0 on success or error code on error.
https://github.com/aws/amazon-freertos/blob/49e7fe5d667362ce90bcd03b12633361d6e6f220/libraries/freertos_plus/standard/tls/src/iot_tls.c#L620-L625

**Screenshots or console output**
<img width="902" alt="image" src="https://user-images.githubusercontent.com/112676446/190311481-d441ca03-f96e-4a5b-9845-1a66739b2224.png">

**Comment by alfred2g** [comment]
Hi @UVScan,
 
The function TLS_Connect that is calling that  prvInitializeClientCredential which in turn is calling mbedtls_ssl_conf_own_cert, is checking the return value and checking if the negotiation failed.

So this is not really a bug, will be closing, please reopen if I missed something.
