### ISSUE TITLE
[BUG] ESP32 Port SPI Error with S3

### ISSUE THREAD

**Issue by thomasklaush** [aws/amazon-freertos#3542]
**Describe the bug**
When SPI port is used with ESP32-S3 the Error:
"invalid dma channel, chip only support spi dma channel auto-alloc"
occures.

Reason is that in the port for dma chanel directly lSPIInstance or 1 is used:

iot_spi.c line 155:
ret = spi_bus_initialize(spi_ctx->spi_port_num, &spi_ctx->spi_bus_config, lSPIInstance);
iot_spi.c line 253:
ret = spi_bus_initialize(spi_ctx->spi_port_num, &spi_ctx->spi_bus_config, 1);

I changed it to SPI_DMA_CH_AUTO which works for S3 but maybe not for all.

**System information**
- Hardware board: esp32-s3
- IDE used: 4.4.2
- Operating System: Windows
- Code version: (run ``git describe --tags`` to find it)
- Project/Demo: [ mqtt_demo_mutual_auth | shadow_demo | custom application | etc... ]
- If your project is a custom application, please add the relevant code snippet(s) in the section titled `"Code to reproduce bug"`.

**Comment by dachalco** [comment]
Hi @thomasklaush 

While we offer demos framework for esp32 and esp32-s2, we do not have a specific setup for esp32-s3. Likely there are other configs, besides SPI usage/availability, that need adjusting as well. For example, they build with different [IDF sdkconfig defaults](https://github.com/aws/amazon-freertos/blob/main/vendors/espressif/boards/esp32/aws_demos/sdkconfig.defaults). 

For esp32(-s2) ports, SPI1 is a usable SPI Master instance, however that's [not the case for esp32-s3](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/spi_master.html). I suspect most of the existing esp32 code should translate to s3 without many changes though.

**Comment by n9wxu** [comment]
ESP32-S3 is unsupported in Amazon-Freertos
