### ISSUE TITLE
file system

### ISSUE THREAD

**Issue by EduardShaid** [aws/amazon-freertos#42]
But where is the file system? Virtual input / output system?

**Comment by mradulan** [comment]
@EduardShaid , amazon freertos is one of the products of the[ FreeRTOS Ecosystem](https://www.freertos.org/FreeRTOS-Plus/index.shtml). There is a FreeRTOS+FAT open source file system which can be reference from [here](https://www.freertos.org/FreeRTOS-Plus/index.shtml). Hope this helps.

**Comment by tushartp** [comment]
Hello,
is there plan on making FreeRTOS+FAT production ready. I mean take it out from the labs category and put it in the mainstream on amazon-freertos.
