### ISSUE TITLE
[question] include lwip problem

### ISSUE THREAD

**Issue by chegewara** [aws/amazon-freertos#427]
Sorry for lame question, but how to include or add third_party/lwip to include in esp32 project. 
I have everything working, but i cant this library:
https://github.com/aws/amazon-freertos/tree/master/lib/third_party/lwip

**Comment by pvyawaha** [comment]
Hi,

We have included the information regarding using LWIP in Amazon FreeRTOS Qualification Developer Guide and can be found  amazon-freertos/tests/Amazon FreeRTOS Qualification Developer Guide.pdf.

Thank you.

**Comment by chegewara** [comment]
Thank you.
