### ISSUE TITLE
current shadow service code always verify clientToken, while this is optional in shadow service

### ISSUE THREAD

**Issue by xiongyu0523** [aws/amazon-freertos#46]
If update JSON does not contain a 'clientToken', it will get the timeout because verification of clientToken fails

**Comment by aggarg** [comment]
Yes, as of now you need to put a client token in the shadow update document. As you correctly pointed out, it is optional in the AWS Shadow Service and we will see how we can make this optional in Amazon FreeRTOS.

Thank you for bringing it to our attention.

**Comment by aggarg** [comment]
This is by design as of now that we do not invoke any callback if the response document does not contain a valid clientToken. We will look into how can we inform the user about the receipt of a JSON document without a valid token.

Thank you for pointing it out.

**Comment by yuhui-zheng** [comment]
Appreciate bringing this up, please don't hesitate to reach out again if any other concern. Closing this issue since it has been inactive.
