### ISSUE TITLE
Arm compiler 6 support for Keil MDK 5

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [aws/amazon-freertos#48]
I would like to kindly ask for improvement. Could you add support for ARM Compiler 6 (Clang/LLVM)?
Differences are described here: www.keil.com/appnotes/files/apnt_298.pdf

I have found following potentially conflicting cases in RVDS port:

__forceinline
        amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM_CM3\portmacro.h
        amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM_CM4_MPU\portmacro.h
        amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM_CM4F\portmacro.h
        amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM_CM7\r0p1\portmacro.h
__asm{
       amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM_CM4_MPU\portmacro.h
       amazon-freertos\lib\FreeRTOS\portable\RVDS\ARM7_LPC21xx\portmacro.h

Regards,
David

**Comment by RichardBarry** [comment]
Hi David - thanks for your suggestion.  I have previously had success compiling and and using the FreeRTOS GCC port with LLVM, but that was on an M0 rather than an M4F.  Did you try that?

**Comment by TomasBarakNXP** [comment]
Hi Richard,

we were able to try the GCC port which seems to be compatible with the armclang v6 compiler. However it was necessary to do following modification in several files to align with the compiler version 6:
-#ifdef __CC_ARM
+#if defined(__CC_ARM) || defined(__ARMCC_VERSION)
Following files were needed to update:
demos/nxp/lpc54018iotmodule/common/config_files/FreeRTOSConfig.h
lib/include/freertos_tasks_c_additions.h
lib/third_party/pkcs11/pkcs11.h
lib/third_party/tracealyzer_recorder/streamports/Jlink_RTT/SEGGER_RTT.c
lib/third_party/tracealyzer_recorder/streamports/Jlink_RTT/include/SEGGER_RTT_Conf.h
tests/nxp/lpc54018iotmodule/common/config_files/FreeRTOSConfig.h
Other vendors' source code files are necessary to update too.

Best regards

Tomas Barak

**Comment by dcgaws** [comment]
Is it possible to handle this by adding the __CC_ARM define to your build in this case, rather than taking a code change?

**Comment by DavidJurajdaNXP** [comment]
The macros discussed are predefined according to used compiler variant.
__CC_ARM - ARM Compiler 5
__ARMCC_VERSION - ARM Compiler 6 (Clang/LLVM)

Simple additional definition of __CC_ARM in  ARM Compiler 6 project could cause issues in other software components. Application determine compiler variant from this macros and it should not be manipulated.

**Comment by boofish** [comment]
> Hi David - thanks for your suggestion. I have previously had success compiling and and using the FreeRTOS GCC port with LLVM, but that was on an M0 rather than an M4F. Did you try that?

Hi, Richard, how did you using the FreeRTOS GCC port with LLVM?I have trouble with that. What configuration should I make, would you give some hints?

**Comment by RichardBarry** [comment]
> how did you using the FreeRTOS GCC port with LLVM

Not sure I understand the question.  I just build the source files from the GCC port layer in the LLVM project.

> I have trouble with that

What did you try?
What trouble did you have?

**Comment by boofish** [comment]
> What did you try?

I try to build amazon freertos source code with llvm, generate into llvm IR code. 
In order to analysis its run time behavior through instrumentation.
 
> What trouble did you have?

I don't know how to handle it with llvm compiler to generate llvm IR code. 

I try to using command "cmake -DVENDOER=ti -DBOARD=cc3220_launchpad -DCOMPILER=arm-armclang -S . build"，but it response with error "compiler not found".

 So I need to download armclang compiler and configure it into PATH, but I don't found the compiler provider by directory 'ccstudio/ccs/tools/compiler/'，I check the directory, only found 
![24a5b54283e83e67bf49737192e2564](https://user-images.githubusercontent.com/52410003/70124898-b0885000-16b0-11ea-8d76-c607593ac5b4.png)

So, how can I do to compile the project into llvm ir code?

**Comment by RichardBarry** [comment]
> So I need to download armclang compiler and configure it into PATH, but I don't found the compiler provider by directory 'ccstudio/ccs/tools/compiler/'

Did you download the compiler?  If so, which directory did you install it in?

**Comment by boofish** [comment]
> Did you download the compiler? If so, which directory did you install it in?

I did not download the compiler and don't know where to download it, that's it.

**Comment by boofish** [comment]
> we were able to try the GCC port which seems to be compatible with the armclang v6 compiler. However it was necessary to do following modification in several files to align with the compiler version 6.

Hi Tomas， Where did you download armclang v6 compiler, thanks.
