### ISSUE TITLE
[ble-beta] feature request

### ISSUE THREAD

**Issue by chegewara** [aws/amazon-freertos#487]
I know it is only demo code, but could we make this code more generic and expect BaseType_t instead of `y` or `Y`?
https://github.com/aws/amazon-freertos/blob/feature/ble-beta/demos/common/ble/iot_ble_numericComparison.c#L91

This way we can send confirmation from push button without making it more complicated than necessary. Its not very important, but would be nice to change it. 

Thanks.

**Comment by abhidixi11** [comment]
Hello @chegewara , 
Thanks for the suggestion.  We will consider it for future releases.
