### ISSUE TITLE
Can I add '\0' to the end of income payload

### ISSUE THREAD

**Issue by xiongyu0523** [aws/amazon-freertos#50]
Now MQTT or Shadow API return the pointer to the buffer and the length of the buffer. I understand the buffer is allocated from a static buffer and belongs to xBuffer pointer. '\0' is not in buffer. 

I want to use the buffer as a string and pass to cJSON for further parsing. Is it safe to modify buffer[len] to '\0' to make the payload as a NULL terminated string? 

Thanks.

**Comment by aggarg** [comment]
No, it is not safe as you may end up corrupting the memory if the MQTT message fits exactly in the buffer i.e. there is no free space in the buffer.

Thanks.
