### ISSUE TITLE
Multiple File OTA

### ISSUE THREAD

**Issue by sbertrand-witekio** [aws/amazon-freertos#51]
Hi,

I am using the Window Simulator to understand the AWS OTA system before using on a embedded platform.

I have tested a multiple file OTA with 2 files in the OTA stream. The Windows Simulator reports : 

> [prvUpdateJobStatus] Msg: {"status":"FAILED","statusDetails":{"reason":"0x24000000: 0x00000005"}}

It complains about duplicate JSON entry.

What limitation exist with the current OTA implementation ?

Regards
Stan

**Comment by sarenameas** [comment]
Hello Stan,

Multi-file updates are not yet supported in AWS OTA. If you attempt an OTA update with multiple files in the --files deployment option the job will be rejected. We appreciate your attempt and it is in our planning prioritization.

Thanks,
Sarena
