### ISSUE TITLE
can I use dynamic allocation for MQTT?

### ISSUE THREAD

**Issue by xiongyu0523** [aws/amazon-freertos#53]
Hi, Amazon FreeRTOS expert

The buffer allocation scheme uses a static method. In my use case, I need use Shadow_Get API to get the full document from the cloud and its size is quite large (close to 8KB), and if the block number assigned is too small, I will get the message drop hint. So I have to assign 20 x 8KB = 160KB buffer dedicated to MQTT, it wastes a lot for the most time. 

Can I use replace the GET and FREE pointer by pvPortMalloc() and vPortFree()? So that I can use the memory more efficient. Are there any risks? (alignment requirement or fragmentation?)

BTW, I'm using the heap_4 algorithm.

**Comment by gordonwang0** [comment]
Hi @xiongyu0523,

Yes, you can safely replace the current statically-allocated buffer functions with implementations using pvPortMalloc and vPortFree.  I don't see any risks in doing this.
