### ISSUE TITLE
Adding support for MQTT LWT on connection parameters

### ISSUE THREAD

**Issue by egoltzman** [aws/amazon-freertos#576]
I can't find a way to define the MQTT LWT in Amazon FreeRTOS MQTT Agent
Adding support for MQTT LWT on connection parameters like in AWS IOT SDK will solve this issue:
	bool isWillMsgPresent;			///< Is there a LWT associated with this connection?
	IoT_MQTT_Will_Options will;		///< MQTT LWT parameters.have this option but I can't 
Thank you!

**Comment by huguesBouvier** [comment]
We have branch - currently in beta - that has a new MQTT client which supports LWT.
If you need LWT you can start using this branch before it becomes the new master.
https://github.com/aws/amazon-freertos/blob/3e9383c7319099aebbf9c54aa01c22cb20d43487/modules/libraries/standard/mqtt/include/iot_mqtt.h#L159
