### ISSUE TITLE
Thread cancellation in POSIX

### ISSUE THREAD

**Issue by abelfodil** [aws/amazon-freertos#587]
**Is your feature request related to a problem? Please describe.**  

`pthread_create` wraps `xTaskCreate` to create a thread, but currently there is no way to terminate a thread from the outside, i.e.: nothing wraps `vTaskDelete` to cancel a specific thread (`pthread_exit` only kills a thread from the inside).

**Describe the solution you would like.**  
Implement `int pthread_cancel(pthread_t tid);`

**Additional context**  
 Part of the code can be copied from `pthread_join`.

**Comment by huguesBouvier** [comment]
Hello,

This is an excellent feedback, thank you! After discussing internally I confirm that we intend to implement it. I cannot give you an ETA as of now but I added it as an action item.

Hugues
