### ISSUE TITLE
Add Ethernet Support for ESP32

### ISSUE THREAD

**Issue by velbn** [aws/amazon-freertos#59]
Hi,

I'm working on a product that needs Wifi and Ethernet connectivity.
Is it possible to add Ethernet functionality to the ESP32?

Thanks in advance!
velbn

**Comment by WRansohoff** [comment]
Hello,

Unfortunately we don't currently have any plans to support Ethernet connectivity on the ESP32. Thank you for the feedback though, we always like to hear what features people are interested in seeing.

**Comment by juanpablovega** [comment]
Ditching Amazon FreeRTOS, then.
Thanks for the fast and cold response.

**Comment by WRansohoff** [comment]
My apologies for not adequately responding to your request – that was not my intent. 

We can add Ethernet connectivity to the ESP32 SoC to the FreeRTOS+TCP stack, but we do not have example code for the feature at this time. Also, if you are planning on using both Ethernet and WiFi in your application, please be aware that the FreeRTOS+TCP stack currently only supports a single interface at this time. There is an experimental version that supports multiple networking interfaces though, which you can [learn more about here](https://freertos.org/FreeRTOS-Labs/RTOS_labs_download.html).

**Comment by laszlopataki** [comment]
I raised a [feature request](https://github.com/aws/amazon-freertos/issues/3409).
