### ISSUE TITLE
BLE duplicate include

### ISSUE THREAD

**Issue by WayneRiesterer** [aws/amazon-freertos#591]
**iot_ble_gap.c**

`#include "iot_ble.h"` occurs on lines 35 & 44

**Comment by huguesBouvier** [comment]
Hello,

Thank you for the feedback. This duplicate has already been removed in release 1.5 from in this recent commit: https://github.com/aws/amazon-freertos/commit/5fd5ce7f32d8ca42ef1265089e1839d168315cb1#diff-2ab8644725edc8eaaab948e5f83f9cf8.

Hugues
