### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by bradspry** [aws/amazon-freertos#6]
Just look at those beautiful I2C ports waiting to send their data to AWS IoT:

![pzi2c_a_4](https://user-images.githubusercontent.com/7230377/33578794-b6a03ef6-d915-11e7-8a07-1b14f37aaaf6.png)

![toutpi2_c_2](https://user-images.githubusercontent.com/7230377/33578803-bbd9f83a-d915-11e7-9050-942d47ef003a.png)

[I2C shield source](https://store.ncd.io/?fwp_product_type=accessories&fwp_platform=raspberry-pi)

**Comment by dave2** [comment]
Given the Pi is just Linux on a MPU-class SOC, you can just use Python or any other larger implementation straight on the Pi, eg https://github.com/aws/aws-iot-device-sdk-python

FreeRTOS is for MCU-class systems with limited resources.

**Comment by adjervis** [comment]
Amazon FreeRTOS does not currently support Raspberry Pis. As pointed out by an earlier post, the OS is being targeted to more resource constrained devices than the Raspberry Pi. However 3rd party code is available at : https://github.com/jameswalmsley/RaspberryPi-FreeRTOS.

**Comment by bradspry** [comment]
It surely would be nice to have a lightweight alternative to Linux, optimized out of the box for AWS IoT.

**Comment by drbartling** [comment]
As mentioned by @adjervis, Amazon FreeRTOS is targeted at smaller μCU level devices and does not currently support Raspberry-PI type devices. I will close this issue for now. Let us know if you need any other information.
