### ISSUE TITLE
Linux simulator support?

### ISSUE THREAD

**Issue by karlding** [aws/amazon-freertos#60]
I was curious as to what the plans were regarding the Linux simulator, now that FreeRTOS is under AWS leadership.

The Linux simulator was a community port, and was released under the old FreeRTOS GPLv2 license. However, now that FreeRTOS is MIT licensed, this makes using the Linux port somewhat difficult, as from what I understand, you cannot use GPL-licensed code in a MIT-licensed project without relicensing your code.

Are there plans on officially adding support for a Linux port/simulator? Or is there a way to run the Windows port on Linux?

Thanks!

**Comment by WRansohoff** [comment]
Hi there,

Unfortunately we don't have an officially-supported Linux simulator right now, but thank you for the suggestion and feedback; it helps us prioritize our work internally.

**Comment by elagon** [comment]
that sucks!

**Comment by elagon** [comment]
A Linux simulator is very useful.

**Comment by alfred2g** [comment]
Hi @elagon 
Thanks for your interest in FreeRTOS!

We actually do have a linux simulator!
https://github.com/FreeRTOS/FreeRTOS/pull/37
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/30

Thanks
