### ISSUE TITLE
roadmap / milestones / future visibility

### ISSUE THREAD

**Issue by jrr** [aws/amazon-freertos#603]
I'm excited to see activity on the [release-1.5](https://github.com/aws/amazon-freertos/tree/release-1.5) branch, but I haven't seen anything public about what's planned for it, or any versions beyond that.

Is there something I'm missing? A roadmap or blog post somewhere? I don't need commitments with features and dates, but a vague idea of where AFR is going would be helpful for planning projects around it, and interesting besides.

At minimum it'd be a good practice to update that branch's [changelog.md](https://github.com/aws/amazon-freertos/blob/release-1.5/CHANGELOG.md) as changes land.

**Comment by dnoal** [comment]
Thanks for this input.  We are considering what steps we can take to increase transparency and visibility into what we are doing in the near and medium term.
