### ISSUE TITLE
Syntax error in release-1.5 demo readme file

### ISSUE THREAD

**Issue by mhattiga** [aws/amazon-freertos#604]
**Describe the bug**
This readme file has typos:
https://github.com/aws/amazon-freertos/blob/release-1.5/demos/README.md

In all the cmake commands like this one:
"cmake -DVENDOR=espressif -DBOARD=esp32_wrover_kit -DCOMPILER=xtensa-esp32 -S. -B <you build directory> -DAFR_ENABLE_TESTS=1"
the "-S." should be "-S ."

**Comment by huguesBouvier** [comment]
Fixed :) thank you for the feedback!
