### ISSUE TITLE
Demo readme file has un-useful information.

### ISSUE THREAD

**Issue by mhattiga** [aws/amazon-freertos#605]
**Describe the bug**
The file: https://github.com/aws/amazon-freertos/blob/release-1.5/demos/README.md

Please remove the following from the file because it suggests duplicate ways of doing the same thing. The "make flash" is especially harmful becuase this is the legacy method of building and it sets the expectation that other legacy commands work, but they do not. Specifically "make flash monitor" and "make erase_flash" do not work. 

This creates unnecessary friction for the customer to adopt to the latest version of AmazonFreeRTOS.

**Comment by huguesBouvier** [comment]
Hello,

Make flash is a supported command so it has its place in the readme.
The purpose is to give users a list of what is supported and what can be used.
Hugues
