### ISSUE TITLE
Erase flash for ESP32 goes into infinite loop.

### ISSUE THREAD

**Issue by mhattiga** [aws/amazon-freertos#606]
Bug:
The erase_flash command goes into an infinite loop. 

Here is the command:
./vendors/espressif/esp-idf/tools/idf.py erase_flash monitor  -B build -p /dev/tty.usbserial-141201

Here is the loop it gets stuck in:
rst:0x10 (RTCWDT_RTC_RESET),boot:0x3e (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

**Comment by huguesBouvier** [comment]
Hello,

I was able to reproduce the issue when my board was not flashed with the correct binary. 
erase_flash command works, however, followed by a monitor it just tries to monitor an empty board.
try erase_flash then do a flash then you can do a monitor.
Hugues
