### ISSUE TITLE
Make dependencies are not working.

### ISSUE THREAD

**Issue by mhattiga** [aws/amazon-freertos#617]
**Describe the bug**
I moved from the BLE_OTA demo to the OTAandHelloWorld demo. Changed aws_credentials.h file to a different device name from running  "py SetupAWS.py setup", but the old name was presented in the firmware after doing the build.

I did a make clean, then a make, and it fixed the problem. But this demonstrates the dependencies in the make files are not correct.
console output to explain the issue. If possible, include the call stack. 

**To reproduce**

1. Run "py SetupAWS.py setup" with "device one" name. Do a "flash monitor" of the firmware.
2. Run "py SetupAWS.py setup" with "device two" name. Do a "flash monitor" of the firmware.
3. Watch the output from the device. The name of "device one" shows up in the serial output.
4. Do a "make clean"
5. Do a "flash monitor" of the firmware. Now you see the "device two" name.

The device name is just a leading indicator that the firmware is not built right. The entire debug output did not match. For example, wifi did not start up when going from a BLE only demo to a WiFi demo.   After doing the make clean, then WiFi init was part of the startup output.

**Comment by huguesBouvier** [comment]
Hello,

This was fixed in release-1.5 branch. It won't be carried over to this branch.

Hugues
