### ISSUE TITLE
Mobile App to device pairing over BLE requires a reconnect.

### ISSUE THREAD

**Issue by mhattiga** [aws/amazon-freertos#619]
**Describe the bug**
Mobile App to device pairing over BLE requires a reconnect.

When the mobile app pairs with the device the "toggle slider" turns pink every time. However the "More ..." text  stays grey.  I have to select the "toggle slider" to disconnect BLE then select the "toggle slider" a second time. Now the "More .." turns pink and I can select WiFi Provisionning or MQTT BLE Proxy.  

The color of the "toggle slider" changes between pink and grey when doing this.

Clicking on the "More ..." button only presents the provision WIFI and MQTT Proxy options when the "More ..." is pink.

**Comment by bxpan** [comment]
The "more" menu is only enabled after all initialization is done after ble connection. If it is grey, something might have gone wrong. Please share adb log.
