### ISSUE TITLE
freertos support cmsis rtos2 

### ISSUE THREAD

**Issue by Cherish-Gww** [aws/amazon-freertos#629]
I think freertos need to support cmsis rtos 2. is there have a project support my request?
Thank you!

**Comment by RichardBarry** [comment]
There are a few implementations on the web.  For example, if you create a FreeRTOS project using the STM32CubeMX software then you also get the CMSIS wrappers for FreeRTOS.

**Comment by yuhui-zheng** [comment]
I'm closing this issue, since [this post](https://github.com/ARM-software/CMSIS-FreeRTOS/issues/31) in ARM-software/CMSIS-FreeRTOS repo suggests you were able to get pass the question posted here.
