### ISSUE TITLE
ble-beta: IotBle_SendResponse() on ESP ignores resp.rspErrorStatus

### ISSUE THREAD

**Issue by unixdj** [aws/amazon-freertos#656]
**Describe the bug**
On ESP32, calls to `IotBle_SendResponse()` ignore the `resp.rspErrorStatus` and thus always send a success response.

**System information**
- Which hardware board or part numbers?
Custom ESP32-based board

- IDE used
none

- Operating System [Windows|Linux|MacOS]
Linux

- Version of Amazon FreeRTOS (run ``git describe --tags`` to find it)
v1.4.7-433-g4fa09aac
branch feature/ble-beta

- Project [Custom Application|MQTT|Shadow|Greengrass|OTA|Device Defender|TCP Echo|Sub pub Demo|Simple TCP Server]
Custom Application

- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 

**Expected behavior**
A BLE response packet such as:
```
0x01 0xXX 0x00 0x00 0x01
```
Meaning:
```
0x01       Error
0xXX       BLE (GATT) command that triggered the error
0x00 0x00  Attribute
0x01       Value of resp.eventStatus
```

**Screenshots or console output**

**To reproduce**

In, e.g., a BLE characteristic fallback function, put the code below.  Then, use a BLE client to connect to the board and trigger the error response.

**Code to reproduce the bug**
```cpp
IotBleEventResponse_t resp =
{   
        .eventStatus    = eBTStatusFail,
        .rspErrorStatus = 0x80, 
};      
IotBle_SendResponse( &resp, foo->connId, foo->transId );
```

**Additional context**
Fix:
```
diff --git a/lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gatt_server.c b/lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gatt_server.c
index dc8ca830..e4ba444a 100644
--- a/lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gatt_server.c
+++ b/lib/bluetooth_low_energy/portable/espressif/aws_ble_hal_gatt_server.c
@@ -746,7 +746,7 @@ BTStatus_t prvBTSendResponse( uint16_t usConnId,
     {
     	memcpy( rsp.attr_value.value, pxResponse->xAttrValue.pucValue, pxResponse->xAttrValue.xLen );
 
-		xESPstatus = esp_ble_gatts_send_response( ulGattServerIFhandle, usConnId, ulTransId, xReturnStatus, &rsp );
+		xESPstatus = esp_ble_gatts_send_response( ulGattServerIFhandle, usConnId, ulTransId, xStatus, &rsp );
 
 		if( xESPstatus != ESP_OK )
 		{
```

**Comment by mradulan** [comment]
Hi @unixdj , we are no longer maintaining ble-beta branch. Can you please test your application with the branch [release-1.5](https://github.com/aws/amazon-freertos/tree/release-1.5), and let us know if you are still getting the same response.
