### ISSUE TITLE
thread compile/linking/ Implementation in freertos

### ISSUE THREAD

**Issue by beikeln** [aws/amazon-freertos#66]
hello  Gaurav Aggarwal:
i  find the codes
in  amazon-freertos/lib/third_party/mcu_vendor/espressif/espidf/components/pthread/testtest_pthread_cxx.cpp,

i cannot find the where the "thread" is implementation in freertos (as same as  xTaskCreate of pthread?) 
i want know the  how the "thread" is compiling 、linking and  Implementation  in freeeros.
i compile the code , e.g  std::thread  t1(func)  using g++, it is ok,
while using arm-none-eabi-g++ , some errors happen.

thank you

**Comment by beikeln** [comment]
hello Gaurav Aggarwal:
some codes  in amazonfreertos/lib/third_party/mcu_vendor/espressif/espidf/components/pthread/testtest_pthread_cxx.cpp,

**Comment by gordonwang0** [comment]
Hi @beikeln,

The `thread` used in ESP's `test_pthread_cxx.cpp` is C++11's `std::thread`.  This is not supported in Amazon FreeRTOS (which is C only).

When you compile that file using `g++`, it's linking against your OS's C++ thread library.  My guess is that `arm-none-eabi-g++` does not have the C++ thread library, hence the errors.  Can you share the compilation errors you're seeing?

**Comment by gordonwang0** [comment]
Hi @beikeln,

Please let me know if you need any more help with this.  Closing issue.
