### ISSUE TITLE
Atmel SAMD21 AWS FreeRTOS

### ISSUE THREAD

**Issue by gtech12** [aws/amazon-freertos#675]
Hi, 

I would like to know if there is support for the Atmel SAMD21 MCU for the AWS FreeRTOS , so I can connect WiFi or cellular modules on the same MCU . 
Is porting needed to be done for this to function on the SAMD21 MCU ?

**Comment by yuhui-zheng** [comment]
Amazon FreeRTOS does not officially support Atmel SAMD21. But FreeRTOS kernel has [a port for Atmel SAMD20](https://www.freertos.org/Atmel_SAMD20_RTOS.html) which is similar that may be worth a shot.

**Comment by WRansohoff** [comment]
We haven't seen any feedback on this in a couple of weeks, so we are closing the issue. Please feel free to re-open it with comments if you have any further questions.
