### ISSUE TITLE
Nordic NRF52840 Custom BLE service Issues.

### ISSUE THREAD

**Issue by ljaynes87** [aws/amazon-freertos#701]
I am trying to add my own custom BLE service to the NRF52840 on the latest release-1.5 branch. I am trying to add a characteristic with notify properties but the application crashes on IotBle_CreateService when adding a characteristic with eBTPropNotify in the properties. I am able to create a service and characteristics for it if i just do read and write properties. 

With just the read and write properties enabled I am able to see the service and characteristics on my phone but when attempting to call IotBle_SendIndication my application once again crashes. It seems to be crashing at the Nordic soft device sd_ble_gatts_hvx function. I've checked the handle, connection id, and uuid before it is sent out and everything seems to be correct. Since there doesn't seem to be any documentation about this I've modeled my code mostly after  the GATT server demo and the iot_ble_device_information.c file include with the Nordic MQTT over BLE demo.

I am not sure what I am doing incorrectly to cause these crashes.

My code for creating the service.

```c

#define app_SERVICE_BASE_UUID    0x11, 0xAA
#define app_SERVICE_UUID_MASK    0x32, 0xF9, 0x79, 0xE6, 0xB5, 0x83, 0xFB, 0x4E, 0xAF, 0x48, 0x68, 0x11, 0x7F, 0xAE
#define app_SERVICE_UUID         {app_SERVICE_BASE_UUID, app_SERVICE_UUID_MASK }

/**
 * @brief Service, characteristic and descriptor UUIDS for app service
 */
#define app_CHAR_UUID_BASE             app_SERVICE_UUID
#define app_TEST_UUID                  { 0x01, 0xAA, app_SERVICE_UUID_MASK }
#define app_TEST_WRITE_UUID            { 0x02, 0xAA, app_SERVICE_UUID_MASK }

/**
 * @brief Number of characteristics, descriptors and included services for app service
 */
#define app_MAX_CHARS               4
#define app_MAX_DESCRS              1
#define app_MAX_INC_SVCS            0

/**
 * @brief Structure used for App Information Service
 */
typedef struct appService
{
    BTService_t * pBLEService;
    uint16_t CCFGVal[ app_MAX_DESCRS ];
    uint16_t BLEConnId;
    uint16_t BLEMtu;
} appService_t;


/*------------------------------------------------------------------------------------*/

static appService_t app_service =
{
  .pBLEService = NULL,
  .BLEConnId  = 65535,
  .BLEMtu     = 0,
  .CCFGVal    = { 0 }
};

#define app_TEST_UUID_TYPE \
{ \
    .uu.uu128 = app_TEST_UUID,\
    .ucType   = eBTuuidType128 \
}

#define app_TEST_WRITE_UUID_TYPE \
{ \
    .uu.uu128 = app_TEST_WRITE_UUID,\
    .ucType   = eBTuuidType128 \
}

#define xappSvcUUID \
{ \
    .uu.uu128 = app_SERVICE_UUID,\
    .ucType   = eBTuuidType128\
}


typedef enum {
  ATTR_SERVICE,
  ATTR_CHAR_END_POINT,
  ATTR_CHAR_TEST_WRITE,
  ATTR_NUMBER
} app_attr_t;

static uint16_t app_handles_buffer[ATTR_NUMBER];

static const BTAttribute_t pAttributeTable[] = {
  {    
     .xServiceUUID =  xappSvcUUID
  },
  {
     .xAttributeType = eBTDbCharacteristic,
     .xCharacteristic = 
     {
        .xUuid = app_TEST_UUID_TYPE,
        .xPermissions = ( IOT_BLE_CHAR_READ_PERM | IOT_BLE_CHAR_WRITE_PERM ),
        .xProperties = ( eBTPropRead | eBTPropWrite )
     }
   },
   {
     .xAttributeType = eBTDbCharacteristic,
     .xCharacteristic = 
     {
        .xUuid = app_TEST_WRITE_UUID_TYPE,
        .xPermissions = ( IOT_BLE_CHAR_READ_PERM ),
        .xProperties  = ( eBTPropRead | eBTPropNotify )
     }
   }
};

static const BTService_t appService = 
{
  .xNumberOfAttributes = ATTR_NUMBER,
  .ucInstId = 0,
  .xType = eBTServiceTypePrimary,
  .pusHandlesBuffer = app_handles_buffer,
  .pxBLEAttributes = (BTAttribute_t *)pAttributeTable
};

void appTestWriteCharCallback( IotBleAttributeEvent_t * pEventParam );


static void appTestCharCallback( IotBleAttributeEvent_t * pEventParam );

static void vMTUChangedCallback( uint16_t connId,
                                 uint16_t usMtu );

static void vConnectionCallback( BTStatus_t status,
                                 uint16_t connId,
                                 bool bConnected,
                                 BTBdaddr_t * pxRemoteBdAddr );


static const IotBleAttributeEventCallback_t pxCallBackArray[ATTR_NUMBER] =
    {
  NULL,
  appTestCharCallback,
  appTestWriteCharCallback,
};


BaseType_t ble_init( void )
{
    BTStatus_t status = eBTStatusFail;
    BaseType_t error = pdFAIL;
    IotBleEventsCallbacks_t callback;

    /* Select the handle buffer. */
    status = IotBle_CreateService( (BTService_t *)&appService, (IotBleAttributeEventCallback_t *)pxCallBackArray );

	if( status == eBTStatusSuccess )
	{
		callback.pMtuChangedCb = vMTUChangedCallback;
		status = IotBle_RegisterEventCb( eBLEMtuChanged, callback );
	}

	if( status == eBTStatusSuccess )
	{
		callback.pConnectionCb = vConnectionCallback;
		status = IotBle_RegisterEventCb( eBLEConnection, callback );
	}

	if( status == eBTStatusSuccess )
	{
		error = pdPASS;
	}

    return error;
}


void IotBle_AddCustomServicesCb(void)
{
  ble_init();
}


void appTestCharCallback( IotBleAttributeEvent_t * pEventParam )
{
    IotBleAttributeData_t attrData = { 0 };
    IotBleEventResponse_t resp;


    if( pEventParam->xEventType == eBLERead )
    {

        attrData.handle = pEventParam->pParamRead->attrHandle;
        attrData.pData = "test";
        attrData.size = strlen( "test" );

        resp.pAttrData = &attrData;
        resp.attrDataOffset = 0;
        resp.eventStatus = eBTStatusSuccess;
        resp.rspErrorStatus = eBTRspErrorNone;

        IotBle_SendResponse( &resp, pEventParam->pParamRead->connId, pEventParam->pParamRead->transId );

    }
}


void appTestWriteCharCallback( IotBleAttributeEvent_t * pEventParam )
{
    IotBleAttributeData_t attrData = { 0 };
    IotBleEventResponse_t resp;


    if( pEventParam->xEventType == eBLERead )
    {

        attrData.handle = pEventParam->pParamRead->attrHandle;
        attrData.pData = "test";
        attrData.size = strlen( "test" );

        resp.pAttrData = &attrData;
        resp.attrDataOffset = 0;
        resp.eventStatus = eBTStatusSuccess;
        resp.rspErrorStatus = eBTRspErrorNone;

        IotBle_SendResponse( &resp, pEventParam->pParamRead->connId, pEventParam->pParamRead->transId );

    }
}



static void vMTUChangedCallback( uint16_t connId,
                                 uint16_t usMtu )
{

//Nothing

}


static void vConnectionCallback( BTStatus_t status,
                                 uint16_t connId,
                                 bool bConnected,
                                 BTBdaddr_t * pxRemoteBdAddr )
{
  if( status == eBTStatusSuccess )
  {
    if( bConnected == true )
    {
      app_service.BLEConnId = connId;  

    }
  }
}


size_t app_ble_send(uint8_t attribute,
                    uint8_t * pData,
                    size_t len)
{

  IotBleAttributeData_t attrData = { 0 };
  IotBleEventResponse_t response =
  {
      .pAttrData      = &attrData,
      .attrDataOffset = 0,
      .eventStatus    = eBTStatusSuccess,
      .rspErrorStatus = eBTRspErrorNone,
  };

  bool status = true;

  attrData.handle = appService.pusHandlesBuffer[attribute];
  attrData.uuid   = appService.pxBLEAttributes[attribute].xCharacteristic.xUuid;
  attrData.pData  = pData;
  attrData.size   = len;


  if(  IotBle_SendIndication( &response, app_service.BLEConnId, false ) != eBTStatusSuccess )
  {
      status = false;
  }

  return status;

}
```

**Comment by ljaynes87** [comment]
I forgot to include this above but I am currently on the latest commit to release-1.5 branch.

**Comment by lt72** [comment]
@huguesBouvier can you please help @ljaynes87 ?

**Comment by huguesBouvier** [comment]
Hey,

The code didn't crash for me but I found some issues in it. Please find the fixed code below. You basically need to have a Client Configuration Descriptor if you want to be able to notify.
`

#define app_SERVICE_BASE_UUID    0x11, 0xAA
#define app_SERVICE_UUID_MASK    0x32, 0xF9, 0x79, 0xE6, 0xB5, 0x83, 0xFB, 0x4E, 0xAF, 0x48, 0x68, 0x11, 0x7F, 0xAE
#define app_SERVICE_UUID         {app_SERVICE_BASE_UUID, app_SERVICE_UUID_MASK }

/**
 * @brief Service, characteristic and descriptor UUIDS for app service
 */
#define app_CHAR_UUID_BASE             app_SERVICE_UUID
#define app_TEST_UUID                  { 0x01, 0xAA, app_SERVICE_UUID_MASK }
#define app_TEST_WRITE_UUID            { 0x02, 0xAA, app_SERVICE_UUID_MASK }

/**
 * @brief Number of characteristics, descriptors and included services for app service
 */
#define app_MAX_CHARS               4
#define app_MAX_DESCRS              1
#define app_MAX_INC_SVCS            0

/**
 * @brief Structure used for App Information Service
 */
typedef struct appService
{
    BTService_t * pBLEService;
    uint16_t CCFGVal[ app_MAX_DESCRS ];
    uint16_t BLEConnId;
    uint16_t BLEMtu;
} appService_t;


/*------------------------------------------------------------------------------------*/

static appService_t app_service =
{
  .pBLEService = NULL,
  .BLEConnId  = 65535,
  .BLEMtu     = 0,
  .CCFGVal    = { 0 }
};

#define app_TEST_UUID_TYPE \
{ \
    .uu.uu128 = app_TEST_UUID,\
    .ucType   = eBTuuidType128 \
}

#define app_TEST_WRITE_UUID_TYPE \
{ \
    .uu.uu128 = app_TEST_WRITE_UUID,\
    .ucType   = eBTuuidType128 \
}

#define xappSvcUUID \
{ \
    .uu.uu128 = app_SERVICE_UUID,\
    .ucType   = eBTuuidType128\
}

#define IOT_INFO_CLIENT_CHAR_CFG_UUID_TYPE        \
    {                                                        \
        .uu.uu16 = 0x2902  , \
        .ucType = eBTuuidType16                              \
    }


typedef enum {
  ATTR_SERVICE,
  ATTR_CHAR_END_POINT,
  ATTR_CHAR_TEST_WRITE,
  ATTR_CCD,
  ATTR_NUMBER
} app_attr_t;

static uint16_t app_handles_buffer[ATTR_NUMBER];

static const BTAttribute_t pAttributeTable[] = {
  {    
     .xServiceUUID =  xappSvcUUID
  },
  {
     .xAttributeType = eBTDbCharacteristic,
     .xCharacteristic = 
     {
        .xUuid = app_TEST_UUID_TYPE,
        .xPermissions = ( IOT_BLE_CHAR_READ_PERM | IOT_BLE_CHAR_WRITE_PERM ),
        .xProperties = ( eBTPropRead | eBTPropWrite )
     }
   },
   {
     .xAttributeType = eBTDbCharacteristic,
     .xCharacteristic = 
     {
        .xUuid = app_TEST_WRITE_UUID_TYPE,
        .xPermissions = ( IOT_BLE_CHAR_READ_PERM ),
        .xProperties  = ( eBTPropRead | eBTPropNotify )
     }
   },
  {
      .xAttributeType = eBTDbDescriptor,
      .xCharacteristicDescr =
      {
          .xUuid        = IOT_INFO_CLIENT_CHAR_CFG_UUID_TYPE,
          .xPermissions = ( IOT_BLE_CHAR_READ_PERM | IOT_BLE_CHAR_WRITE_PERM )
      }
  },
};

static const BTService_t appService = 
{
  .xNumberOfAttributes = ATTR_NUMBER,
  .ucInstId = 0,
  .xType = eBTServiceTypePrimary,
  .pusHandlesBuffer = app_handles_buffer,
  .pxBLEAttributes = (BTAttribute_t *)pAttributeTable
};

void appTestWriteCharCallback( IotBleAttributeEvent_t * pEventParam );


static void appTestCharCallback( IotBleAttributeEvent_t * pEventParam );

static void vMTUChangedCallback( uint16_t connId,
                                 uint16_t usMtu );

static void vConnectionCallback( BTStatus_t status,
                                 uint16_t connId,
                                 bool bConnected,
                                 BTBdaddr_t * pxRemoteBdAddr );


static const IotBleAttributeEventCallback_t pxCallBackArray[ATTR_NUMBER] =
    {
  NULL,
  appTestCharCallback,
  appTestWriteCharCallback,
};


BaseType_t ble_init( void )
{
    BTStatus_t status = eBTStatusFail;
    BaseType_t error = pdFAIL;
    IotBleEventsCallbacks_t callback;

    /* Select the handle buffer. */
    status = IotBle_CreateService( (BTService_t *)&appService, (IotBleAttributeEventCallback_t *)pxCallBackArray );

	if( status == eBTStatusSuccess )
	{
		callback.pMtuChangedCb = vMTUChangedCallback;
		status = IotBle_RegisterEventCb( eBLEMtuChanged, callback );
	}

	if( status == eBTStatusSuccess )
	{
		callback.pConnectionCb = vConnectionCallback;
		status = IotBle_RegisterEventCb( eBLEConnection, callback );
	}

	if( status == eBTStatusSuccess )
	{
		error = pdPASS;
	}

    return error;
}


void IotBle_AddCustomServicesCb(void)
{
  ble_init();
}


void appTestCharCallback( IotBleAttributeEvent_t * pEventParam )
{
    IotBleAttributeData_t attrData = { 0 };
    IotBleEventResponse_t resp;


    if( pEventParam->xEventType == eBLERead )
    {

        attrData.handle = pEventParam->pParamRead->attrHandle;
        attrData.pData = "test";
        attrData.size = strlen( "test" );

        resp.pAttrData = &attrData;
        resp.attrDataOffset = 0;
        resp.eventStatus = eBTStatusSuccess;
        resp.rspErrorStatus = eBTRspErrorNone;

        IotBle_SendResponse( &resp, pEventParam->pParamRead->connId, pEventParam->pParamRead->transId );

    }
}


void appTestWriteCharCallback( IotBleAttributeEvent_t * pEventParam )
{
    IotBleAttributeData_t attrData = { 0 };
    IotBleEventResponse_t resp;


    if( pEventParam->xEventType == eBLERead )
    {

        attrData.handle = pEventParam->pParamRead->attrHandle;
        attrData.pData = "test";
        attrData.size = strlen( "test" );

        resp.pAttrData = &attrData;
        resp.attrDataOffset = 0;
        resp.eventStatus = eBTStatusSuccess;
        resp.rspErrorStatus = eBTRspErrorNone;

        IotBle_SendResponse( &resp, pEventParam->pParamRead->connId, pEventParam->pParamRead->transId );

    }
}



static void vMTUChangedCallback( uint16_t connId,
                                 uint16_t usMtu )
{

//Nothing

}


static void vConnectionCallback( BTStatus_t status,
                                 uint16_t connId,
                                 bool bConnected,
                                 BTBdaddr_t * pxRemoteBdAddr )
{
  if( status == eBTStatusSuccess )
  {
    if( bConnected == true )
    {
      app_service.BLEConnId = connId;  

    }
  }
}


size_t app_ble_send(uint8_t attribute,
                    uint8_t * pData,
                    size_t len)
{

  IotBleAttributeData_t attrData = { 0 };
  IotBleEventResponse_t response =
  {
      .pAttrData      = &attrData,
      .attrDataOffset = 0,
      .eventStatus    = eBTStatusSuccess,
      .rspErrorStatus = eBTRspErrorNone,
  };

  bool status = true;

  attrData.handle = appService.pusHandlesBuffer[attribute];
  attrData.uuid   = appService.pxBLEAttributes[attribute].xCharacteristic.xUuid;
  attrData.pData  = pData;
  attrData.size   = len;


  if(  IotBle_SendIndication( &response, app_service.BLEConnId, false ) != eBTStatusSuccess )
  {
      status = false;
  }

  return status;

}`

**Comment by ljaynes87** [comment]
Thanks. That along with adding an enable notification callback seemed to fix my issues. Thanks for the input.
