### ISSUE TITLE
encoding issue with aws_iot_mqtt_publish using esp-32 @ eu-central-1

### ISSUE THREAD

**Issue by markfink** [aws/amazon-freertos#75]
I get "encoding" issues like with the following received message:

``` json
{
  "format": "string",
  "payload": "\u0000\u0000{  \"temperature\": 22.97,  \"pressure\": 937.89,  \"humidity\": 30.95}",
  "qos": 0,
  "timestamp": 1540800888355,
  "topic": "farm/farm0001/sensor02"
}
```

I do not yet understand where the \u0000 come from. Might also be an AWS issue since I started to get these once I added an iot-rule to write the messages to s3.

Here is the code to assemble and send the message:
``` c
        sprintf(cPayload,
            "{"
            "  \"temperature\": %0.2f,"
            "  \"pressure\": %0.2f,"
            "  \"humidity\": %0.2f"
            "}",
            comp_data.temperature, comp_data.pressure / 100.0, comp_data.humidity
        );
        params.payloadLen = strlen(cPayload);
        rc = aws_iot_mqtt_publish(&client, cTopic, strlen(cTopic), &params);
```

**Comment by RichardBarry** [comment]
Is the message formatted correctly in cPayload?  If not, it might be the sprintf() implementation either does not, or is not configured to, support the %0.2f formatting.

**Comment by markfink** [comment]
@RichardBarry thank you and yes the cPayload is formated just fine - I logged to console and checked:

``` c
ESP_LOGI(TAG, "%d - #%s#", (int) params.payloadLen, (char *)params.payload);
```

I think it was an AWS issue since I can not reproduce it anymore.
