### ISSUE TITLE
MQTT demo with Amazon FreeRTOS and Android as Mqtt proxy

### ISSUE THREAD

**Issue by Amijic** [aws/amazon-freertos#752]
Greetings,

Currently I am porting Amazon FreeRTOS on my nRF52840 DK and trying to connect to the cloud with mqtt proxy on my android device. After configuring the demo and downloading the android app on my phone, I couldnt find some of the constants that needed to be defined. I could not find amazon-freertos-ble-android-sdk/app/src/main/java/com/amazon/aws/freertosandroid/MainActivity.java.

In the end I configured the json file and DemoConstants.java in wich I wrote:
AWS_IOT_POLICY_NAME:
AWS_IOT_REGION:

In json file I configured:
Under CognitoIdentity, redefine the following variables:
PoolId: Your Amazon Cognito identity pool ID.
Region: Your AWS Region.

Under CognitoUserPool, redefine the following variables:
PoolId: Your Amazon Cognito user pool ID.
AppClientId: Your app client ID.
AppClientSecret: Your app client secret.
Region: Your AWS Region.

Then I installed the app on my android device and started a BLE demo on my board.
First problem is related to my android app, I can not click "More.." option on my device.

In my SEGGER terminal this is the output: 

The RAM must start at 200046f8, it's size must be 3b908
Common libraries successfully initialized.
No networks connected. Waiting for a network connection. 
2 989 https://forums.aws.amazon.com/ Requesting to update ATT MTU to 247 bytes on connection 0x0.3 989 https://forums.aws.amazon.com/ sd_ble_gattc_exchange_mtu_request() on connection 0x0 returned busy, will retry.4 989 https://forums.aws.amazon.com/ BLE Connected to remote device, connId = 0

Successfully initialized the demo. Network type for the demo6 989 https://forums.aws.amazon.com/ https://forums.aws.amazon.com/https://forums.aws.amazon.com/https://forums.aws.amazon.com/ MQTT library successfully initialized.
MQTT demo client identifier is XXXXXX (length X).
Numeric comparison:"some numbers"
Press 'y' to confirm
UNKNOWN BLE EVENT 35

Is it possible that there are some steps I missed that are not written in https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_nordic.html.

Best regards :)

**Comment by WRansohoff** [comment]
Does the `UNKNOWN BLE EVENT 35` error happen after you press 'y' to confirm the pairing?

One possible cause of those errors seems to be that mobile devices often cache Bluetooth connection data, and that cached data can sometimes become stale or unreliable. In your phone's Bluetooth settings, can you see the nRF52840 board under the list of paired devices? If it does show up, could you try deleting the connection, restarting the phone, and then re-pairing the devices?

**Comment by Amijic** [comment]
Hello,

Thank you for answering. 

The UNKNOWN BLE EVENT 35 error shows up before I press 'y' to confirm pairing. It doesnt give me a chance to press 'y' it immediately throws an error. In my mobile app I can detect my nRF52840 but it wont connect. However, is it possible that my phone cant accses the board because i didnt put MAC adress of a device and I dont have MainActivity.java. When I downloaded Android SDK for Amazon FreeRTOS the MainActivity.java file was not there. 
Nevertheless, I configured all other parameters like Amazon Cognito, AWS IoT policy, region in my JSON file and DemoConstants.java.  



Best regards :)

**Comment by bxpan** [comment]
Hi Amijic,

There is no MainActivity.java in the demo app. The documentation is out-of-date. You need to modify DemoConstants.java and the awsconfiguration.json file, which you did. The fact that "more" button is not enabled suggests the connection is not fully ready. Could you please provide following information:



Build info
What is the branch and commit on the device side?
What is the branch and tag the SDK side?
Does pulling the latest code help resolve the issue?

System info
What is the Android version?
What is the bluetooth version?

To Reproduce
What is the frequency of this issue?
Steps to reproduce the behavior:

Log
Could you provide log on both the device side and SDK side?

Additional context
Add any other context about the problem here.

**Comment by Amijic** [comment]
Hello,

Build info:
Regarding my device I have last version of Amazon FreeRTOS, specificly commit  4fa09aa  on 18 Apr. I downloaded the latest version of SDK commit b073707  23 hours ago. 

Again it shows the same thing. It does not let me press 'y' on my segger terminal connection immediately chrashes

System info:
Regarding my system info, my phone has Bluetooth 5 and it is Android 9 version.

To reproduce:

I followed all the steps in Getting started tutorial on nRF52840 DK. Firstly I set my AWS IoT thing and policy. After that I got my Amazon Cognito identity and user pool. 
In next step I downloaded amazon freertos and configured the demo for simple hello with BLE and MQTT. Afterwards I downloaded the SDK and installed it on my mobile device. In Android Studio I configured JSON file and DemoConstants.java as it was said in the tutorial. Then I powered up both the board and the app and UNKNOW BLE EVENT 35 error occurs.


Log: 

![Izrezak](https://user-images.githubusercontent.com/50965043/59533957-3c34d700-8eed-11e9-8c45-97e5ff22384f.PNG)

This is my output in Segger. And in my app I just get a pairing request from the board and when I click OK it just disconnects. 

Additional context:

Do you think that missing MAC adress can be the problem. In the tutorial for this demo it says that it is needed to put MAC adress of a device in MainActivity.java.

This is my IAM policy;
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Effect":"Allow",
         "Action":[
            "iot:AttachPolicy",
            "iot:AttachPrincipalPolicy",
            "iot:Connect",
            "iot:Publish",
            "iot:Subscribe",
            "iot:Receive",
            "iot:GetThingShadow",
            "iot:UpdateThingShadow",
            "iot:DeleteThingShadow"
         ],
         "Resource":[
            "*"
         ]
      }
   ]
}

It is the same as my AWS IoT policy in my AWS console.

Considering that I used mobile device as proxy I did not create certificate for my AWS IoT thing.
In my Amazon FreeRTOS I configured the demo by uncommenting certain functions and hardcoding my endpoint and my IoT thing.

Kind regards :)

**Comment by bxpan** [comment]
Cloud you please share adb log from android studio? 

You do not need to to add mac address in the demo app as this step is no longer needed. When you open the demo app, you should see the mac address of the device, and you can toggle the switch to connect to it. To debug why the "More" button is not enabled, please share the adb log from your demo app.

**Comment by Amijic** [comment]
Hello,

This is output of my info log on ADB is

2019-06-15 15:42:08.674 31366-31366/software.amazon.freertos.demo I/DeviceScanFragment: scan button clicked.
2019-06-15 15:42:08.677 31366-31366/software.amazon.freertos.demo I/AmazonFreeRTOSManager: Starting ble device scan
2019-06-15 15:42:08.891 31366-31366/software.amazon.freertos.demo I/chatty: uid=10239(software.amazon.freertos.demo) identical 1 line
2019-06-15 15:42:09.772 31366-31366/software.amazon.freertos.demo I/DeviceScanFragment: connect switch isChecked: ON
2019-06-15 15:42:09.907 31366-31382/software.amazon.freertos.demo I/FRD: BLE connection state changed: 0; new state: BLE_CONNECTED
2019-06-15 15:42:09.909 31366-31382/software.amazon.freertos.demo I/FRD: Connected to GATT server.
2019-06-15 15:42:09.913 31366-31382/software.amazon.freertos.demo I/BluetoothDevice: createBond() for device F4:B6:6C:58:32:F1 called by pid: 31366 tid: 31382
2019-06-15 15:42:10.891 31366-31382/software.amazon.freertos.demo I/FRD: Discovered Ble gatt services successfully. Bonding state: 11
2019-06-15 15:42:18.689 31366-31464/software.amazon.freertos.demo I/AmazonFreeRTOSManager: Stopping ble device scan
2019-06-15 15:42:40.488 31366-31382/software.amazon.freertos.demo I/FRD: BLE connection state changed: 19; new state: BLE_DISCONNECTED
2019-06-15 15:42:40.488 31366-31382/software.amazon.freertos.demo I/FRD: Disconnected from GATT server.
2019-06-15 15:42:40.488 31366-31382/software.amazon.freertos.demo I/DeviceScanFragment: BLE connection status changed to: BLE_DISCONNECTED
2019-06-15 15:42:40.497 31366-31366/software.amazon.freertos.demo I/DeviceScanFragment: connect switch isChecked: OFF
2019-06-15 15:42:42.188 31366-31366/software.amazon.freertos.demo I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-06-15 15:42:46.263 31366-31366/software.amazon.freertos.demo I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus

**Comment by bxpan** [comment]
There seems to be some issue during BLE bonding. It is not fully paired and bonded, and it got disconnected. Could you share the BLE configuration below on the device side: 

#define IOT_BLE_ENABLE_NUMERIC_COMPARISON        ( 1 )
#define IOT_BLE_ENABLE_SECURE_CONNECTION         ( 1 )
#define IOT_BLE_INPUT_OUTPUT (eBTIODisplayYesNo)

> 2019-06-15 15:42:10.891 31366-31382/software.amazon.freertos.demo I/FRD: Discovered Ble gatt services successfully. Bonding state: 11
2019-06-15 15:42:18.689 31366-31464/software.amazon.freertos.demo I/AmazonFreeRTOSManager: Stopping ble device scan
2019-06-15 15:42:40.488 31366-31382/software.amazon.freertos.demo I/FRD: BLE connection state changed: 19; new state: BLE_DISCONNECTED

**Comment by Amijic** [comment]
#ifndef IOT_BLE_ENABLE_NUMERIC_COMPARISON
#define IOT_BLE_ENABLE_NUMERIC_COMPARISON        ( 1 )
#endif


#ifndef IOT_BLE_ENABLE_SECURE_CONNECTION
#define IOT_BLE_ENABLE_SECURE_CONNECTION         ( 1 )
#endif


#ifndef IOT_BLE_INPUT_OUTPUT
#define IOT_BLE_INPUT_OUTPUT eBTIODisplayYesNo
#endif

This is what I got in my iot_ble_config_defaults.h file.

**Comment by bxpan** [comment]
These look correct .

> #ifndef IOT_BLE_ENABLE_NUMERIC_COMPARISON
#define IOT_BLE_ENABLE_NUMERIC_COMPARISON ( 1 )
#endif
#ifndef IOT_BLE_ENABLE_SECURE_CONNECTION
#define IOT_BLE_ENABLE_SECURE_CONNECTION ( 1 )
#endif
#ifndef IOT_BLE_INPUT_OUTPUT
#define IOT_BLE_INPUT_OUTPUT eBTIODisplayYesNo
#endif

Error 19 indicates that it was disconnected from the device side. 

> 2019-06-15 15:42:40.488 31366-31382/software.amazon.freertos.demo I/FRD: BLE connection state changed: 19; new state: BLE_DISCONNECTED

**Comment by Amijic** [comment]
Can you give me few tips on where the mistake could be? 

I did not hardcode my credidentials in my device code because it says in the tutorial that it is not needed when I am using mobile device as MQTT proxy. 

I enabled the demo by uncommenting and entered my endpoint and IoT thing name. I really dont know what to try anymore :D

**Comment by bxpan** [comment]
Did you see the pair notification from your app? Were you able to press the pair button successfully? 

Another option to try is that without using the demo app, go to the Bluetooth settings on your phone, and see if the device shows up and try to connect and pair to the device. Please let us know if this works?

**Comment by Amijic** [comment]
Hello,

I followed you instruction and my phone does see the device using Bluetooth settings. When I tried to pair ( I can press the pair button successfully) same error occurs UNKNOW BLE EVENT 35.


![image](https://user-images.githubusercontent.com/50965043/60217100-32579000-986c-11e9-9512-0116ae6d34e2.png)

This is my Segger terminal output.

**Comment by huguesBouvier** [comment]
Hello,

The UNKNOW BLE EVENT 35 is an un-handled message. It is not harmful.
We are working on supressing it cleaning but it won't give you any problem.

**Comment by bxpan** [comment]
Just to clarify, "The UNKNOW BLE EVENT 35" is not the cause of the disconnection. This is simply an unhandled message type. There's some other issues that caused the disconnection. We still need to root cause this.

**Comment by Amijic** [comment]
Hello,

Not much is changed on my device code. I just uncommented the demo I wanted to use and hardcoded my endopoint and my AWS IoT Thing name. 
Afterwards, I defined #define IOT_BLE_ADD_CUSTOM_SERVICES ( 1 ) in my iot_ble_config.h file

I did not find this file in my path.

![image](https://user-images.githubusercontent.com/50965043/60337965-c593e100-99a4-11e9-8e19-f3af9e8f925b.png)

This is my file tree. 

![image](https://user-images.githubusercontent.com/50965043/60338243-bcefda80-99a5-11e9-91f7-db9fa1270b3b.png)

Is it possible that lack of this definition can cause the device to disconnect?

**Comment by bxpan** [comment]
> Is it possible that the region has anything to do with connection? I am in Europe and my AWS default region is US West(Oregon).

This is not an issue. The disconnection is between the device and the phone over BLE, it is not disconnected between phone and the cloud.

**Comment by huguesBouvier** [comment]
Could you repport the error statuses? It should be displayed at this line:
https://github.com/aws/amazon-freertos/blob/b76006df130102971b5f3575b7a85356c5439394/vendors/nordic/boards/nrf52840-dk/ports/ble/aws_ble_hal_common_gap.c#L1556
There another possibility, we support only BLE 4.2 and above. Could you check the version of the BT stack of your phone?

**Comment by Amijic** [comment]
The RAM must start at 200046f8, it's size must be 3b908
0 0 [iot_thread] [INFO ][COMMON][0] Common libraries successfully initialized.
1 2 [iot_thread] [INFO ][DEMO][20] No networks connected. Waiting for a network connection. 
2 2821 [BLE] Requesting to update ATT MTU to 247 bytes on connection 0x0.3 2821 [BLE] sd_ble_gattc_exchange_mtu_request() on connection 0x0 returned busy, will retry.4 2821 [BLE] [INFO ][DEMO][28210] BLE Connected to remote device, connId = 0

5 2821 [iot_thread] [INFO ][DEMO][28210] Successfully initialized the demo. Network type for the de6 2821 [iot_thread] [INFO ][MQTT][28210] MQTT library successfully initialized.
7 2821 [iot_thread] [INFO ][DEMO][28210] MQTT demo client identifier is BLEthing (length 8).
8 2857 [InputTask] Numeric comparison:388263
9 2857 [InputTask] Press 'y' to confirm
10 2903 [BLE] UNKNOWN BLE EVENT 35
11 5854 [BLE] Failed to secure connection. Disconnecting.12 5854 [BLE] BLE_GAP_EVT_AUTH_STATUS
13 5855 [BLE] [INFO ][DEMO][58550] BLE disconnected with remote device, connId = 0 

14 5855 [BLE] Disconnect received for MQTT service instance 0


This is my Debugg Terminal.

**Comment by huguesBouvier** [comment]
You don't need to download the C SDK.
The parameter is located here: https://github.com/aws/amazon-freertos/blob/6144acbe61db1928a9a925f00fdf85ec239e012b/vendors/nordic/boards/nrf52840-dk/aws_demos/config_files/aws_demo_config.h#L40
Could you report the detailed error status at the following location?
Could you repport the error statuses? It should be displayed at this line:
https://github.com/aws/amazon-freertos/blob/b76006df130102971b5f3575b7a85356c5439394/vendors/nordic/boards/nrf52840-dk/ports/ble/aws_ble_hal_common_gap.c#L1556
Thanks!

**Comment by Amijic** [comment]
Can you tell me what do you mean by report the error statuses? Isnt that just the debug terminal messages?

**Comment by huguesBouvier** [comment]
No, that NRF debug log is not reported. I can't read the string "PM_EVT_CONN_SEC_FAILED src:" from your terminal

**Comment by Amijic** [comment]
Greetings, 

My build wont run on my board when I enable NRF_LOG in my sdk_config.h
![image](https://user-images.githubusercontent.com/50965043/60773519-f2fc2f80-a106-11e9-8df4-51202aa88286.png)

When I try to debugg it just stops in unknow function.

**Comment by huguesBouvier** [comment]
I have had issues with step by step too. But you could:
1.  Add a breakpoint there and check the statuses (do not step inside, just stop the program where you want)
2. Use FreeRTOS configPRINTF to output the message. Make sure that the totality of the message is displayed.
