### ISSUE TITLE
SECURE_SOCKETS_SetSockOpt_SERVER_NAME_INDICATION failed 

### ISSUE THREAD

**Issue by wxiangcheng** [aws/amazon-freertos#78]
Hi, i'm confused about this test. Through sniffer log I can see that even with wrong SNI info in client hello message the connection still succeed but I suppose it should fail. The question is will amazon's server check this element or did I miss any settings?
The failure info is "Connect worked when subject name check should have failed it." Thanks.

**Comment by aggarg** [comment]
Hi,

SNI is a hint for the server. The Amazon server will still send the server certificate even when the SNI info is wrong in the Client Hello message. This test expects that the client checks the ```Server Certificate Subject Name``` and rejects the connection as the ```Server Certificate Subject Name``` in the received certificate is different than what was indicated in the Client Hello message.

So essentially you need to check why your TLS client is not performing Server Certificate Name check.

Thanks.

**Comment by wxiangcheng** [comment]
Thanks.
