### ISSUE TITLE
Receiving data from a queue based on which task sent the data

### ISSUE THREAD

**Issue by gokcedilek** [aws/amazon-freertos#813]
Hello,

I have multiple sender and receiver tasks using the same queue data type. I want the sender functions to only receive data from a given sender task (ie. sender1 -> receiver1, sender2 -> receiver2). Is there a way to implement this behavior before receiving and removing the data from the queue? Or, would I have to use a separate queue for the sender-receiver pairs?

Thank you!

**Comment by chegewara** [comment]
Hi,
in your case it may better to try with TaskNotify chain instead of queue chain.

**Comment by alexa-noxon** [comment]
Hi gokcedilek,
Is there a particular Amazon FreeRTOS library/port that you are trying to use?
