### ISSUE TITLE
Error while running 'python SetupAWS.py setup'

### ISSUE THREAD

**Issue by KunjalRupala** [aws/amazon-freertos#841]
Hey,
I am new to AWS and am trying to get the latest version of FreeRTOS into my windows system to operate along with ESP32-DevKitC. Whenever I try to run the 'python SetupAWS.py setup' to run the configuration script, it shows me the following error:

![Screenshot (1)](https://user-images.githubusercontent.com/29608004/60098697-bed25780-9773-11e9-8ace-a7ca16b54369.png)

The content of my 'configure.json' file is as follows:
```cpp
{
    "afr_source_dir":"C:/AmazonFreeRTOS/",
    "thing_name":"first",
    "wifi_ssid":"XXXXXXX",
    "wifi_password":"XXXXXXXX",
    "wifi_security":"eWiFiSecurityWPA2"
}
``` 
My 'aws configure' is also in sync with my access keys and I have no thing with the same name

Please help me resolve the issue.

Thank you!

**Comment by tgsong** [comment]
Hi, can you double check if you're looking at the correct region? You can also try list things from AWS CLI by running `aws iot list-things` from your commandline. This should give you the same result, the python script is just calling the AWS SDK under the hood.

**Comment by KunjalRupala** [comment]
Hey tgsong,
I have double checked my region its the same. In addition to that i also tried ```aws iot list-things``` as suugested by you but still it gives me the following error:

```An error occurred (UnrecognizedClientException) when calling the ListThings operation: The security token included in the request is invalid.```

**Comment by sheldon123z** [comment]
Hi, exactly the same errors happened here. Any suggestions ? I have fixed the buggy code mentioned in the [f9c987a](https://github.com/aws/amazon-freertos/commit/f9c987a4537a7f4abd684348c5194ed672eaaadf) but the same error still happens.

**Comment by alexa-noxon** [comment]
Do you have multi-factor authentication enabled for your account? 
If so, maybe this article could help https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/

One more thing to check might be whether the user that you set during aws configure has permissions to perform all the actions (For example, I have a user with 'AWSIoTFullAccess'), although I would expect a message along the lines of User "is not authorized to perform: iot:ListThings on resource" if that were the case.

**Comment by alexa-noxon** [comment]
One more idea- I was able to replicate the error message you are getting by making the user who's credentials I was using in IAM "Inactive"

![image](https://user-images.githubusercontent.com/33439348/60474462-f97e3900-9c26-11e9-8faa-718f6a009b26.png)

Can you also check that your IAM user is "active"?

If you are not using MFA and your user is 'active' with permissions that include the "AWSIoTFullAccess", try upgrading to the most recent aws cli version.

Let me know if this fixes your issue!

**Comment by ravibhagavandas** [comment]
Hi @KunjalRupala,

Does the suggestions fixed the issue ?

**Comment by pvyawaha** [comment]
Hi KunjalRupala,

Closing this issue now, please reopen if you have more questions.
