### ISSUE TITLE
.gitignore doesn't work. and outdated

### ISSUE THREAD

**Issue by povi2946** [aws/amazon-freertos#842]
Hi, it seems that .gitignore doesn't work for AWS files and folders. It works only on files created additionally. 

Also to note that 
demos/include/aws_clientcredential.h
directory changed from 
demos/common/include/aws_clientcredential.h
So, .gitignore file paths should be updated. 

My goal is to add credentials files to .gitignore but it doesn't work.
Thank you.

**Comment by tgsong** [comment]
Hi, thanks for reporting this, our `.gitignore` file has been modified by mistake, we will roll back to what it was before. It shouldn't reference any file that's already tracked by git.

**Comment by alexa-noxon** [comment]
I have revised our .gitignore paths and modified/added new .gitignores to match with the new directory structure.

Thanks again for pointing this out.
