### ISSUE TITLE
nRF52 Thread stack

### ISSUE THREAD

**Issue by vervaekejonathan** [aws/amazon-freertos#884]
Thanks for the nRF52 support.

Currently, this uses the nRF5_SDK_15.2.0 stack from Nordic.
Can the [nrf5 SDK for Thread and Zigbee](https://www.nordicsemi.com/?sc_itemid=%7B55A66FBE-42A1-4ABE-A8F4-17F8D86DD41A%7D) be supported too?

This would allow thread networks instead of BLE.
Thanks.

**Comment by huguesBouvier** [comment]
Hello,

Thank you :).
Sorry, as of now we don't have plan to add support a different SDK.
The files important for the port are located in the freeRTOS repo:
https://github.com/aws/amazon-freertos/tree/master/freertos_kernel/portable/CMSIS/nrf52
https://github.com/aws/amazon-freertos/tree/master/freertos_kernel/portable/GCC/nrf52840-dk
You may be able to do your own port using those.
Best,

Hugues
