### ISSUE TITLE
typo in lib/crypto/aws_crypto.c

### ISSUE THREAD

**Issue by captcha1** [aws/amazon-freertos#9]
`

diff --git a/lib/crypto/aws_crypto.c b/lib/crypto/aws_crypto.c
index 653e5ad..de969f7 100644
--- a/lib/crypto/aws_crypto.c
+++ b/lib/crypto/aws_crypto.c
@@ -34,7 +34,7 @@
 #include "mbedtls/config.h"
 #include "mbedtls/platform.h"
 #include "mbedtls/sha256.h"
-#include "mbedTLS/sha1.h"
+#include "mbedtls/sha1.h"
 #include "mbedtls/pk.h"
 #include "mbedtls/x509_crt.h"

`

**Comment by RichardBarry** [comment]
Thanks for taking the time to report.

**Comment by huguesBouvier** [comment]
Thank you for reporting the issue.
It has been fixed.
