### ISSUE TITLE
Cmake tool error

### ISSUE THREAD

**Issue by sheldon123z** [aws/amazon-freertos#903]
**Describe the bug**

I encountered cmake errors while compiling FreeRTOS project under windows 
-------------------------------terminal record----------------------------------------------------------

The C compiler

  "C:/Program Files/Espressif/ESP-IDF Tools/toolchain/bin/xtensa-esp32-elf-gcc.exe"

is not able to compile a simple test program.

It fails with the following output:

  Change Dir: C:/Users/shzheng/Desktop/amazon-freertos-master/build/CMakeFiles/CMakeTmp
  
  Run Build Command(s):C:/PROGRA~1/ESPRES~1/ESP-ID~1/ninja.exe cmTC_22a16 
  [1/2] Building C object CMakeFiles/cmTC_22a16.dir/testCCompiler.c.obj
  [2/2] Linking C executable cmTC_22a16.exe
  FAILED: cmTC_22a16.exe 
  cmd.exe /C "cd . && C:\PROGRA~1\ESPRES~1\ESP-ID~1\TOOLCH~1\bin\XT8994~1.EXE    CMakeFiles/cmTC_22a16.dir/testCCompiler.c.obj  -o cmTC_22a16.exe -Wl,--out-implib,libcmTC_22a16.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
  c:/progra~1/espres~1/esp-id~1/toolch~1/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: unrecognized option '--out-implib'
  c:/progra~1/espres~1/esp-id~1/toolch~1/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: use the --help option for usage information
  collect2.exe: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.
  

CMake will not be able to correctly generate this project.
-----------------------------------------.----------------------------------------------------------------
**System information**
- Which hardware board or part numbers? esp32 
- IDE used 
- Operating System [Windows|
- Project [Custom Application|MQTT|Shadow|Greengrass|OTA|Device Defender|TCP Echo|Sub pub Demo|Simple TCP Server]
- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 

**Expected behavior**

**Screenshots or console output**
If appropriate, please cut-and-paste the console output to explain the issue. If possible, include the call stack. 

**To reproduce**

1. Using cmake 3.15 
2. Following the instruction on FreeRTOS amazon page

**Code to reproduce the bug**
The code should be wrapped in the cpp tag in order to be displayed clearly. For example:

```cpp
printf("Hello World")
```

If the code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

**Additional context**

Thank you!

**Comment by sarenameas** [comment]
Hello.,

Are you following the instructions under https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html#build-and-run-example-espressif ?

I am using Windows and I can compile straight out of the box with the following commands starting from the amazon-freertos root:
`make -DVENDOR=espressif -DBOARD=esp32_wrover_kit -DCOMPILER=xtensa-esp32 -GNinja -S . -B build`
`cd build`
`ninja`

I noticed that you have a CMakeTmp/ tmp folder that we do not have by default. This is not something that we can account for in this troubleshoot. Also there seems to be some failure in your "cmTC_22a16.exe" program not being in the PATH for ninja to execute.

I noticed that you have some extra options "-out-implib". I do not believe this is used in our default configuration. If xtensa-esp32-elf-gcc does not support this, then the most I can suggest is updating to a more recent version. Espressif distributes their toolchain here: https://docs.espressif.com/projects/esp-idf/en/v3.1.3/get-started-cmake/windows-setup.html
