### ISSUE TITLE
BLE: Provide ability to selectively start Data Info Service and Data Transfer Service

### ISSUE THREAD

**Issue by mtalreja-a** [aws/amazon-freertos#950]
**Is your feature request related to a problem? Please describe.**  
Customers need ability to disable the two services if they are building a custom service and don't need mobile SDK MQTT broker support

**Describe the solution you would like.**  
Create #defines to allow/disallow creation of the info and transfer services.

Thank you!

**Comment by ravibhagavandas** [comment]
@mtalreja-a,
Thanks for reporting this. I have created a PR for the solution: 
https://github.com/aws/amazon-freertos/pull/952

**Comment by ravibhagavandas** [comment]
PR has been merged. Please try the latest master branch and reopen the issue if you have any issues.
